import type { Tema, Termino } from './tipos';

/** Parejas de animales que se parecen lo justo. */
const terminos: readonly Termino[] = [
  { a: 'Perro', b: 'Lobo', pistas: ['correa', 'fiel', 'ladra'] },
  { a: 'Gato', b: 'Tigre', pistas: ['tejado', 'ronronea', 'independiente'] },
  { a: 'Caballo', b: 'Burro', pistas: ['establo', 'galope', 'herradura'] },
  { a: 'Delfín', b: 'Tiburón', pistas: ['listo', 'salta', 'acuario'] },
  { a: 'Pingüino', b: 'Foca', pistas: ['frac', 'torpe', 'hielo'] },
  { a: 'Águila', b: 'Halcón', pistas: ['altura', 'vista', 'escudo'] },
  { a: 'Abeja', b: 'Avispa', pistas: ['miel', 'colmena', 'flores'] },
  { a: 'Elefante', b: 'Rinoceronte', pistas: ['memoria', 'trompa', 'enorme'] },
  { a: 'Serpiente', b: 'Lagarto', pistas: ['arrastra', 'muda', 'veneno'] },
  { a: 'Búho', b: 'Lechuza', pistas: ['noche', 'sabio', 'cuello'] },
  { a: 'Pulpo', b: 'Calamar', pistas: ['tinta', 'ocho', 'gallego'] },
  { a: 'Camello', b: 'Llama', pistas: ['desierto', 'joroba', 'aguanta'] },
  { a: 'Vaca', b: 'Toro', pistas: ['cuernos', 'prado', 'granja'] },
  { a: 'Oveja', b: 'Cabra', pistas: ['rebaño', 'queso', 'prado'] },
  { a: 'Cerdo', b: 'Jabalí', pistas: ['barro', 'hocico', 'granja'] },
  { a: 'Ratón', b: 'Rata', pistas: ['queso', 'agujero', 'bigotes'] },
  { a: 'Conejo', b: 'Liebre', pistas: ['orejas', 'salto', 'madriguera'] },
  { a: 'León', b: 'Leopardo', pistas: ['selva', 'rugido', 'zoo'] },
  { a: 'Oso', b: 'Panda', pistas: ['miel', 'cueva', 'peluche'] },
  { a: 'Jirafa', b: 'Cebra', pistas: ['áfrica', 'zoo', 'sabana'] },
  { a: 'Ñu', b: 'Antílope', pistas: ['manada', 'cuernos', 'sabana'] },
  { a: 'Hipopótamo', b: 'Manatí', pistas: ['agua', 'gordo', 'lento'] },
  { a: 'Gorila', b: 'Chimpancé', pistas: ['zoo', 'parientes', 'plátano'] },
  { a: 'Mono', b: 'Mandril', pistas: ['trepa', 'cola', 'cacahuete'] },
  { a: 'Orangután', b: 'Gibón', pistas: ['brazos', 'árbol', 'columpio'] },
  { a: 'Canguro', b: 'Koala', pistas: ['australia', 'zoo', 'raro'] },
  { a: 'Perezoso', b: 'Armadillo', pistas: ['lento', 'raro', 'sudamérica'] },
  { a: 'Ciervo', b: 'Corzo', pistas: ['bosque', 'cuernos', 'caza'] },
  { a: 'Reno', b: 'Alce', pistas: ['nieve', 'cornamenta', 'norte'] },
  { a: 'Gamo', b: 'Rebeco', pistas: ['monte', 'cuernos', 'caza'] },
  { a: 'Zorro', b: 'Chacal', pistas: ['astuto', 'cola', 'gallinas'] },
  { a: 'Lince', b: 'Puma', pistas: ['acecho', 'montaña', 'silencio'] },
  { a: 'Pantera', b: 'Jaguar', pistas: ['selva', 'sigilo', 'noche'] },
  { a: 'Guepardo', b: 'Ocelote', pistas: ['manchas', 'rápido', 'caza'] },
  { a: 'Hiena', b: 'Coyote', pistas: ['risa', 'noche', 'carroña'] },
  { a: 'Búfalo', b: 'Bisonte', pistas: ['manada', 'cuernos', 'pradera'] },
  { a: 'Buey', b: 'Mula', pistas: ['tira', 'campo', 'lento'] },
  { a: 'Yegua', b: 'Potro', pistas: ['establo', 'crin', 'montar'] },
  { a: 'Poni', b: 'Mustang', pistas: ['pequeño', 'montar', 'crin'] },
  { a: 'Cordero', b: 'Cabrito', pistas: ['pascua', 'tierno', 'leche'] },
  { a: 'Ardilla', b: 'Hámster', pistas: ['nueces', 'mofletes', 'rueda'] },
  { a: 'Erizo', b: 'Puercoespín', pistas: ['pinchos', 'bola', 'bosque'] },
  { a: 'Topo', b: 'Topillo', pistas: ['tierra', 'túnel', 'ciego'] },
  { a: 'Murciélago', b: 'Desmán', pistas: ['cueva', 'noche', 'raro'] },
  { a: 'Nutria', b: 'Castor', pistas: ['río', 'mojado', 'presa'] },
  { a: 'Mapache', b: 'Tejón', pistas: ['antifaz', 'noche', 'basura'] },
  { a: 'Comadreja', b: 'Hurón', pistas: ['largo', 'gallinero', 'caza'] },
  { a: 'Marta', b: 'Visón', pistas: ['piel', 'bosque', 'abrigo'] },
  { a: 'Morsa', b: 'Narval', pistas: ['colmillo', 'ártico', 'hielo'] },
  { a: 'Ballena', b: 'Orca', pistas: ['sopla', 'mar', 'grande'] },
  { a: 'Cachalote', b: 'Beluga', pistas: ['canto', 'mar', 'enorme'] },
  { a: 'Alpaca', b: 'Vicuña', pistas: ['andes', 'lana', 'suave'] },
  { a: 'Cabra montés', b: 'Muflón', pistas: ['risco', 'cuernos', 'caza'] },
  { a: 'Íbice', b: 'Gamuza', pistas: ['alpe', 'salto', 'cuernos'] },
  { a: 'Suricata', b: 'Mangosta', pistas: ['atalaya', 'grupo', 'desierto'] },
  { a: 'Coatí', b: 'Panda rojo', pistas: ['cola', 'árbol', 'ladrón'] },
  { a: 'Jineta', b: 'Meloncillo', pistas: ['nocturno', 'monte', 'silvestre'] },
  { a: 'Paloma', b: 'Tórtola', pistas: ['plaza', 'arrullo', 'migas'] },
  { a: 'Gallina', b: 'Gallo', pistas: ['corral', 'amanece', 'pluma'] },
  { a: 'Pato', b: 'Ganso', pistas: ['estanque', 'grazna', 'pluma'] },
  { a: 'Cisne', b: 'Flamenco', pistas: ['cuello', 'lago', 'elegante'] },
  { a: 'Cuervo', b: 'Urraca', pistas: ['negro', 'ladrona', 'grazna'] },
  { a: 'Gorrión', b: 'Jilguero', pistas: ['terraza', 'miga', 'pequeño'] },
  { a: 'Canario', b: 'Periquito', pistas: ['jaula', 'canta', 'color'] },
  { a: 'Loro', b: 'Cacatúa', pistas: ['habla', 'pico', 'trópico'] },
  { a: 'Pavo', b: 'Faisán', pistas: ['navidad', 'corral', 'cola'] },
  { a: 'Pavo real', b: 'Quetzal', pistas: ['cola', 'color', 'presumido'] },
  { a: 'Cigüeña', b: 'Grulla', pistas: ['nido', 'viaje', 'humedal'] },
  { a: 'Pelícano', b: 'Garza', pistas: ['pico', 'pesca', 'agua'] },
  { a: 'Buitre', b: 'Cóndor', pistas: ['carroña', 'calvo', 'planea'] },
  { a: 'Alimoche', b: 'Milano', pistas: ['planea', 'campo', 'carroña'] },
  { a: 'Golondrina', b: 'Vencejo', pistas: ['verano', 'nido', 'rápido'] },
  { a: 'Colibrí', b: 'Abejaruco', pistas: ['flores', 'pico', 'color'] },
  { a: 'Ruiseñor', b: 'Petirrojo', pistas: ['canta', 'pecho', 'jardín'] },
  { a: 'Cuco', b: 'Carpintero', pistas: ['bosque', 'agujero', 'nido'] },
  { a: 'Gaviota', b: 'Albatros', pistas: ['playa', 'vuela', 'pez'] },
  { a: 'Cormorán', b: 'Alcatraz', pistas: ['bucea', 'acantilado', 'pez'] },
  { a: 'Perdiz', b: 'Codorniz', pistas: ['caza', 'campo', 'bandada'] },
  { a: 'Urogallo', b: 'Avutarda', pistas: ['canto', 'campo', 'grande'] },
  { a: 'Abubilla', b: 'Alondra', pistas: ['cresta', 'campo', 'vuelo'] },
  { a: 'Avestruz', b: 'Ñandú', pistas: ['corre', 'huevo', 'pluma'] },
  { a: 'Autillo', b: 'Mochuelo', pistas: ['noche', 'canto', 'pequeño'] },
  { a: 'Arrendajo', b: 'Rabilargo', pistas: ['azul', 'bosque', 'chillido'] },
  { a: 'Mirlo', b: 'Estornino', pistas: ['negro', 'jardín', 'bandada'] },
  { a: 'Carbonero', b: 'Herrerillo', pistas: ['comedero', 'pequeño', 'rama'] },
  { a: 'Cárabo', b: 'Búho real', pistas: ['noche', 'bosque', 'ulula'] },
  { a: 'Cocodrilo', b: 'Caimán', pistas: ['río', 'dientes', 'acecha'] },
  { a: 'Tortuga', b: 'Galápago', pistas: ['caparazón', 'lento', 'playa'] },
  { a: 'Rana', b: 'Sapo', pistas: ['charco', 'croa', 'salta'] },
  { a: 'Salamandra', b: 'Tritón', pistas: ['húmedo', 'cola', 'manchas'] },
  { a: 'Iguana', b: 'Camaleón', pistas: ['color', 'rama', 'sol'] },
  { a: 'Lagartija', b: 'Salamanquesa', pistas: ['pared', 'sol', 'cola'] },
  { a: 'Cobra', b: 'Víbora', pistas: ['silba', 'picadura', 'miedo'] },
  { a: 'Culebra', b: 'Pitón', pistas: ['enrolla', 'larga', 'bosque'] },
  { a: 'Boa', b: 'Anaconda', pistas: ['aprieta', 'selva', 'enorme'] },
  { a: 'Araña', b: 'Tarántula', pistas: ['tela', 'patas', 'miedo'] },
  { a: 'Escorpión', b: 'Ciempiés', pistas: ['pinza', 'pica', 'desierto'] },
  { a: 'Sardina', b: 'Anchoa', pistas: ['lata', 'salada', 'tapa'] },
  { a: 'Atún', b: 'Salmón', pistas: ['lata', 'rosa', 'fresco'] },
  { a: 'Trucha', b: 'Lubina', pistas: ['anzuelo', 'filete', 'río'] },
  { a: 'Bacalao', b: 'Merluza', pistas: ['rebozado', 'viernes', 'lomo'] },
  { a: 'Pez espada', b: 'Marlín', pistas: ['pico', 'mar', 'pesca'] },
  { a: 'Raya', b: 'Mantarraya', pistas: ['plana', 'mar', 'picotazo'] },
  { a: 'Anguila', b: 'Lamprea', pistas: ['resbala', 'río', 'larga'] },
  { a: 'Caballito de mar', b: 'Pez payaso', pistas: ['acuario', 'raro', 'dibujos'] },
  { a: 'Carpa', b: 'Barbo', pistas: ['estanque', 'río', 'bigote'] },
  { a: 'Besugo', b: 'Dorada', pistas: ['horno', 'navidad', 'escama'] },
  { a: 'Sepia', b: 'Jibia', pistas: ['tinta', 'arroz', 'mar'] },
  { a: 'Mejillón', b: 'Ostra', pistas: ['concha', 'vapor', 'perla'] },
  { a: 'Almeja', b: 'Berberecho', pistas: ['arena', 'paella', 'concha'] },
  { a: 'Cangrejo', b: 'Langosta', pistas: ['pinzas', 'muda', 'marisco'] },
  { a: 'Gamba', b: 'Langostino', pistas: ['plancha', 'ajillo', 'caro'] },
  { a: 'Nécora', b: 'Centollo', pistas: ['marisco', 'navidad', 'gallego'] },
  { a: 'Medusa', b: 'Anémona', pistas: ['picadura', 'playa', 'agua'] },
  { a: 'Caracol', b: 'Babosa', pistas: ['baba', 'lluvia', 'lento'] },
  { a: 'Lombriz', b: 'Gusano', pistas: ['tierra', 'húmedo', 'manzana'] },
  { a: 'Mosca', b: 'Mosquito', pistas: ['verano', 'zumbido', 'pesada'] },
  { a: 'Hormiga', b: 'Termita', pistas: ['fila', 'picnic', 'trabajo'] },
  { a: 'Mariposa', b: 'Polilla', pistas: ['capullo', 'color', 'armario'] },
  { a: 'Mariquita', b: 'Escarabajo', pistas: ['lunares', 'jardín', 'suerte'] },
  { a: 'Grillo', b: 'Cigarra', pistas: ['verano', 'ruido', 'salto'] },
  { a: 'Luciérnaga', b: 'Libélula', pistas: ['luz', 'verano', 'estanque'] },
  { a: 'Pulga', b: 'Garrapata', pistas: ['pica', 'rasca', 'pequeña'] },
  { a: 'Abejorro', b: 'Moscardón', pistas: ['peludo', 'zumbido', 'flores'] },
  { a: 'Mantis', b: 'Saltamontes', pistas: ['verde', 'salto', 'jardín'] },
  { a: 'Cucaracha', b: 'Tijereta', pistas: ['cocina', 'noche', 'asco'] },
  { a: 'Chinche', b: 'Piojo', pistas: ['pica', 'cama', 'asco'] },
  { a: 'Oruga', b: 'Crisálida', pistas: ['hoja', 'blanda', 'pata'] },
  { a: 'Erizo de mar', b: 'Estrella de mar', pistas: ['pinchos', 'fondo', 'playa'] },
  { a: 'Percebe', b: 'Lapa', pistas: ['roca', 'mar', 'pega'] },
  { a: 'Pez globo', b: 'Pez león', pistas: ['acuario', 'veneno', 'raro'] },
];

export const ANIMALES: Tema = {
  id: 'animales',
  nombre: 'Animales',
  pinta: 'Del gato de tu vecina al calamar gigante',
  terminos,
};
