import type { Tema, Termino } from './tipos';

/** Parejas de objetos de casa que se parecen lo justo. */
const terminos: readonly Termino[] = [
  { a: 'Nevera', b: 'Congelador', pistas: ['imanes', 'abrir', 'zumbido'] },
  { a: 'Sofá', b: 'Sillón', pistas: ['siesta', 'mando', 'migas'] },
  { a: 'Lavadora', b: 'Lavavajillas', pistas: ['calcetín', 'centrifugado', 'vecina'] },
  { a: 'Escoba', b: 'Fregona', pistas: ['esquina', 'polvo', 'domingo'] },
  { a: 'Cajón', b: 'Armario', pistas: ['todo', 'cables', 'no cierra'] },
  { a: 'Espejo', b: 'Ventana', pistas: ['baño', 'mañana', 'vaho'] },
  { a: 'Persiana', b: 'Cortina', pistas: ['ruido', 'cuerda', 'atascada'] },
  { a: 'Microondas', b: 'Horno', pistas: ['pitido', 'minuto', 'girar'] },
  { a: 'Manta', b: 'Edredón', pistas: ['invierno', 'sofá', 'pelusa'] },
  { a: 'Enchufe', b: 'Regleta', pistas: ['detrás', 'pocos', 'pisar'] },
  { a: 'Felpudo', b: 'Alfombra', pistas: ['entrada', 'llave', 'pisar'] },
  { a: 'Fiambrera', b: 'Termo', pistas: ['tapa', 'nunca', 'trabajo'] },
  { a: 'Cama', b: 'Litera', pistas: ['sábanas', 'siesta', 'almohada'] },
  { a: 'Colchón', b: 'Somier', pistas: ['muelles', 'espalda', 'funda'] },
  { a: 'Almohada', b: 'Cojín', pistas: ['cama', 'baba', 'funda'] },
  { a: 'Sábana', b: 'Funda', pistas: ['cama', 'cambiar', 'doblar'] },
  { a: 'Mesilla', b: 'Cómoda', pistas: ['despertador', 'cajón', 'lámpara'] },
  { a: 'Lámpara', b: 'Flexo', pistas: ['bombilla', 'noche', 'interruptor'] },
  { a: 'Bombilla', b: 'Vela', pistas: ['luz', 'fundida', 'rosca'] },
  { a: 'Interruptor', b: 'Timbre', pistas: ['pared', 'palanca', 'apagón'] },
  { a: 'Radiador', b: 'Estufa', pistas: ['invierno', 'seco', 'calor'] },
  { a: 'Aire acondicionado', b: 'Ventilador', pistas: ['verano', 'ruido', 'mando'] },
  { a: 'Calefacción', b: 'Caldera', pistas: ['factura', 'invierno', 'calor'] },
  { a: 'Grifo', b: 'Ducha', pistas: ['gotea', 'agua', 'arandela'] },
  { a: 'Bañera', b: 'Plato de ducha', pistas: ['baño', 'jabón', 'resbala'] },
  { a: 'Lavabo', b: 'Bidé', pistas: ['baño', 'grifo', 'encimera'] },
  { a: 'Váter', b: 'Cisterna', pistas: ['baño', 'tirar', 'atasco'] },
  { a: 'Papel higiénico', b: 'Servilleta', pistas: ['rollo', 'acaba', 'baño'] },
  { a: 'Toalla', b: 'Albornoz', pistas: ['húmeda', 'baño', 'gancho'] },
  { a: 'Esponja', b: 'Estropajo', pistas: ['plato', 'fregar', 'verde'] },
  { a: 'Jabón', b: 'Gel', pistas: ['baño', 'resbala', 'olor'] },
  { a: 'Champú', b: 'Acondicionador', pistas: ['ducha', 'tapón', 'ojo'] },
  { a: 'Pasta de dientes', b: 'Enjuague', pistas: ['cepillo', 'baño', 'menta'] },
  { a: 'Cepillo', b: 'Peine', pistas: ['pelo', 'baño', 'nudos'] },
  { a: 'Secador', b: 'Plancha de pelo', pistas: ['baño', 'cable', 'ruido'] },
  { a: 'Máquina de afeitar', b: 'Cuchilla', pistas: ['baño', 'espuma', 'corte'] },
  { a: 'Cubo', b: 'Papelera', pistas: ['basura', 'bolsa', 'cocina'] },
  { a: 'Basura', b: 'Reciclaje', pistas: ['bolsa', 'olor', 'bajar'] },
  { a: 'Fregadero', b: 'Pila', pistas: ['platos', 'grifo', 'tapón'] },
  { a: 'Encimera', b: 'Isla', pistas: ['cocina', 'migas', 'cortar'] },
  { a: 'Fogón', b: 'Vitrocerámica', pistas: ['cazuela', 'fuego', 'quemar'] },
  { a: 'Campana', b: 'Extractor', pistas: ['humo', 'ruido', 'grasa'] },
  { a: 'Tostadora', b: 'Sandwichera', pistas: ['desayuno', 'palanca', 'quemado'] },
  { a: 'Cafetera', b: 'Tetera', pistas: ['mañana', 'pava', 'gotea'] },
  { a: 'Batidora', b: 'Picadora', pistas: ['ruido', 'cocina', 'tapa'] },
  { a: 'Freidora', b: 'Airfryer', pistas: ['patatas', 'olor', 'crujiente'] },
  { a: 'Olla', b: 'Cacerola', pistas: ['tapa', 'fuego', 'hervor'] },
  { a: 'Sartén', b: 'Wok', pistas: ['aceite', 'mango', 'huevo'] },
  { a: 'Olla a presión', b: 'Olla exprés', pistas: ['vapor', 'pito', 'rápido'] },
  { a: 'Cuchara', b: 'Tenedor', pistas: ['cajón', 'mesa', 'caer'] },
  { a: 'Cuchillo', b: 'Pelador', pistas: ['corte', 'tabla', 'afilado'] },
  { a: 'Cazuela', b: 'Fuente', pistas: ['horno', 'barro', 'domingo'] },
  { a: 'Bandeja', b: 'Plato', pistas: ['servir', 'café', 'llevar'] },
  { a: 'Vaso', b: 'Copa', pistas: ['agua', 'cristal', 'brindis'] },
  { a: 'Taza', b: 'Tazón', pistas: ['desayuno', 'asa', 'posos'] },
  { a: 'Cuenco', b: 'Bol', pistas: ['sopa', 'cereal', 'hondo'] },
  { a: 'Jarra', b: 'Botella', pistas: ['agua', 'nevera', 'tapón'] },
  { a: 'Sacacorchos', b: 'Abrebotellas', pistas: ['vino', 'cajón', 'invitado'] },
  { a: 'Colador', b: 'Escurridor', pistas: ['pasta', 'fregadero', 'agujeros'] },
  { a: 'Rallador', b: 'Mandolina', pistas: ['queso', 'dedo', 'cajón'] },
  { a: 'Tabla de cortar', b: 'Tabla de quesos', pistas: ['madera', 'cocina', 'ralla'] },
  { a: 'Salero', b: 'Pimentero', pistas: ['mesa', 'agujeritos', 'tapar'] },
  { a: 'Mantel', b: 'Individual', pistas: ['mesa', 'mancha', 'domingo'] },
  { a: 'Bayeta', b: 'Trapo', pistas: ['fregar', 'fregadero', 'húmedo'] },
  { a: 'Agarrador', b: 'Manopla', pistas: ['horno', 'quema', 'cajón'] },
  { a: 'Delantal', b: 'Gorro de cocina', pistas: ['cocina', 'bolsillo', 'mancha'] },
  { a: 'Reloj', b: 'Despertador', pistas: ['pila', 'mesa', 'tarde'] },
  { a: 'Calendario', b: 'Agenda', pistas: ['pared', 'mes', 'recado'] },
  { a: 'Cuadro', b: 'Póster', pistas: ['clavo', 'pared', 'torcido'] },
  { a: 'Estantería', b: 'Librería', pistas: ['polvo', 'libros', 'ikea'] },
  { a: 'Perchero', b: 'Colgador', pistas: ['abrigo', 'entrada', 'ganchos'] },
  { a: 'Percha', b: 'Gancho', pistas: ['armario', 'ropa', 'cae'] },
  { a: 'Cesto', b: 'Capazo', pistas: ['ropa sucia', 'baño', 'olor'] },
  { a: 'Tendedero', b: 'Secadora', pistas: ['ropa', 'pinzas', 'patio'] },
  { a: 'Plancha', b: 'Tabla de planchar', pistas: ['vapor', 'camisa', 'domingo'] },
  { a: 'Aguja', b: 'Alfiler', pistas: ['hilo', 'dedal', 'botón'] },
  { a: 'Botón', b: 'Cremallera', pistas: ['camisa', 'se cae', 'cajón'] },
  { a: 'Mando', b: 'Televisor', pistas: ['sofá', 'pila', 'entre'] },
  { a: 'Pantalla', b: 'Monitor', pistas: ['sofá', 'apagada', 'brillo'] },
  { a: 'Altavoz', b: 'Barra de sonido', pistas: ['bluetooth', 'volumen', 'rincón'] },
  { a: 'Router', b: 'Módem', pistas: ['luz', 'armario', 'reiniciar'] },
  { a: 'Cargador', b: 'Cable', pistas: ['busca', 'sofá', 'único'] },
  { a: 'Pila alcalina', b: 'Batería', pistas: ['mando', 'acaba', 'cajón'] },
  { a: 'Linterna', b: 'Farolillo', pistas: ['apagón', 'cajón', 'botón'] },
  { a: 'Mechero', b: 'Encendedor', pistas: ['cajón', 'gas', 'cocina'] },
  { a: 'Cerillas', b: 'Fósforos', pistas: ['cajón', 'fuego', 'rascar'] },
  { a: 'Extintor', b: 'Detector', pistas: ['rincón', 'polvo', 'alarma'] },
  { a: 'Alarma', b: 'Portero', pistas: ['pitido', 'llave', 'vecino'] },
  { a: 'Llave', b: 'Cerrojo', pistas: ['puerta', 'busca', 'copia'] },
  { a: 'Pomo', b: 'Picaporte', pistas: ['puerta', 'gira', 'suelta'] },
  { a: 'Pestillo', b: 'Cadena', pistas: ['puerta', 'noche', 'seguro'] },
  { a: 'Cerradura', b: 'Candado', pistas: ['llave', 'puerta', 'atasco'] },
  { a: 'Escalera', b: 'Taburete', pistas: ['alto', 'armario', 'tambalea'] },
  { a: 'Mesa', b: 'Escritorio', pistas: ['sillas', 'migas', 'raya'] },
  { a: 'Silla', b: 'Mecedora', pistas: ['mesa', 'respaldo', 'cruje'] },
  { a: 'Banqueta', b: 'Reposapiés', pistas: ['bajo', 'cocina', 'sienta'] },
  { a: 'Zapatero', b: 'Revistero', pistas: ['pasillo', 'polvo', 'lleno'] },
  { a: 'Paraguas', b: 'Chubasquero', pistas: ['entrada', 'mojado', 'olvido'] },
  { a: 'Lejía', b: 'Amoníaco', pistas: ['olor', 'baño', 'quemar'] },
  { a: 'Detergente', b: 'Suavizante', pistas: ['tapón', 'olor', 'dosis'] },
  { a: 'Ambientador', b: 'Incienso', pistas: ['baño', 'olor', 'tapón'] },
  { a: 'Planta', b: 'Maceta', pistas: ['riego', 'olvido', 'alféizar'] },
  { a: 'Jarrón', b: 'Florero', pistas: ['flores', 'agua', 'polvo'] },
  { a: 'Imán', b: 'Chincheta', pistas: ['nevera', 'recado', 'cae'] },
  { a: 'Tijeras', b: 'Cúter', pistas: ['cajón', 'punta', 'cinta'] },
  { a: 'Cinta', b: 'Celo', pistas: ['pegar', 'rollo', 'cajón'] },
  { a: 'Pegamento', b: 'Silicona', pistas: ['tapa', 'pega', 'seco'] },
  { a: 'Destornillador', b: 'Llave inglesa', pistas: ['cajón', 'tuerca', 'gira'] },
  { a: 'Martillo', b: 'Clavo', pistas: ['pared', 'dedo', 'cajón'] },
  { a: 'Taladro', b: 'Atornillador', pistas: ['ruido', 'vecino', 'broca'] },
  { a: 'Recogedor', b: 'Pala', pistas: ['polvo', 'rincón', 'junto'] },
  { a: 'Aspiradora', b: 'Robot', pistas: ['ruido', 'pelo', 'cable'] },
  { a: 'Plumero', b: 'Mocho', pistas: ['polvo', 'alto', 'palo'] },
  { a: 'Vitrina', b: 'Aparador', pistas: ['vajilla', 'polvo', 'cristal'] },
  { a: 'Mesa de centro', b: 'Mesita', pistas: ['sofá', 'mando', 'rincón'] },
  { a: 'Plafón', b: 'Foco', pistas: ['techo', 'luz', 'cambiar'] },
  { a: 'Ladrón', b: 'Alargador', pistas: ['enchufes', 'detrás', 'corto'] },
  { a: 'Fusible', b: 'Diferencial', pistas: ['salta', 'cuadro', 'apagón'] },
  { a: 'Calentador', b: 'Acumulador', pistas: ['agua', 'factura', 'baño'] },
  { a: 'Bote', b: 'Tarro', pistas: ['tapa', 'despensa', 'etiqueta'] },
  { a: 'Tupper', b: 'Recipiente', pistas: ['tapa', 'nevera', 'sobras'] },
  { a: 'Film', b: 'Papel de aluminio', pistas: ['envolver', 'cajón', 'pega'] },
  { a: 'Papel de horno', b: 'Papel vegetal', pistas: ['bandeja', 'pegar', 'horno'] },
  { a: 'Cubitera', b: 'Molde', pistas: ['hielo', 'nevera', 'goma'] },
  { a: 'Balanza', b: 'Medidor', pistas: ['gramos', 'cocina', 'dieta'] },
  { a: 'Termómetro', b: 'Termostato', pistas: ['grados', 'número', 'pared'] },
  { a: 'Botiquín', b: 'Tiritas', pistas: ['baño', 'caducado', 'corte'] },
  { a: 'Humidificador', b: 'Deshumidificador', pistas: ['ruido', 'invierno', 'agua'] },
  { a: 'Costurero', b: 'Dedal', pistas: ['hilo', 'botón', 'caja'] },
  { a: 'Hilo', b: 'Ovillo', pistas: ['coser', 'enreda', 'color'] },
  { a: 'Palangana', b: 'Cubo de fregar', pistas: ['agua', 'suelo', 'trapo'] },
  { a: 'Fregasuelos', b: 'Quitagrasas', pistas: ['olor', 'suelo', 'botella'] },
  { a: 'Estor', b: 'Visillo', pistas: ['ventana', 'luz', 'polvo'] },
  { a: 'Mosquitera', b: 'Toldo', pistas: ['verano', 'ventana', 'bichos'] },
  { a: 'Sombrilla', b: 'Parasol', pistas: ['terraza', 'sol', 'viento'] },
  { a: 'Regadera', b: 'Manguera', pistas: ['agua', 'plantas', 'patio'] },
  { a: 'Caja', b: 'Baúl', pistas: ['trastero', 'tapado', 'cosas'] },
  { a: 'Nórdico', b: 'Colcha', pistas: ['cama', 'invierno', 'funda'] },
  { a: 'Plaid', b: 'Cubrecama', pistas: ['sofá', 'siesta', 'pelusa'] },
  { a: 'Moqueta', b: 'Alfombrilla', pistas: ['suelo', 'pelo', 'pisar'] },
  { a: 'Toallero', b: 'Portarrollos', pistas: ['baño', 'húmedo', 'cae'] },
  { a: 'Mampara', b: 'Cortina de ducha', pistas: ['baño', 'gotas', 'moho'] },
  { a: 'Buzón', b: 'Taquilla', pistas: ['llave', 'cartas', 'abajo'] },
  { a: 'Pinzas', b: 'Ganchos de ropa', pistas: ['tendedero', 'caen', 'cesta'] },
  { a: 'Puff', b: 'Hamaca', pistas: ['siesta', 'salón', 'hundirse'] },
  { a: 'Neverita', b: 'Isotérmica', pistas: ['playa', 'hielo', 'tapa'] },
  { a: 'Bidón', b: 'Garrafa', pistas: ['agua', 'tapón', 'peso'] },
  { a: 'Cajonera', b: 'Tocador', pistas: ['ropa', 'espejo', 'cajones'] },
  { a: 'Cuadro eléctrico', b: 'Contador', pistas: ['caja', 'luz', 'abajo'] },
  { a: 'Videoportero', b: 'Mirilla', pistas: ['puerta', 'quién', 'timbre'] },
];

export const CASA: Tema = {
  id: 'casa',
  nombre: 'Cosas de casa',
  pinta: 'Objetos que todo el mundo tiene y nadie mira',
  terminos,
};
