import type { Tema, Termino } from './tipos';

const terminos: readonly Termino[] = [
  { a: 'Titanic', b: 'Poseidón', pistas: ['barco', 'tabla', 'frío'] },
  { a: 'Matrix', b: 'Origen', pistas: ['pastilla', 'gafas', 'despertar'] },
  { a: 'Star Wars', b: 'Star Trek', pistas: ['espada', 'padre', 'galaxia'] },
  { a: 'Terror', b: 'Suspense', pistas: ['cojín', 'noche', 'grito'] },
  { a: 'Documental', b: 'Reportaje', pistas: ['siesta', 'narrador', 'real'] },
  { a: 'Palomitas', b: 'Nachos', pistas: ['ruido', 'cubo', 'sal'] },
  { a: 'Tráiler', b: 'Cartel', pistas: ['antes', 'engaña', 'minuto'] },
  { a: 'Secuela', b: 'Precuela', pistas: ['peor', 'otra vez', 'dinero'] },
  { a: 'Doblaje', b: 'Subtítulos', pistas: ['discusión', 'voz', 'España'] },
  { a: 'Maratón', b: 'Estreno', pistas: ['sofá', 'noche', 'siguiente'] },
  { a: 'Villano', b: 'Antihéroe', pistas: ['plan', 'capa', 'monólogo'] },
  { a: 'Zombi', b: 'Vampiro', pistas: ['lento', 'grupo', 'apocalipsis'] },
  { a: 'El Padrino', b: 'Scarface', pistas: ['familia', 'respeto', 'trono'] },
  { a: 'Jurassic Park', b: 'Jumanji', pistas: ['isla', 'corre', 'cerca'] },
  { a: 'Harry Potter', b: 'El Señor de los Anillos', pistas: ['magia', 'mapa', 'tren'] },
  { a: 'Avatar', b: 'Dune', pistas: ['tribu', 'arena', 'planeta'] },
  { a: 'Frozen', b: 'Encanto', pistas: ['hermana', 'canción', 'casa'] },
  { a: 'Toy Story', b: 'Monstruos S.A.', pistas: ['infantil', 'fábrica', 'armario'] },
  { a: 'El Rey León', b: 'Madagascar', pistas: ['sabana', 'huida', 'canto'] },
  { a: 'Gladiator', b: '300', pistas: ['arena', 'polvo', 'Roma'] },
  { a: 'Interstellar', b: 'Gravity', pistas: ['espacio', 'hija', 'tiempo'] },
  { a: 'Batman', b: 'Superman', pistas: ['ciudad', 'cueva', 'periódico'] },
  { a: 'Spiderman', b: 'Iron Man', pistas: ['traje', 'tío', 'rascacielos'] },
  { a: 'Los Vengadores', b: 'Liga de la Justicia', pistas: ['equipo', 'final', 'muchos'] },
  { a: 'Piratas del Caribe', b: 'Indiana Jones', pistas: ['mapa', 'sombrero', 'museo'] },
  { a: 'Fast & Furious', b: 'Mad Max', pistas: ['coche', 'desierto', 'familia'] },
  { a: 'Ocean\'s Eleven', b: 'La casa de papel', pistas: ['máscara', 'equipo', 'red'] },
  { a: 'Kill Bill', b: 'John Wick', pistas: ['venganza', 'lista', 'traje'] },
  { a: 'Pulp Fiction', b: 'Reservoir Dogs', pistas: ['maletín', 'baile', 'hamburguesa'] },
  { a: 'El silencio de los corderos', b: 'Seven', pistas: ['sótano', 'lista', 'miedo'] },
  { a: 'Psicosis', b: 'El resplandor', pistas: ['hotel', 'ducha', 'hacha'] },
  { a: 'Scream', b: 'Halloween', pistas: ['máscara', 'teléfono', 'fiesta'] },
  { a: 'Alien', b: 'Predator', pistas: ['nave', 'ácido', 'caza'] },
  { a: 'Terminator', b: 'RoboCop', pistas: ['metal', 'futuro', 'policía'] },
  { a: 'Blade Runner', b: 'Minority Report', pistas: ['lluvia', 'ojos', 'futuro'] },
  { a: 'El club de la lucha', b: 'Taxi Driver', pistas: ['jabón', 'insomnio', 'sótano'] },
  { a: 'Forrest Gump', b: 'Rain Man', pistas: ['banco', 'caja', 'correr'] },
  { a: 'Cadena perpetua', b: 'El fugitivo', pistas: ['muro', 'amigo', 'años'] },
  { a: 'Amélie', b: 'Medianoche en París', pistas: ['París', 'foto', 'rojo'] },
  { a: 'Cinema Paradiso', b: 'The Artist', pistas: ['rollo', 'silencio', 'pueblo'] },
  { a: 'El viaje de Chihiro', b: 'Mi vecino Totoro', pistas: ['tren', 'baño', 'bosque'] },
  { a: 'Parásitos', b: 'El hoyo', pistas: ['escaleras', 'olor', 'abajo'] },
  { a: 'Whiplash', b: 'El cisne negro', pistas: ['profesor', 'sangre', 'escenario'] },
  { a: 'Oppenheimer', b: 'Chernobyl', pistas: ['humo', 'culpa', 'sala'] },
  { a: 'Barbie', b: 'La Sirenita', pistas: ['rosa', 'muñeca', 'canción'] },
  { a: 'La La Land', b: 'Cantando bajo la lluvia', pistas: ['baile', 'farola', 'Hollywood'] },
  { a: 'El laberinto del fauno', b: 'El orfanato', pistas: ['niña', 'guerra', 'rojo'] },
  { a: 'Tesis', b: 'Abre los ojos', pistas: ['cámara', 'campus', 'cinta'] },
  { a: 'Todo sobre mi madre', b: 'Volver', pistas: ['madre', 'pueblo', 'pelo'] },
  { a: 'Ocho apellidos vascos', b: 'Ocho apellidos catalanes', pistas: ['boda', 'acento', 'pueblo'] },
  { a: 'Torrente', b: 'Mortadelo y Filemón', pistas: ['España', 'chiste', 'gabardina'] },
  { a: 'Relatos salvajes', b: 'La isla mínima', pistas: ['pueblo', 'calor', 'rabia'] },
  { a: 'Celda 211', b: 'El Niño', pistas: ['patio', 'fuga', 'sur'] },
  { a: 'Campeones', b: 'Intocable', pistas: ['furgoneta', 'risa', 'equipo'] },
  { a: 'REC', b: 'Los otros', pistas: ['casa', 'cinta', 'sombra'] },
  { a: 'Mar adentro', b: 'También la lluvia', pistas: ['cama', 'juicio', 'Galicia'] },
  { a: 'Rocky', b: 'Creed', pistas: ['ring', 'huevos', 'entrenador'] },
  { a: 'Troya', b: 'Espartaco', pistas: ['caballo', 'arena', 'antiguo'] },
  { a: 'El gran hotel Budapest', b: 'Moonrise Kingdom', pistas: ['bigote', 'simétrico', 'pastel'] },
  { a: 'Coco', b: 'Soul', pistas: ['familia', 'color', 'otro lado'] },
  { a: 'Up', b: 'WALL-E', pistas: ['globos', 'viejo', 'silencio'] },
  { a: 'Del revés', b: 'Luca', pistas: ['cabeza', 'color', 'niño'] },
  { a: 'Shrek', b: 'Encantada', pistas: ['cuento', 'ogro', 'boda'] },
  { a: 'El conjuro', b: 'Poltergeist', pistas: ['casa', 'muñeca', 'ruidos'] },
  { a: 'Crepúsculo', b: 'True Blood', pistas: ['mordisco', 'pueblo', 'brillante'] },
  { a: 'Joker', b: 'El lobo de Wall Street', pistas: ['risa', 'locura', 'traje'] },
  { a: 'Pearl Harbor', b: 'Salvando al soldado Ryan', pistas: ['guerra', 'playa', 'carta'] },
  { a: 'Infiltrados', b: 'Heat', pistas: ['policía', 'ciudad', 'traición'] },
  { a: 'El irlandés', b: 'Uno de los nuestros', pistas: ['coche', 'años', 'familia'] },
  { a: 'Friends', b: 'The Big Bang Theory', pistas: ['café', 'piso', 'risa'] },
  { a: 'The Office', b: 'Cámara Café', pistas: ['cubículo', 'cámara', 'cringe'] },
  { a: 'Juego de Tronos', b: 'Vikingos', pistas: ['trono', 'invierno', 'traición'] },
  { a: 'Breaking Bad', b: 'Narcos', pistas: ['laboratorio', 'desierto', 'familia'] },
  { a: 'Stranger Things', b: 'Dark', pistas: ['sótano', 'luces', 'desaparece'] },
  { a: 'The Walking Dead', b: 'The Last of Us', pistas: ['carretera', 'mordisco', 'muro'] },
  { a: 'Black Mirror', b: 'Westworld', pistas: ['futuro', 'botón', 'inquieto'] },
  { a: 'Sherlock', b: 'True Detective', pistas: ['lupa', 'tren', 'compañero'] },
  { a: 'Élite', b: 'Física o Química', pistas: ['instituto', 'cotilleo', 'pasillo'] },
  { a: 'Aquí no hay quien viva', b: 'La que se avecina', pistas: ['patio', 'vecino', 'comunidad'] },
  { a: 'Cuéntame', b: 'Médico de familia', pistas: ['tele', 'abuelos', 'memoria'] },
  { a: 'Doctor Who', b: 'El Ministerio del Tiempo', pistas: ['puerta', 'época', 'corbata'] },
  { a: 'Bridgerton', b: 'Downton Abbey', pistas: ['baile', 'carta', 'época'] },
  { a: 'The Crown', b: 'Los Tudor', pistas: ['palacio', 'acento', 'corona'] },
  { a: 'Peaky Blinders', b: 'Gangs of New York', pistas: ['gorra', 'calle', 'familia'] },
  { a: 'Succession', b: 'Dallas', pistas: ['herencia', 'mesa', 'traición'] },
  { a: 'The Bear', b: 'Ratatouille', pistas: ['cocina', 'gritos', 'delantal'] },
  { a: 'Ted Lasso', b: 'Friday Night Lights', pistas: ['vestuario', 'charla', 'banquillo'] },
  { a: 'Squid Game', b: 'Los juegos del hambre', pistas: ['juego', 'número', 'sobrevivir'] },
  { a: 'Vis a vis', b: 'Orange is the New Black', pistas: ['patio', 'uniforme', 'fuga'] },
  { a: 'Las chicas del cable', b: 'Mad Men', pistas: ['falda', 'oficina', 'teléfono'] },
  { a: 'Velvet', b: 'Gran Hotel', pistas: ['hotel', 'traje', 'romance'] },
  { a: 'Águila Roja', b: 'Isabel', pistas: ['palacio', 'capa', 'España'] },
  { a: 'Los Simpson', b: 'Padre de familia', pistas: ['domingo', 'amarillo', 'sofá'] },
  { a: 'One Piece', b: 'Dragon Ball', pistas: ['isla', 'pelea', 'años'] },
  { a: 'Naruto', b: 'Bleach', pistas: ['cinta', 'pueblo', 'grito'] },
  { a: 'Oscar', b: 'Goya', pistas: ['estatua', 'alfombra', 'discurso'] },
  { a: 'Netflix', b: 'HBO', pistas: ['sofá', 'original', 'mes'] },
  { a: 'Taquilla', b: 'Streaming', pistas: ['fin de semana', 'cola', 'cifras'] },
  { a: 'Director', b: 'Guionista', pistas: ['silla', 'grita', 'crédito'] },
  { a: 'Actor', b: 'Doble', pistas: ['maquillaje', 'cachet', 'marca'] },
];

export const CINE: Tema = {
  id: 'cine',
  nombre: 'Cine y series',
  pinta: 'Spoilers no; pistas malas, todas las que quieras',
  terminos,
};
