import type { Tema, Termino } from './tipos';

/** Parejas de comida y bebida que se parecen lo justo. */
const terminos: readonly Termino[] = [
  { a: 'Pizza', b: 'Empanada', pistas: ['reparto', 'horno', 'porción'] },
  { a: 'Tortilla', b: 'Revuelto', pistas: ['huevo', 'debate', 'sartén'] },
  { a: 'Paella', b: 'Fideuá', pistas: ['domingo', 'socarrat', 'leña'] },
  { a: 'Café', b: 'Té', pistas: ['mañana', 'taza', 'amargo'] },
  { a: 'Cerveza', b: 'Sidra', pistas: ['terraza', 'espuma', 'fría'] },
  { a: 'Chocolate', b: 'Turrón', pistas: ['tableta', 'dulce', 'derrite'] },
  { a: 'Sushi', b: 'Ceviche', pistas: ['crudo', 'palillos', 'arroz'] },
  { a: 'Hamburguesa', b: 'Bocadillo', pistas: ['pan', 'manos', 'servilleta'] },
  { a: 'Helado', b: 'Granizado', pistas: ['verano', 'cucurucho', 'frío'] },
  { a: 'Jamón', b: 'Chorizo', pistas: ['navidad', 'loncha', 'caro'] },
  { a: 'Sopa', b: 'Caldo', pistas: ['cuchara', 'invierno', 'abuela'] },
  { a: 'Churros', b: 'Porras', pistas: ['domingo', 'aceite', 'mojar'] },
  { a: 'Croqueta', b: 'Buñuelo', pistas: ['frito', 'bocado', 'bar'] },
  { a: 'Bravas', b: 'Alioli', pistas: ['patata', 'picante', 'ración'] },
  { a: 'Calamares', b: 'Rabas', pistas: ['anilla', 'limón', 'ración'] },
  { a: 'Gilda', b: 'Banderilla', pistas: ['palillo', 'bar', 'picante'] },
  { a: 'Pincho', b: 'Montadito', pistas: ['barra', 'pequeño', 'vasco'] },
  { a: 'Tosta', b: 'Canapé', pistas: ['fiesta', 'picoteo', 'bocado'] },
  { a: 'Aceitunas', b: 'Pepinillos', pistas: ['bote', 'vermú', 'hueso'] },
  { a: 'Torreznos', b: 'Cortezas', pistas: ['crujiente', 'cerdo', 'bar'] },
  { a: 'Boquerones', b: 'Anchoas', pistas: ['vinagre', 'tapa', 'salados'] },
  { a: 'Mejillones', b: 'Almejas', pistas: ['vapor', 'vino', 'concha'] },
  { a: 'Gambas', b: 'Langostinos', pistas: ['ajillo', 'plancha', 'caro'] },
  { a: 'Pulpo', b: 'Sepia', pistas: ['gallego', 'tinta', 'plancha'] },
  { a: 'Padrón', b: 'Guindilla', pistas: ['pican', 'verde', 'ración'] },
  { a: 'Ensaladilla', b: 'Ensalada', pistas: ['mayonesa', 'fiesta', 'fría'] },
  { a: 'Gazpacho', b: 'Salmorejo', pistas: ['tomate', 'verano', 'frío'] },
  { a: 'Ajoblanco', b: 'Vichyssoise', pistas: ['vaso', 'verano', 'frío'] },
  { a: 'Cocido', b: 'Fabada', pistas: ['cuchara', 'invierno', 'plato'] },
  { a: 'Lentejas', b: 'Garbanzos', pistas: ['jueves', 'cuchara', 'abuela'] },
  { a: 'Callos', b: 'Oreja', pistas: ['casquería', 'plato', 'sábado'] },
  { a: 'Estofado', b: 'Guiso', pistas: ['cacerola', 'lento', 'cuchara'] },
  { a: 'Puchero', b: 'Olla', pistas: ['domingo', 'pueblo', 'plato'] },
  { a: 'Marmitako', b: 'Porrusalda', pistas: ['norte', 'cuchara', 'pescado'] },
  { a: 'Pisto', b: 'Escalivada', pistas: ['verdura', 'pimiento', 'pan'] },
  { a: 'Chuletón', b: 'Entrecot', pistas: ['parrilla', 'sangre', 'caro'] },
  { a: 'Filete', b: 'Escalope', pistas: ['plancha', 'empanado', 'ración'] },
  { a: 'Albóndigas', b: 'Kefta', pistas: ['salsa', 'carne', 'plato'] },
  { a: 'Lomo', b: 'Solomillo', pistas: ['plancha', 'salsa', 'tierno'] },
  { a: 'Costilla', b: 'Carrillera', pistas: ['horno', 'salsa', 'chupar'] },
  { a: 'Pollo asado', b: 'Pollo al ajillo', pistas: ['domingo', 'ajo', 'ración'] },
  { a: 'Cordero', b: 'Cabrito', pistas: ['horno', 'pascua', 'pata'] },
  { a: 'Cochinillo', b: 'Lechazo', pistas: ['segovia', 'crujiente', 'horno'] },
  { a: 'Morcilla', b: 'Butifarra', pistas: ['parrilla', 'sangre', 'tapa'] },
  { a: 'Chistorra', b: 'Longaniza', pistas: ['grasa', 'parrilla', 'navarra'] },
  { a: 'Salchichón', b: 'Fuet', pistas: ['loncha', 'picoteo', 'seco'] },
  { a: 'Cecina', b: 'Lomo embuchado', pistas: ['loncha', 'tabla', 'seco'] },
  { a: 'Bacon', b: 'Panceta', pistas: ['desayuno', 'crujiente', 'grasa'] },
  { a: 'Salchicha', b: 'Frankfurt', pistas: ['mostaza', 'parrilla', 'pan'] },
  { a: 'Perrito', b: 'Kebab', pistas: ['noche', 'salsa', 'rollo'] },
  { a: 'Tacos', b: 'Burrito', pistas: ['maíz', 'picante', 'manos'] },
  { a: 'Quesadilla', b: 'Nachos', pistas: ['queso', 'crujiente', 'dip'] },
  { a: 'Bacalao', b: 'Merluza', pistas: ['rebozado', 'potas', 'lomo'] },
  { a: 'Sardinas', b: 'Caballa', pistas: ['parrilla', 'lata', 'verano'] },
  { a: 'Atún', b: 'Bonito', pistas: ['lata', 'ensalada', 'norte'] },
  { a: 'Salmón', b: 'Trucha', pistas: ['rosa', 'horno', 'fresco'] },
  { a: 'Besugo', b: 'Dorada', pistas: ['horno', 'navidad', 'escama'] },
  { a: 'Rape', b: 'Lubina', pistas: ['horno', 'salsa', 'lomo'] },
  { a: 'Percebes', b: 'Nécoras', pistas: ['galicia', 'marisco', 'caros'] },
  { a: 'Centollo', b: 'Bogavante', pistas: ['navidad', 'marisco', 'rico'] },
  { a: 'Berberechos', b: 'Navajas', pistas: ['playa', 'limón', 'crudo'] },
  { a: 'Arroz negro', b: 'Arroz a banda', pistas: ['tinta', 'cazuela', 'arroz'] },
  { a: 'Risotto', b: 'Arroz cubano', pistas: ['cuchara', 'plato', 'cremoso'] },
  { a: 'Macarrones', b: 'Espaguetis', pistas: ['tomate', 'nido', 'queso'] },
  { a: 'Lasaña', b: 'Canelones', pistas: ['horno', 'bechamel', 'domingo'] },
  { a: 'Fideos', b: 'Tallarines', pistas: ['nido', 'chino', 'caldo'] },
  { a: 'Ñoquis', b: 'Ravioli', pistas: ['salsa', 'italia', 'relleno'] },
  { a: 'Cuscús', b: 'Quinoa', pistas: ['grano', 'sano', 'guarnición'] },
  { a: 'Migas', b: 'Gachas', pistas: ['sartén', 'pueblo', 'pastor'] },
  { a: 'Pan', b: 'Baguette', pistas: ['cesta', 'corteza', 'migas'] },
  { a: 'Mollete', b: 'Chapata', pistas: ['desayuno', 'tostada', 'aceite'] },
  { a: 'Bollo', b: 'Panecillo', pistas: ['merienda', 'mantequilla', 'bolsa'] },
  { a: 'Sandwich', b: 'Bikini', pistas: ['plancha', 'mixto', 'bar'] },
  { a: 'Empanadilla', b: 'Pastelito', pistas: ['horno', 'recado', 'pequeño'] },
  { a: 'Queso', b: 'Cuajada', pistas: ['oveja', 'cucharilla', 'postre'] },
  { a: 'Manchego', b: 'Idiazábal', pistas: ['cuña', 'curado', 'tabla'] },
  { a: 'Cabrales', b: 'Roquefort', pistas: ['azul', 'fuerte', 'pudre'] },
  { a: 'Tetilla', b: 'Mahón', pistas: ['suave', 'tabla', 'gallega'] },
  { a: 'Yogur', b: 'Kéfir', pistas: ['nevera', 'desayuno', 'cucharilla'] },
  { a: 'Mantequilla', b: 'Margarina', pistas: ['tostada', 'nevera', 'barra'] },
  { a: 'Natillas', b: 'Flan', pistas: ['huevo', 'postre', 'cucharilla'] },
  { a: 'Crema catalana', b: 'Tocino de cielo', pistas: ['quemada', 'yema', 'postre'] },
  { a: 'Arroz con leche', b: 'Sémola', pistas: ['canela', 'postre', 'cucharilla'] },
  { a: 'Tarta', b: 'Pastel', pistas: ['cumpleaños', 'nata', 'velas'] },
  { a: 'Brownie', b: 'Coulant', pistas: ['caliente', 'horno', 'chocolate'] },
  { a: 'Galleta', b: 'Bizcocho', pistas: ['merienda', 'bote', 'café'] },
  { a: 'Magdalena', b: 'Croissant', pistas: ['desayuno', 'sobre', 'mantequilla'] },
  { a: 'Ensaimada', b: 'Palmera', pistas: ['mallorca', 'azúcar', 'hojaldre'] },
  { a: 'Rosquilla', b: 'Donut', pistas: ['agujero', 'feria', 'azúcar'] },
  { a: 'Torrijas', b: 'Leche frita', pistas: ['semana santa', 'canela', 'frito'] },
  { a: 'Roscón', b: 'Panettone', pistas: ['reyes', 'haba', 'naranja'] },
  { a: 'Polvorón', b: 'Mantecado', pistas: ['navidad', 'migas', 'almendra'] },
  { a: 'Mazapán', b: 'Yema', pistas: ['toledo', 'navidad', 'almendra'] },
  { a: 'Peladillas', b: 'Garrapiñadas', pistas: ['boda', 'almendra', 'crujiente'] },
  { a: 'Sorbete', b: 'Polo', pistas: ['verano', 'palo', 'frío'] },
  { a: 'Batido', b: 'Smoothie', pistas: ['vaso', 'paja', 'fruta'] },
  { a: 'Horchata', b: 'Leche merengada', pistas: ['vaso', 'verano', 'chufa'] },
  { a: 'Sangría', b: 'Tinto de verano', pistas: ['jarra', 'hielo', 'terraza'] },
  { a: 'Cava', b: 'Champagne', pistas: ['burbujas', 'brindis', 'año'] },
  { a: 'Vino', b: 'Vermú', pistas: ['copa', 'domingo', 'tapa'] },
  { a: 'Clara', b: 'Radler', pistas: ['limón', 'terraza', 'ligera'] },
  { a: 'Cubata', b: 'Gin-tonic', pistas: ['copa', 'hielo', 'fiesta'] },
  { a: 'Chupito', b: 'Carajillo', pistas: ['barra', 'después', 'quemar'] },
  { a: 'Whisky', b: 'Ron', pistas: ['vaso', 'hielo', 'noche'] },
  { a: 'Orujo', b: 'Pacharán', pistas: ['digestivo', 'norte', 'anís'] },
  { a: 'Mosto', b: 'Zumo', pistas: ['niño', 'uva', 'vaso'] },
  { a: 'Cola', b: 'Fanta', pistas: ['burbujas', 'hielo', 'infantil'] },
  { a: 'Agua', b: 'Casera', pistas: ['botella', 'mesa', 'grifo'] },
  { a: 'Leche', b: 'Colacao', pistas: ['vaso', 'desayuno', 'bigote'] },
  { a: 'Cortado', b: 'Manchado', pistas: ['taza', 'barra', 'pequeño'] },
  { a: 'Capuchino', b: 'Café con leche', pistas: ['espuma', 'taza', 'mañana'] },
  { a: 'Infusión', b: 'Manzanilla', pistas: ['sobre', 'después', 'abuela'] },
  { a: 'Aceite', b: 'Vinagre', pistas: ['aliño', 'botella', 'ensalada'] },
  { a: 'Mayonesa', b: 'Kétchup', pistas: ['bote', 'frito', 'dip'] },
  { a: 'Mostaza', b: 'Barbacoa', pistas: ['salsa', 'perrito', 'bote'] },
  { a: 'Ajo', b: 'Cebolla', pistas: ['sofrito', 'llora', 'olor'] },
  { a: 'Sal', b: 'Pimienta', pistas: ['mesa', 'toque', 'molinillo'] },
  { a: 'Azúcar', b: 'Sacarina', pistas: ['sobre', 'cucharilla', 'café'] },
  { a: 'Miel', b: 'Sirope', pistas: ['cuchara', 'tostada', 'dulce'] },
  { a: 'Mermelada', b: 'Compota', pistas: ['tostada', 'bote', 'desayuno'] },
  { a: 'Sobrasada', b: 'Paté', pistas: ['untar', 'mallorca', 'pan'] },
  { a: 'Tomate', b: 'Pimiento', pistas: ['ensalada', 'rojo', 'huerta'] },
  { a: 'Lechuga', b: 'Espinaca', pistas: ['hoja', 'verde', 'ensalada'] },
  { a: 'Patata', b: 'Boniato', pistas: ['frita', 'horno', 'guarnición'] },
  { a: 'Setas', b: 'Champiñones', pistas: ['plancha', 'bosque', 'ajo'] },
  { a: 'Calabacín', b: 'Berenjena', pistas: ['asado', 'horno', 'pisto'] },
  { a: 'Brócoli', b: 'Coliflor', pistas: ['verde', 'sano', 'vapor'] },
  { a: 'Zanahoria', b: 'Nabo', pistas: ['huerta', 'sopa', 'cruda'] },
  { a: 'Alcachofa', b: 'Espárrago', pistas: ['temporada', 'vinagreta', 'fibra'] },
  { a: 'Pipas', b: 'Palomitas', pistas: ['bolsa', 'cascar', 'cine'] },
  { a: 'Patatas fritas', b: 'Gusanitos', pistas: ['bolsa', 'crujiente', 'aperitivo'] },
  { a: 'Cacahuetes', b: 'Pistachos', pistas: ['cáscara', 'barra', 'salados'] },
  { a: 'Almendras', b: 'Avellanas', pistas: ['tostadas', 'bote', 'navidad'] },
  { a: 'Huevo frito', b: 'Huevo duro', pistas: ['yema', 'desayuno', 'cáscara'] },
  { a: 'Falafel', b: 'Hummus', pistas: ['garbanzo', 'pita', 'dip'] },
  { a: 'Guacamole', b: 'Tzatziki', pistas: ['dip', 'verde', 'pan'] },
  { a: 'Tapa', b: 'Ración', pistas: ['bar', 'compartir', 'pequeño'] },
  { a: 'Menú', b: 'Carta', pistas: ['mediodía', 'primero', 'elegir'] },
  { a: 'Crepe', b: 'Filloa', pistas: ['sartén', 'nata', 'fina'] },
  { a: 'Gofre', b: 'Barquillo', pistas: ['feria', 'nata', 'crujiente'] },
  { a: 'Gominola', b: 'Caramelo', pistas: ['bolsa', 'niño', 'pega'] },
  { a: 'Nube', b: 'Regaliz', pistas: ['chuche', 'color', 'bolsa'] },
  { a: 'Calzone', b: 'Focaccia', pistas: ['horno', 'italia', 'masa'] },
  { a: 'Fabes', b: 'Alubias', pistas: ['asturias', 'cuchara', 'pote'] },
  { a: 'Guisantes', b: 'Judías verdes', pistas: ['guarnición', 'verde', 'menú'] },
  { a: 'Aguacate', b: 'Pepino', pistas: ['ensalada', 'verde', 'fresco'] },
  { a: 'Nata', b: 'Crema', pistas: ['postre', 'montar', 'dulce'] },
  { a: 'Rebujito', b: 'Kalimotxo', pistas: ['fiesta', 'barato', 'jarra'] },
  { a: 'Agua con gas', b: 'Tónica', pistas: ['burbujas', 'hielo', 'rodaja'] },
  { a: 'Menestra', b: 'Samfaina', pistas: ['verdura', 'guarnición', 'temporada'] },
];

export const COMIDA: Tema = {
  id: 'comida',
  nombre: 'Comida y bebida',
  pinta: 'Discutir de tortilla sin decir «tortilla»',
  terminos,
};
