import type { Tema, Termino } from './tipos';

const terminos: readonly Termino[] = [
  { a: 'Fútbol', b: 'Fútbol sala', pistas: ['domingo', 'árbitro', 'once'] },
  { a: 'Baloncesto', b: 'Balonmano', pistas: ['canasta', 'altos', 'bote'] },
  { a: 'Tenis', b: 'Pádel', pistas: ['raqueta', 'red', 'ceros'] },
  { a: 'Natación', b: 'Waterpolo', pistas: ['gorro', 'calle', 'cloro'] },
  { a: 'Ciclismo', b: 'Motociclismo', pistas: ['puerto', 'julio', 'maillot'] },
  { a: 'Maratón', b: 'Media maratón', pistas: ['dorsal', 'rodilla', 'muro'] },
  { a: 'Ajedrez', b: 'Damas', pistas: ['reloj', 'callado', 'apertura'] },
  { a: 'Boxeo', b: 'Judo', pistas: ['asalto', 'guantes', 'esquina'] },
  { a: 'Esquí', b: 'Snowboard', pistas: ['cola', 'caro', 'yeso'] },
  { a: 'Golf', b: 'Minigolf', pistas: ['césped', 'carrito', 'silencio'] },
  { a: 'Gimnasio', b: 'Crossfit', pistas: ['enero', 'cuota', 'espejo'] },
  { a: 'Petanca', b: 'Bolos', pistas: ['parque', 'jubilados', 'medir'] },
  { a: 'Atletismo', b: 'Marcha atlética', pistas: ['pista', 'tacos', 'crono'] },
  { a: '100 metros', b: '200 metros', pistas: ['tacos', 'recta', 'explosión'] },
  { a: '400 metros', b: '800 metros', pistas: ['calle', 'agónico', 'anillo'] },
  { a: '1500 metros', b: '5000 metros', pistas: ['ritmo', 'grupo', 'vueltas'] },
  { a: '10000 metros', b: 'Campo a través', pistas: ['barro', 'otoño', 'largo'] },
  { a: '110 vallas', b: '400 vallas', pistas: ['zancada', 'ritmo', 'listón'] },
  { a: '3000 obstáculos', b: 'Milla', pistas: ['agua', 'ritmo', 'pista'] },
  { a: 'Relevos', b: '4x400', pistas: ['testigo', 'pasillo', 'equipo'] },
  { a: 'Salto de altura', b: 'Salto de longitud', pistas: ['listón', 'arena', 'carrera'] },
  { a: 'Triple salto', b: 'Salto con pértiga', pistas: ['batida', 'colchoneta', 'vuelo'] },
  { a: 'Lanzamiento de peso', b: 'Lanzamiento de disco', pistas: ['giro', 'círculo', 'campo'] },
  { a: 'Jabalina', b: 'Martillo', pistas: ['giro', 'lejos', 'jaula'] },
  { a: 'Heptatlón', b: 'Decatlón', pistas: ['pruebas', 'dos días', 'cansancio'] },
  { a: 'Pentatlón', b: 'Combinada', pistas: ['varias', 'medalla', 'lío'] },
  { a: 'Trampolín', b: 'Palanca', pistas: ['splash', 'altura', 'nota'] },
  { a: 'Natación artística', b: 'Aguas abiertas', pistas: ['nariz', 'frío', 'coreografía'] },
  { a: 'Voleibol', b: 'Voleibol playa', pistas: ['saque', 'bloqueo', 'red'] },
  { a: 'Bádminton', b: 'Tenis de mesa', pistas: ['pluma', 'rápido', 'sala'] },
  { a: 'Rugby', b: 'Fútbol americano', pistas: ['ovalada', 'tacle', 'hueso'] },
  { a: 'Hockey hierba', b: 'Hockey hielo', pistas: ['stick', 'casco', 'portería'] },
  { a: 'Hockey patines', b: 'Patinaje en línea', pistas: ['ruedas', 'pista', 'caídas'] },
  { a: 'Béisbol', b: 'Sóftbol', pistas: ['bate', 'base', 'guante'] },
  { a: 'Críquet', b: 'Lacrosse', pistas: ['bate', 'largo', 'césped'] },
  { a: 'Squash', b: 'Frontenis', pistas: ['pared', 'sudor', 'gafas'] },
  { a: 'Pelota vasca', b: 'Cesta punta', pistas: ['pared', 'rápido', 'norte'] },
  { a: 'Frontón', b: 'Trinquete', pistas: ['pelota', 'eco', 'euskadi'] },
  { a: 'Pelota valenciana', b: 'Galotxa', pistas: ['guante', 'calle', 'pueblo'] },
  { a: 'Fútbol playa', b: 'Balonmano playa', pistas: ['arena', 'verano', 'torneo'] },
  { a: 'Ultimate', b: 'Frisbee', pistas: ['disco', 'parque', 'joven'] },
  { a: 'Billar', b: 'Snooker', pistas: ['taco', 'bola', 'silencio'] },
  { a: 'Billar americano', b: 'Carambola', pistas: ['mesa', 'bola', 'café'] },
  { a: 'Dardos', b: 'Bowling', pistas: ['diana', 'pub', 'ruido'] },
  { a: 'Halterofilia', b: 'Powerlifting', pistas: ['barra', 'kilos', 'grito'] },
  { a: 'Kickboxing', b: 'Muay thai', pistas: ['patada', 'saco', 'vendaje'] },
  { a: 'Karate', b: 'Taekwondo', pistas: ['kimono', 'cinturón', 'dojo'] },
  { a: 'Kung-fu', b: 'Aikido', pistas: ['película', 'maestro', 'equilibrio'] },
  { a: 'Jiu-jitsu', b: 'Sambo', pistas: ['tapiz', 'agarre', 'suelo'] },
  { a: 'Lucha libre', b: 'Lucha grecorromana', pistas: ['tapiz', 'caída', 'agarre'] },
  { a: 'MMA', b: 'Vale tudo', pistas: ['jaula', 'mixto', 'sangriento'] },
  { a: 'Sumo', b: 'Lucha canaria', pistas: ['empujar', 'ritual', 'círculo'] },
  { a: 'Lucha leonesa', b: 'Sokatira', pistas: ['corro', 'pueblo', 'fuerza'] },
  { a: 'Esgrima', b: 'Kendo', pistas: ['máscara', 'toque', 'sala'] },
  { a: 'Capoeira', b: 'Breaking', pistas: ['música', 'acrobacia', 'suelo'] },
  { a: 'Gimnasia artística', b: 'Gimnasia rítmica', pistas: ['suelo', 'nota', 'cinta'] },
  { a: 'Tumbling', b: 'Mini tramp', pistas: ['colchoneta', 'serie', 'rebote'] },
  { a: 'Yoga', b: 'Pilates', pistas: ['esterilla', 'calma', 'respirar'] },
  { a: 'Zumba', b: 'Aeróbic', pistas: ['música', 'grupo', 'sudor'] },
  { a: 'Spinning', b: 'Bicicleta estática', pistas: ['clase', 'pedales', 'sudor'] },
  { a: 'Calistenia', b: 'Culturismo', pistas: ['barras', 'parque', 'espejo'] },
  { a: 'Fitness', b: 'GAP', pistas: ['clase', 'repetición', 'monitora'] },
  { a: 'Triatlón', b: 'Duatlón', pistas: ['transición', 'neopreno', 'tres'] },
  { a: 'Karting', b: 'Fórmula 1', pistas: ['casco', 'curva', 'ruido'] },
  { a: 'Rally', b: 'Autocross', pistas: ['barro', 'copiloto', 'curva'] },
  { a: 'Motocross', b: 'Enduro', pistas: ['barro', 'salto', 'casco'] },
  { a: 'Trial', b: 'Supermoto', pistas: ['equilibrio', 'piedras', 'moto'] },
  { a: 'BMX', b: 'Bici de montaña', pistas: ['salto', 'tierra', 'casco'] },
  { a: 'Ciclocrós', b: 'Contrarreloj', pistas: ['barro', 'otoño', 'crono'] },
  { a: 'Automovilismo', b: 'Turismos', pistas: ['circuito', 'boxes', 'ruido'] },
  { a: 'Remo', b: 'Piragüismo', pistas: ['pala', 'río', 'espaldas'] },
  { a: 'Kayak', b: 'Canoa', pistas: ['río', 'chaleco', 'rápidos'] },
  { a: 'Vela', b: 'Catamarán', pistas: ['viento', 'boya', 'escora'] },
  { a: 'Windsurf', b: 'Kitesurf', pistas: ['tabla', 'racha', 'playa'] },
  { a: 'Surf', b: 'Bodyboard', pistas: ['ola', 'cera', 'playa'] },
  { a: 'Paddle surf', b: 'Esquí náutico', pistas: ['equilibrio', 'lago', 'cuerda'] },
  { a: 'Rafting', b: 'Barranquismo', pistas: ['río', 'chaleco', 'gritos'] },
  { a: 'Submarinismo', b: 'Apnea', pistas: ['botella', 'oídos', 'azul'] },
  { a: 'Snorkel', b: 'Pesca submarina', pistas: ['tubo', 'aletas', 'peces'] },
  { a: 'Escalada', b: 'Alpinismo', pistas: ['arnés', 'presa', 'miedo'] },
  { a: 'Senderismo', b: 'Trekking', pistas: ['mochila', 'camino', 'picnic'] },
  { a: 'Orientación', b: 'Raid', pistas: ['mapa', 'brújula', 'bosque'] },
  { a: 'Espeleología', b: 'Vía ferrata', pistas: ['casco', 'cuerda', 'oscuro'] },
  { a: 'Paracaidismo', b: 'Puenting', pistas: ['salto', 'miedo', 'foto'] },
  { a: 'Parapente', b: 'Ala delta', pistas: ['viento', 'precipicio', 'arnés'] },
  { a: 'Parkour', b: 'Freerunning', pistas: ['muro', 'salto', 'urbano'] },
  { a: 'Patinaje artístico', b: 'Danza sobre hielo', pistas: ['hielo', 'giros', 'música'] },
  { a: 'Bobsleigh', b: 'Skeleton', pistas: ['hielo', 'tubo', 'casco'] },
  { a: 'Luge', b: 'Monobob', pistas: ['hielo', 'tumbado', 'casco'] },
  { a: 'Biatlón', b: 'Esquí de fondo', pistas: ['disparo', 'nieve', 'agotado'] },
  { a: 'Salto de esquí', b: 'Combinada nórdica', pistas: ['rampa', 'vuelo', 'nieve'] },
  { a: 'Raquetas de nieve', b: 'Trineo', pistas: ['nieve', 'bosque', 'cuesta'] },
  { a: 'Curling', b: 'Hockey trineo', pistas: ['hielo', 'escoba', 'silencio'] },
  { a: 'Esquí de montaña', b: 'Heliesquí', pistas: ['nieve', 'pieles', 'cima'] },
  { a: 'Skate', b: 'Patinete', pistas: ['rampa', 'caídas', 'vídeo'] },
  { a: 'Longboard', b: 'Surfskate', pistas: ['cuesta', 'ruedas', 'equilibrio'] },
  { a: 'Hidrospeed', b: 'Wakeboard', pistas: ['agua', 'chaleco', 'barco'] },
  { a: 'Calva', b: 'Chito', pistas: ['palo', 'pueblo', 'domingo'] },
  { a: 'Juego de la rana', b: 'Caliche', pistas: ['hierro', 'feria', 'pueblo'] },
  { a: 'Tiro de barra', b: 'Birle', pistas: ['pueblo', 'fuerza', 'fiesta'] },
  { a: 'Traineras', b: 'Bateles', pistas: ['mar', 'remero', 'bandera'] },
  { a: 'Regata', b: 'Travesía', pistas: ['agua', 'boya', 'chaleco'] },
  { a: 'Equitación', b: 'Doma', pistas: ['silla', 'casco', 'pista'] },
  { a: 'Salto ecuestre', b: 'Polo', pistas: ['valla', 'césped', 'casco'] },
  { a: 'Turf', b: 'Galgos', pistas: ['apuesta', 'domingo', 'pista'] },
  { a: 'Tiro con arco', b: 'Tiro olímpico', pistas: ['diana', 'pulso', 'silencio'] },
  { a: 'Caza', b: 'Pesca', pistas: ['madrugón', 'permiso', 'silencio'] },
  { a: 'Colombicultura', b: 'Cetrería', pistas: ['cielo', 'pueblo', 'ave'] },
  { a: 'Juegos Olímpicos', b: 'Juegos Paralímpicos', pistas: ['medalla', 'himno', 'antorcha'] },
  { a: 'Mundial', b: 'Eurocopa', pistas: ['verano', 'himno', 'bar'] },
  { a: 'Copa del Rey', b: 'Supercopa', pistas: ['agosto', 'final', 'himno'] },
  { a: 'Champions', b: 'Europa League', pistas: ['martes', 'himno', 'noche'] },
  { a: 'La Vuelta', b: 'Tour de Francia', pistas: ['julio', 'puerto', 'tele'] },
  { a: 'Derbi', b: 'Clásico', pistas: ['odio', 'ciudad', 'domingo'] },
  { a: 'Wimbledon', b: 'Roland Garros', pistas: ['blanco', 'fresa', 'tierra'] },
  { a: 'Liga', b: 'Playoff', pistas: ['puntos', 'clasificación', 'mayo'] },
  { a: 'Paintball', b: 'Airsoft', pistas: ['chaleco', 'recinto', 'disparo'] },
  { a: 'Póker', b: 'Mus', pistas: ['naipes', 'farol', 'mesa'] },
  { a: 'Bridge', b: 'Tute', pistas: ['baza', 'silencio', 'pareja'] },
  { a: 'Dominó', b: 'Mahjong', pistas: ['ficha', 'cafetería', 'silencio'] },
];

export const DEPORTES: Tema = {
  id: 'deportes',
  nombre: 'Deportes',
  pinta: 'Del fútbol de siempre al pádel del cuñado',
  terminos,
};
