import type { Tema, Termino } from './tipos';

const terminos: readonly Termino[] = [
  { a: 'Siesta', b: 'Sobremesa', pistas: ['sofá', 'después', 'defender'] },
  { a: 'Lotería', b: 'Quiniela', pistas: ['navidad', 'décimo', 'niños'] },
  { a: 'Botellón', b: 'Verbena', pistas: ['plaza', 'noche', 'bolsa'] },
  { a: 'Feria', b: 'Romería', pistas: ['caseta', 'polvo', 'traje'] },
  { a: 'Sanfermines', b: 'Fallas', pistas: ['julio', 'correr', 'blanco'] },
  { a: 'Menú del día', b: 'Tapa', pistas: ['primero', 'once euros', 'pan'] },
  { a: 'Chiringuito', b: 'Terraza', pistas: ['arena', 'sardinas', 'agosto'] },
  { a: 'Cuñado', b: 'Vecino', pistas: ['sabe', 'comida', 'opina'] },
  { a: 'DNI', b: 'Pasaporte', pistas: ['cartera', 'foto', 'caducado'] },
  { a: 'Cercanías', b: 'Metro', pistas: ['retraso', 'andén', 'megafonía'] },
  { a: 'Puente', b: 'Festivo', pistas: ['diciembre', 'atasco', 'calendario'] },
  { a: 'Rebajas', b: 'Viernes negro', pistas: ['enero', 'cola', 'igual'] },
  { a: 'Semana Santa', b: 'Procesión', pistas: ['vela', 'silencio', 'paso'] },
  { a: 'Nochevieja', b: 'Nochebuena', pistas: ['uvas', 'familia', 'tele'] },
  { a: 'Cabalgata', b: 'Reyes', pistas: ['caramelos', 'frío', 'ilusión'] },
  { a: 'Carnaval', b: 'Entierro de la sardina', pistas: ['disfraz', 'febrero', 'comparsa'] },
  { a: 'Tomatina', b: 'Batalla del vino', pistas: ['manchado', 'pueblo', 'agosto'] },
  { a: 'Moros y cristianos', b: 'Gigantes y cabezudos', pistas: ['desfile', 'pólvora', 'pueblo'] },
  { a: 'El Rocío', b: 'Pentecostés', pistas: ['carro', 'polvo', 'rociero'] },
  { a: 'San Juan', b: 'Hogueras', pistas: ['playa', 'fuego', 'junio'] },
  { a: 'Magosto', b: 'Castañada', pistas: ['otoño', 'castaña', 'fuego'] },
  { a: 'Matanza', b: 'San Martín', pistas: ['pueblo', 'invierno', 'cerdo'] },
  { a: 'Quintos', b: 'Mili', pistas: ['pueblo', 'chavales', 'recuerdo'] },
  { a: 'Nazareno', b: 'Costalero', pistas: ['capirote', 'silencio', 'peso'] },
  { a: 'Saeta', b: 'Marcha procesional', pistas: ['balcón', 'silencio', 'pelo'] },
  { a: 'Mascletà', b: 'Castillo de fuegos', pistas: ['oído', 'plaza', 'pólvora'] },
  { a: 'Petardo', b: 'Traca', pistas: ['niño', 'verano', 'susto'] },
  { a: 'Campanadas', b: 'Uvas', pistas: ['doce', 'tele', 'reloj'] },
  { a: 'Caganer', b: 'Tió', pistas: ['belén', 'caca', 'catalán'] },
  { a: 'Belén', b: 'Pesebre', pistas: ['figuras', 'musgo', 'polvo'] },
  { a: 'Roscón', b: 'Torrijas', pistas: ['nata', 'haba', 'postre'] },
  { a: 'Polvorón', b: 'Mantecado', pistas: ['migas', 'navidad', 'almendra'] },
  { a: 'Cotillón', b: 'Aguinaldo', pistas: ['gorro', 'diciembre', 'bolsa'] },
  { a: 'Gazpacho', b: 'Salmorejo', pistas: ['vaso', 'verano', 'frío'] },
  { a: 'Cocido', b: 'Fabada', pistas: ['invierno', 'cuchara', 'domingo'] },
  { a: 'Croqueta', b: 'Pincho', pistas: ['bar', 'frito', 'ración'] },
  { a: 'Patatas bravas', b: 'Alioli', pistas: ['barra', 'picante', 'compartir'] },
  { a: 'Aceitunas', b: 'Pipas', pistas: ['barra', 'cuenco', 'esperar'] },
  { a: 'Caña', b: 'Copa', pistas: ['barra', 'espuma', 'ronda'] },
  { a: 'Tinto de verano', b: 'Sangría', pistas: ['jarra', 'hielo', 'terraza'] },
  { a: 'Kalimotxo', b: 'Cubata', pistas: ['botella', 'fiesta', 'barato'] },
  { a: 'Cava', b: 'Txakoli', pistas: ['burbuja', 'brindis', 'norte'] },
  { a: 'Pacharán', b: 'Orujo', pistas: ['chupito', 'postre', 'digestivo'] },
  { a: 'Horchata', b: 'Agua de Valencia', pistas: ['jarra', 'paja', 'verano'] },
  { a: 'Porrón', b: 'Botijo', pistas: ['chorro', 'pueblo', 'verano'] },
  { a: 'Pintxo', b: 'Montadito', pistas: ['barra', 'palillo', 'norte'] },
  { a: 'Callos', b: 'Oreja', pistas: ['cazuela', 'bar', 'invierno'] },
  { a: 'Cochinillo', b: 'Lechazo', pistas: ['horno', 'mesón', 'domingo'] },
  { a: 'Percebes', b: 'Navajas', pistas: ['caro', 'mar', 'mariscada'] },
  { a: 'Aceite de oliva', b: 'Vinagre de Jerez', pistas: ['tostada', 'cocina', 'desayuno'] },
  { a: 'Pan con tomate', b: 'Pan tumaca', pistas: ['aceite', 'desayuno', 'simple'] },
  { a: 'Con cebolla', b: 'Sin cebolla', pistas: ['discusión', 'bar', 'guerra'] },
  { a: 'Almuerzo', b: 'Merienda', pistas: ['media mañana', 'bocata', 'costumbre'] },
  { a: 'Vermú', b: 'Aperitivo', pistas: ['domingo', 'aceituna', 'mediodía'] },
  { a: 'Ir de cañas', b: 'Tapeo', pistas: ['ronda', 'barra', 'saltar'] },
  { a: 'Ración', b: 'Media ración', pistas: ['compartir', 'plato', 'barra'] },
  { a: 'Clara', b: 'Mosto', pistas: ['grifo', 'suave', 'verano'] },
  { a: 'Cola Cao', b: 'Nocilla', pistas: ['desayuno', 'cuchara', 'infantil'] },
  { a: 'Mollete', b: 'Pitufo', pistas: ['desayuno', 'aceite', 'sur'] },
  { a: 'Ensaimada', b: 'Quesada', pistas: ['desayuno', 'espiral', 'postre'] },
  { a: 'Flan', b: 'Crema catalana', pistas: ['cucharilla', 'quemado', 'menú'] },
  { a: 'Arroz con leche', b: 'Natillas', pistas: ['canela', 'abuela', 'cucharilla'] },
  { a: 'Kikos', b: 'Ganchitos', pistas: ['bolsa', 'aperitivo', 'crujiente'] },
  { a: 'Chupa chups', b: 'Sugus', pistas: ['caramelo', 'bolsillo', 'pegajoso'] },
  { a: 'Pata negra', b: 'Bellota', pistas: ['caro', 'navidad', 'pata'] },
  { a: 'Rioja', b: 'Ribera', pistas: ['copa', 'crianza', 'etiqueta'] },
  { a: 'Albariño', b: 'Verdejo', pistas: ['frío', 'marisco', 'verano'] },
  { a: 'Anís', b: 'Licor 43', pistas: ['chupito', 'postre', 'dulce'] },
  { a: 'Jerez', b: 'Brandy', pistas: ['copa', 'sur', 'barrica'] },
  { a: 'Barra de pan', b: 'Chapata', pistas: ['madrugón', 'brazo', 'crujiente'] },
  { a: 'Casa de comidas', b: 'Mesón', pistas: ['menú', 'mantel', 'de siempre'] },
  { a: 'Sidrería', b: 'Asador', pistas: ['escanciar', 'domingo', 'norte'] },
  { a: 'Ronda', b: 'A escote', pistas: ['pagar', 'grupo', 'discusión'] },
  { a: 'Andalucía', b: 'Extremadura', pistas: ['calor', 'acento', 'seco'] },
  { a: 'Galicia', b: 'Asturias', pistas: ['lluvia', 'verde', 'norte'] },
  { a: 'País Vasco', b: 'Navarra', pistas: ['norte', 'verde', 'carácter'] },
  { a: 'Cataluña', b: 'Comunidad Valenciana', pistas: ['costa', 'idioma', 'arroz'] },
  { a: 'Castilla-La Mancha', b: 'Castilla y León', pistas: ['meseta', 'seco', 'pueblo'] },
  { a: 'Aragón', b: 'La Rioja', pistas: ['interior', 'vino', 'seco'] },
  { a: 'Canarias', b: 'Baleares', pistas: ['isla', 'avión', 'eterno'] },
  { a: 'Andaluz', b: 'Gallego', pistas: ['acento', 'chiste', 'carácter'] },
  { a: 'Vasco', b: 'Catalán', pistas: ['idioma', 'carácter', 'norte'] },
  { a: 'Madrileño', b: 'Sevillano', pistas: ['acento', 'carácter', 'chiste'] },
  { a: 'Autonomía', b: 'Diputación', pistas: ['competencia', 'sede', 'lío'] },
  { a: 'Constitución', b: 'Estatuto', pistas: ['artículo', '78', 'pacto'] },
  { a: 'Diputado', b: 'Senador', pistas: ['escaño', 'sueldo', 'hemiciclo'] },
  { a: 'Alcalde', b: 'Concejal', pistas: ['pueblo', 'banda', 'pleno'] },
  { a: 'Guardia Civil', b: 'Policía Nacional', pistas: ['uniforme', 'control', 'tricornio'] },
  { a: 'Mossos', b: 'Ertzaintza', pistas: ['policía', 'autonomía', 'idioma'] },
  { a: 'Funcionario', b: 'Interino', pistas: ['plaza', 'oposición', 'fijo'] },
  { a: 'Oposición', b: 'Plaza', pistas: ['temario', 'años', 'temas'] },
  { a: 'Paro', b: 'ERTE', pistas: ['prestación', 'papeles', 'temporal'] },
  { a: 'SEPE', b: 'Seguridad Social', pistas: ['cita', 'cola', 'certificado'] },
  { a: 'IRPF', b: 'Borrador', pistas: ['junio', 'hacienda', 'miedo'] },
  { a: 'IVA', b: 'Recibo', pistas: ['porcentaje', 'factura', 'extra'] },
  { a: 'Enchufe', b: 'Amiguismo', pistas: ['primo', 'plaza', 'siempre'] },
  { a: 'BOE', b: 'Boletín', pistas: ['pdf', 'disposición', 'denso'] },
  { a: 'Operación salida', b: 'Operación retorno', pistas: ['agosto', 'atasco', 'radio'] },
  { a: 'ITV', b: 'Multa', pistas: ['cita', 'miedo', 'pegatina'] },
  { a: 'Zona azul', b: 'ORA', pistas: ['parquímetro', 'vueltas', 'ticket'] },
  { a: 'AVE', b: 'ALVIA', pistas: ['retraso', 'asiento', 'silencio'] },
  { a: 'RENFE', b: 'Rodalies', pistas: ['andén', 'aviso', 'retraso'] },
  { a: 'NIE', b: 'CIF', pistas: ['extranjería', 'papeles', 'cita'] },
  { a: 'Tarjeta sanitaria', b: 'Receta', pistas: ['centro', 'cola', 'médico'] },
  { a: 'Médico de cabecera', b: 'Especialista', pistas: ['cita', 'espera', 'derivar'] },
  { a: 'Lista de espera', b: 'Mutua', pistas: ['meses', 'seguro', 'privado'] },
  { a: 'Selectividad', b: 'EvAU', pistas: ['junio', 'nervios', 'nota'] },
  { a: 'ESO', b: 'Bachillerato', pistas: ['instituto', 'examen', 'adolescente'] },
  { a: 'Comunidad de vecinos', b: 'Junta', pistas: ['ruidoso', 'derrama', 'acta'] },
  { a: 'Sálvame', b: 'Deluxe', pistas: ['sofá', 'grito', 'tarde'] },
  { a: 'El Hormiguero', b: 'El Intermedio', pistas: ['sofá', 'invitado', 'noche'] },
  { a: 'Gran Hermano', b: 'Supervivientes', pistas: ['gala', 'expulsión', 'grito'] },
  { a: 'Pasapalabra', b: 'Saber y ganar', pistas: ['rosco', 'sillón', 'pista'] },
  { a: 'La 1', b: 'Telecinco', pistas: ['telediario', 'anuncio', 'sofá'] },
  { a: 'Marca', b: 'As', pistas: ['bar', 'portada', 'domingo'] },
  { a: 'El País', b: 'El Mundo', pistas: ['portada', 'domingo', 'opinión'] },
  { a: 'Cadena SER', b: 'COPE', pistas: ['radio', 'mañana', 'tertulia'] },
  { a: 'Los 40', b: 'Cadena 100', pistas: ['radio', 'verano', 'lista'] },
  { a: 'Aquí no hay quien viva', b: 'La que se avecina', pistas: ['vecinos', 'rellano', 'grito'] },
  { a: 'Cuéntame', b: 'Verano azul', pistas: ['nostalgia', 'tele', 'verano'] },
  { a: 'Eurovisión', b: 'OT', pistas: ['voto', 'palmito', 'sábado'] },
  { a: 'Cervantes', b: 'Lope de Vega', pistas: ['siglo', 'teatro', 'cita'] },
  { a: 'Velázquez', b: 'Goya', pistas: ['museo', 'corte', 'oscuro'] },
  { a: 'Picasso', b: 'Dalí', pistas: ['bigote', 'museo', 'caro'] },
  { a: 'Gaudí', b: 'Calatrava', pistas: ['obra', 'turista', 'presupuesto'] },
  { a: 'Almodóvar', b: 'Amenábar', pistas: ['premio', 'acento', 'cine'] },
  { a: 'Mecano', b: 'Alaska', pistas: ['ochenta', 'tele', 'nostalgia'] },
  { a: 'Lola Flores', b: 'Rocío Jurado', pistas: ['bata', 'olé', 'arte'] },
  { a: 'Camarón', b: 'Paco de Lucía', pistas: ['toque', 'quejío', 'noche'] },
  { a: 'Julio Iglesias', b: 'Raphael', pistas: ['gafas', 'gira', 'eterno'] },
  { a: 'Movida', b: 'Destape', pistas: ['ochenta', 'madrid', 'libertad'] },
  { a: 'Transición', b: '78', pistas: ['pacto', 'abuelos', 'historia'] },
  { a: '12 de octubre', b: 'Hispanidad', pistas: ['desfile', 'discusión', 'bandera'] },
  { a: '6 de diciembre', b: '15 de agosto', pistas: ['calendario', 'maleta', 'colegio'] },
  { a: 'Todos los Santos', b: 'Día de difuntos', pistas: ['flores', 'cementerio', 'crisantemo'] },
  { a: 'Chupinazo', b: 'Encierro', pistas: ['plaza', 'blanco', 'miedo'] },
  { a: 'Pañuelo rojo', b: 'Faja', pistas: ['blanco', 'julio', 'vestir'] },
  { a: 'Fallera', b: 'Mantilla', pistas: ['peineta', 'traje', 'flores'] },
  { a: 'Sevillanas', b: 'Rumba', pistas: ['palmas', 'paso', 'calor'] },
  { a: 'Jota', b: 'Muñeira', pistas: ['pueblo', 'traje', 'fiesta'] },
  { a: 'Sardana', b: 'Aurresku', pistas: ['círculo', 'solemne', 'plaza'] },
  { a: 'Gaita', b: 'Txistu', pistas: ['norte', 'fiesta', 'agudo'] },
  { a: 'Castañuelas', b: 'Palmas', pistas: ['compás', 'tablao', 'manos'] },
  { a: 'Peineta', b: 'Mantón', pistas: ['traje', 'flores', 'feria'] },
  { a: 'Abanico', b: 'Sombrero de paja', pistas: ['calor', 'agosto', 'sombra'] },
  { a: 'Chanclas', b: 'Alpargatas', pistas: ['verano', 'playa', 'pie'] },
  { a: 'Traje de flamenca', b: 'Faralaes', pistas: ['volante', 'calor', 'feria'] },
  { a: 'Camino de Santiago', b: 'Compostela', pistas: ['flecha', 'mochila', 'sello'] },
  { a: 'Peregrino', b: 'Rociero', pistas: ['polvo', 'camino', 'grupo'] },
  { a: 'Dos besos', b: 'Tuteo', pistas: ['saludo', 'mejilla', 'costumbre'] },
  { a: 'Salud', b: 'Jesús', pistas: ['estornudo', 'automático', 'educación'] },
  { a: 'Mañana', b: 'El lunes', pistas: ['posponer', 'barra', 'promesa'] },
  { a: 'Invitar', b: 'A medias', pistas: ['cuenta', 'discusión', 'orgullo'] },
  { a: 'Persiana', b: 'Toldo', pistas: ['calor', 'ruido', 'verano'] },
  { a: 'Portero automático', b: 'Reja', pistas: ['portal', 'zumbido', 'llave'] },
  { a: 'Reciclaje', b: 'Contenedor amarillo', pistas: ['bolsa', 'abajo', 'olvido'] },
  { a: 'Huelga', b: 'Manifestación', pistas: ['pancarta', 'metro', 'viernes'] },
  { a: 'ONCE', b: 'Cupón', pistas: ['esquina', 'sábado', 'número'] },
  { a: 'Primitiva', b: 'Euromillones', pistas: ['viernes', 'boleto', 'ilusión'] },
  { a: 'El Gordo', b: 'El Niño', pistas: ['navidad', 'administración', 'lágrima'] },
  { a: 'Cortado', b: 'Café con leche', pistas: ['barra', 'mañana', 'nube'] },
];

export const ESPANA: Tema = {
  id: 'espana',
  nombre: 'Cosas de España',
  pinta: 'Lo que se explica fatal a un extranjero',
  terminos,
};
