import type { Tema, Termino } from './tipos';

/** Parejas de gente famosa. Sin futbolistas: esos van en su mazo. */
const terminos: readonly Termino[] = [
  { a: 'Cervantes', b: 'Quevedo', pistas: ['siglo de oro', 'pluma', 'castellano'] },
  { a: 'Shakespeare', b: 'Molière', pistas: ['teatro', 'rey', 'verso'] },
  { a: 'Lope de Vega', b: 'Calderón', pistas: ['corral', 'capa', 'barroco'] },
  { a: 'García Márquez', b: 'Vargas Llosa', pistas: ['Nobel', 'trópico', 'boom'] },
  { a: 'Borges', b: 'Cortázar', pistas: ['cuento', 'laberinto', 'sur'] },
  { a: 'Lorca', b: 'Machado', pistas: ['verso', 'generación', 'exilio'] },
  { a: 'Neruda', b: 'Octavio Paz', pistas: ['Nobel', 'verso', 'América'] },
  { a: 'Hemingway', b: 'Fitzgerald', pistas: ['copa', 'novela', 'América'] },
  { a: 'Jane Austen', b: 'Charlotte Brontë', pistas: ['carta', 'casarse', 'campo'] },
  { a: 'Kafka', b: 'Dostoievski', pistas: ['culpa', 'oscuro', 'carta'] },
  { a: 'Homero', b: 'Virgilio', pistas: ['viaje', 'dioses', 'verso'] },
  { a: 'Dante', b: 'Petrarca', pistas: ['Italia', 'amada', 'verso'] },
  { a: 'Cela', b: 'Delibes', pistas: ['pueblo', 'posguerra', 'premio'] },
  { a: 'Galdós', b: 'Clarín', pistas: ['folletín', 'señorita', 'siglo XIX'] },
  { a: 'Unamuno', b: 'Baroja', pistas: ['98', 'ensayo', 'generación'] },
  { a: 'Gloria Fuertes', b: 'Ana María Matute', pistas: ['niños', 'cuento', 'posguerra'] },
  { a: 'Julio Verne', b: 'H. G. Wells', pistas: ['máquina', 'futuro', 'viaje'] },
  { a: 'Oscar Wilde', b: 'Lord Byron', pistas: ['dandy', 'escándalo', 'verso'] },
  { a: 'Goethe', b: 'Schiller', pistas: ['alemán', 'drama', 'verso'] },
  { a: 'Agatha Christie', b: 'Conan Doyle', pistas: ['mayordomo', 'pipa', 'asesinato'] },
  { a: 'Stephen King', b: 'Poe', pistas: ['susto', 'noche', 'sótano'] },
  { a: 'Tolkien', b: 'C. S. Lewis', pistas: ['mapa', 'mago', 'niños'] },
  { a: 'J. K. Rowling', b: 'Roald Dahl', pistas: ['niños', 'magia', 'inglés'] },
  { a: 'Camus', b: 'Sartre', pistas: ['café', 'París', 'absurdo'] },
  { a: 'Platón', b: 'Aristóteles', pistas: ['academia', 'griego', 'alumno'] },
  { a: 'Diógenes', b: 'Epicuro', pistas: ['plaza', 'placer', 'tonel'] },
  { a: 'Kant', b: 'Hegel', pistas: ['alemán', 'razón', 'denso'] },
  { a: 'Nietzsche', b: 'Schopenhauer', pistas: ['bigote', 'pesimista', 'aforismo'] },
  { a: 'Descartes', b: 'Spinoza', pistas: ['duda', 'razón', 'método'] },
  { a: 'Marx', b: 'Engels', pistas: ['manifiesto', 'fábrica', 'barba'] },
  { a: 'Confucio', b: 'Lao-Tse', pistas: ['dicho', 'oriente', 'camino'] },
  { a: 'Séneca', b: 'Cicerón', pistas: ['Roma', 'carta', 'discurso'] },
  { a: 'Einstein', b: 'Newton', pistas: ['física', 'teoría', 'pelo'] },
  { a: 'Galileo', b: 'Copérnico', pistas: ['gira', 'iglesia', 'cielo'] },
  { a: 'Darwin', b: 'Mendel', pistas: ['especie', 'herencia', 'jardín'] },
  { a: 'Marie Curie', b: 'Pasteur', pistas: ['laboratorio', 'bata', 'premio'] },
  { a: 'Tesla', b: 'Edison', pistas: ['corriente', 'patente', 'bombilla'] },
  { a: 'Hawking', b: 'Sagan', pistas: ['cosmos', 'libro', 'voz'] },
  { a: 'Fleming', b: 'Jenner', pistas: ['vacuna', 'casualidad', 'bata'] },
  { a: 'Ramón y Cajal', b: 'Severo Ochoa', pistas: ['Nobel', 'laboratorio', 'español'] },
  { a: 'Ada Lovelace', b: 'Turing', pistas: ['máquina', 'notas', 'código'] },
  { a: 'Arquímedes', b: 'Pitágoras', pistas: ['griego', 'número', 'antiguo'] },
  { a: 'Oppenheimer', b: 'Fermi', pistas: ['bomba', 'secreto', 'laboratorio'] },
  { a: 'Watson y Crick', b: 'Rosalind Franklin', pistas: ['hélice', 'foto', 'Nobel'] },
  { a: 'Margarita Salas', b: 'Rita Levi-Montalcini', pistas: ['laboratorio', 'mujer', 'Nobel'] },
  { a: 'Freud', b: 'Jung', pistas: ['diván', 'sueño', 'madre'] },
  { a: 'Picasso', b: 'Dalí', pistas: ['cuadro', 'museo', 'español'] },
  { a: 'Velázquez', b: 'Goya', pistas: ['corte', 'Prado', 'rey'] },
  { a: 'Frida Kahlo', b: 'Diego Rivera', pistas: ['México', 'marco', 'cama'] },
  { a: 'Van Gogh', b: 'Gauguin', pistas: ['taller', 'sur', 'amarillo'] },
  { a: 'Monet', b: 'Renoir', pistas: ['luz', 'campo', 'agua'] },
  { a: 'Miguel Ángel', b: 'Leonardo da Vinci', pistas: ['Florencia', 'anatomía', 'capilla'] },
  { a: 'Rembrandt', b: 'Vermeer', pistas: ['Holanda', 'luz', 'retrato'] },
  { a: 'Warhol', b: 'Keith Haring', pistas: ['lata', 'calle', 'pop'] },
  { a: 'Miró', b: 'Tàpies', pistas: ['catalán', 'mancha', 'fundación'] },
  { a: 'El Greco', b: 'Zurbarán', pistas: ['santo', 'Toledo', 'oscuro'] },
  { a: 'Botticelli', b: 'Rafael', pistas: ['Florencia', 'virgen', 'suave'] },
  { a: 'Magritte', b: 'Escher', pistas: ['truco', 'pipa', 'escalera'] },
  { a: 'Banksy', b: 'Basquiat', pistas: ['calle', 'spray', 'corona'] },
  { a: 'Gaudí', b: 'Calatrava', pistas: ['arquitecto', 'curva', 'obra'] },
  { a: 'Beatles', b: 'Rolling Stones', pistas: ['británicos', 'sesenta', 'guitarra'] },
  { a: 'Mozart', b: 'Beethoven', pistas: ['partitura', 'clásico', 'peluca'] },
  { a: 'Bach', b: 'Händel', pistas: ['barroco', 'órgano', 'peluca'] },
  { a: 'Queen', b: 'ABBA', pistas: ['setenta', 'estribillo', 'directo'] },
  { a: 'Madonna', b: 'Cher', pistas: ['escenario', 'rubia', 'reinicio'] },
  { a: 'Michael Jackson', b: 'Prince', pistas: ['escenario', 'ochenta', 'baile'] },
  { a: 'Elvis', b: 'Johnny Cash', pistas: ['Memphis', 'radio', 'traje'] },
  { a: 'Camarón', b: 'Paco de Lucía', pistas: ['tablao', 'duende', 'Jerez'] },
  { a: 'Julio Iglesias', b: 'Raphael', pistas: ['bis', 'corbata', 'Marbella'] },
  { a: 'Mecano', b: 'Alaska', pistas: ['ochenta', 'movida', 'teclado'] },
  { a: 'Bob Dylan', b: 'Leonard Cohen', pistas: ['letra', 'Nobel', 'guitarra'] },
  { a: 'Pink Floyd', b: 'Led Zeppelin', pistas: ['vinilo', 'largo', 'británicos'] },
  { a: 'Lola Flores', b: 'Rocío Jurado', pistas: ['copla', 'bata', 'olé'] },
  { a: 'Sabina', b: 'Serrat', pistas: ['pitillo', 'verso', 'directo'] },
  { a: 'Shakira', b: 'Beyoncé', pistas: ['cadera', 'rubia', 'directo'] },
  { a: 'Rosalía', b: 'C. Tangana', pistas: ['trap', 'español', 'verano'] },
  { a: 'Almodóvar', b: 'Amenábar', pistas: ['plano', 'Oscar', 'español'] },
  { a: 'Buñuel', b: 'Berlanga', pistas: ['pueblo', 'corte', 'raro'] },
  { a: 'Penélope Cruz', b: 'Javier Bardem', pistas: ['Oscar', 'pareja', 'español'] },
  { a: 'Antonio Banderas', b: 'Benicio del Toro', pistas: ['Hollywood', 'acento', 'Oscar'] },
  { a: 'Marilyn Monroe', b: 'Audrey Hepburn', pistas: ['rubia', 'Hollywood', 'vestido'] },
  { a: 'Chaplin', b: 'Buster Keaton', pistas: ['mudo', 'bigote', 'caídas'] },
  { a: 'Hitchcock', b: 'Spielberg', pistas: ['suspense', 'taquilla', 'plano'] },
  { a: 'Tarantino', b: 'Scorsese', pistas: ['sangre', 'monólogo', 'cine'] },
  { a: 'Tom Hanks', b: 'DiCaprio', pistas: ['Oscar', 'barco', 'simpático'] },
  { a: 'Bruce Lee', b: 'Jackie Chan', pistas: ['patada', 'chino', 'grito'] },
  { a: 'Schwarzenegger', b: 'Stallone', pistas: ['músculo', 'ochenta', 'secuela'] },
  { a: 'Brad Pitt', b: 'George Clooney', pistas: ['guapo', 'Hollywood', 'anuncio'] },
  { a: 'Carmen Maura', b: 'Marisa Paredes', pistas: ['diva', 'chica', 'movida'] },
  { a: 'Luis Tosar', b: 'Javier Cámara', pistas: ['drama', 'prota', 'español'] },
  { a: 'Belén Esteban', b: 'Jorge Javier', pistas: ['sábado', 'sofá', 'grito'] },
  { a: 'Pablo Motos', b: 'Buenafuente', pistas: ['invitado', 'sofá', 'noche'] },
  { a: 'Broncano', b: 'Berto Romero', pistas: ['late', 'sillón', 'risa'] },
  { a: 'Ibai', b: 'AuronPlay', pistas: ['directo', 'risas', 'cascos'] },
  { a: 'Napoleón', b: 'César', pistas: ['imperio', 'corona', 'batalla'] },
  { a: 'Cleopatra', b: 'Nefertiti', pistas: ['Egipto', 'ojo', 'trono'] },
  { a: 'Isabel la Católica', b: 'Isabel II', pistas: ['corona', 'España', 'reina'] },
  { a: 'Churchill', b: 'De Gaulle', pistas: ['guerra', 'discurso', 'aliados'] },
  { a: 'Gandhi', b: 'Mandela', pistas: ['cárcel', 'paz', 'marcha'] },
  { a: 'Lincoln', b: 'Washington', pistas: ['billete', 'presidente', 'monumento'] },
  { a: 'Felipe II', b: 'Carlos V', pistas: ['imperio', 'Austria', 'corona'] },
  { a: 'Juana de Arco', b: 'Catalina de Médici', pistas: ['Francia', 'corona', 'siglo'] },
  { a: 'Che Guevara', b: 'Fidel Castro', pistas: ['barba', 'boina', 'Habana'] },
  { a: 'Kennedy', b: 'Nixon', pistas: ['discurso', 'Casa Blanca', 'sesenta'] },
  { a: 'Alejandro Magno', b: 'Aníbal', pistas: ['conquista', 'antiguo', 'caballo'] },
  { a: 'Colón', b: 'Magallanes', pistas: ['barco', 'mapa', 'Indias'] },
  { a: 'Hernán Cortés', b: 'Francisco Pizarro', pistas: ['oro', 'conquistador', 'América'] },
  { a: 'El Cid', b: 'Don Pelayo', pistas: ['castillo', 'caballo', 'Asturias'] },
  { a: 'Adolfo Suárez', b: 'Felipe González', pistas: ['transición', 'corbata', 'Moncloa'] },
  { a: 'Juan Carlos I', b: 'Felipe VI', pistas: ['corona', 'Zarzuela', 'discurso'] },
  { a: 'Obama', b: 'Merkel', pistas: ['discurso', 'cumbre', 'foto'] },
  { a: 'Lenin', b: 'Trotski', pistas: ['barba', 'exilio', 'rojo'] },
  { a: 'Letizia', b: 'Reina Sofía', pistas: ['corona', 'balcón', 'revista'] },
  { a: 'Tutankamón', b: 'Ramsés', pistas: ['momia', 'Egipto', 'oro'] },
  { a: 'Bolívar', b: 'San Martín', pistas: ['libertador', 'caballo', 'América'] },
  { a: 'Nadal', b: 'Federer', pistas: ['raqueta', 'Wimbledon', 'revés'] },
  { a: 'Fernando Alonso', b: 'Lewis Hamilton', pistas: ['casco', 'pole', 'box'] },
  { a: 'Pau Gasol', b: 'Marc Gasol', pistas: ['hermanos', 'canasta', 'altos'] },
  { a: 'Muhammad Ali', b: 'Mike Tyson', pistas: ['ring', 'guantes', 'asalto'] },
  { a: 'Michael Jordan', b: 'LeBron James', pistas: ['canasta', 'zapatillas', 'anillos'] },
];

export const FAMOSOS: Tema = {
  id: 'famosos',
  nombre: 'Famosos',
  pinta: 'Gente que se explica en dos pistas malas',
  terminos,
};
