import type { Tema, Termino } from './tipos';

/** Un mazo: clásicos y modernos en el mismo saco. */
const terminos: readonly Termino[] = [
  { a: 'Messi', b: 'Cristiano Ronaldo', pistas: ['Pulga', 'Barcelona', 'diez'] },
  { a: 'Pelé', b: 'Maradona', pistas: ['Rey', 'Brasil', 'mano'] },
  { a: 'Di Stéfano', b: 'Puskás', pistas: ['Saeta', 'Madrid', 'húngaro'] },
  { a: 'Cruyff', b: 'Beckenbauer', pistas: ['Naranja', 'káiser', 'holandés'] },
  { a: 'Zidane', b: 'Figo', pistas: ['Cabezazo', 'Francia', 'galáctico'] },
  { a: 'Ronaldo Nazário', b: 'Ronaldinho', pistas: ['Fenómeno', 'diente', 'Brasil'] },
  { a: 'Haaland', b: 'Mbappé', pistas: ['Noruega', 'City', 'velocidad'] },
  { a: 'Vinicius', b: 'Rodrygo', pistas: ['Baile', 'Madrid', 'banda'] },
  { a: 'Bellingham', b: 'Pedri', pistas: ['Interior', 'Inglaterra', 'joven'] },
  { a: 'Lewandowski', b: 'Benzema', pistas: ['Nueve', 'Polonia', 'Champions'] },
  { a: 'Kane', b: 'Salah', pistas: ['Inglaterra', 'Liverpool', 'gol'] },
  { a: 'Casillas', b: 'Buffon', pistas: ['Santo', 'parada', 'guantes'] },
  { a: 'Ramos', b: 'Piqué', pistas: ['Central', 'clásico', 'cabeza'] },
  { a: 'Xavi', b: 'Iniesta', pistas: ['2010', 'toque', 'ocho'] },
  { a: 'Modric', b: 'Kroos', pistas: ['Balón', 'pase', 'Madrid'] },
  { a: 'Neymar', b: 'Hazard', pistas: ['Regate', 'PSG', 'Brasil'] },
  { a: 'Luis Suárez', b: 'David Villa', pistas: ['Nueve', 'Uruguay', 'mordisco'] },
  { a: 'Raúl', b: 'Fernando Torres', pistas: ['Niño', 'Madrid', 'España'] },
  { a: 'Eusébio', b: 'George Best', pistas: ['Pantera', 'Portugal', 'Manchester'] },
  { a: 'Platini', b: 'Rummenigge', pistas: ['Francia', 'Balón', 'ochenta'] },
  { a: 'Van Basten', b: 'Gullit', pistas: ['Holanda', 'Milan', 'volea'] },
  { a: 'Maldini', b: 'Nesta', pistas: ['Milan', 'Italia', 'eterno'] },
  { a: 'Cafu', b: 'Roberto Carlos', pistas: ['Lateral', 'Brasil', 'falta'] },
  { a: 'Gerrard', b: 'Lampard', pistas: ['Inglaterra', 'Liverpool', 'Chelsea'] },
  { a: 'Scholes', b: 'Giggs', pistas: ['United', 'pelirrojo', 'Gales'] },
  { a: 'Henry', b: 'Bergkamp', pistas: ['Arsenal', 'Francia', 'Highbury'] },
  { a: 'Del Piero', b: 'Totti', pistas: ['Italia', 'diez', 'Roma'] },
  { a: 'Batistuta', b: 'Klose', pistas: ['Cabeza', 'Argentina', 'Mundial'] },
  { a: 'Kaká', b: 'Shevchenko', pistas: ['Milan', 'Brasil', 'Balón'] },
  { a: 'Pirlo', b: 'Gattuso', pistas: ['Italia', 'barba', 'pase'] },
  { a: 'Cannavaro', b: 'Thuram', pistas: ['2006', 'Italia', 'central'] },
  { a: 'Kahn', b: 'Schmeichel', pistas: ['Alemania', 'portero', 'grito'] },
  { a: 'Hierro', b: 'Guardiola', pistas: ['Pivote', 'España', 'líbero'] },
  { a: 'Stoichkov', b: 'Romário', pistas: ['Dream Team', 'Bulgaria', 'nueve'] },
  { a: 'Zico', b: 'Sócrates', pistas: ['Brasil', 'ochenta', 'barba'] },
  { a: 'Falcao', b: 'Valderrama', pistas: ['Colombia', 'pelo', 'noventa'] },
  { a: 'Hugo Sánchez', b: 'Butragueño', pistas: ['Madrid', 'México', 'buitre'] },
  { a: 'Kempes', b: 'Passarella', pistas: ['Argentina', 'setenta y ocho', 'mundial'] },
  { a: 'Baresi', b: 'Costacurta', pistas: ['Milan', 'Italia', 'defensa'] },
  { a: 'Seedorf', b: 'Davids', pistas: ['Holanda', 'Ajax', 'Milan'] },
  { a: 'Makelele', b: 'Vieira', pistas: ['Pivote', 'Francia', 'Chelsea'] },
  { a: 'Drogba', b: 'Eto\'o', pistas: ['África', 'Chelsea', 'nueve'] },
  { a: 'Rooney', b: 'Tevez', pistas: ['United', 'Inglaterra', 'nueve'] },
  { a: 'Ibrahimovic', b: 'Cavani', pistas: ['Zlatan', 'PSG', 'Suecia'] },
  { a: 'Agüero', b: 'Higuaín', pistas: ['Argentina', 'nueve', 'City'] },
  { a: 'Di María', b: 'Özil', pistas: ['Diez', 'Madrid', 'zurdo'] },
  { a: 'De Bruyne', b: 'Bruno Fernandes', pistas: ['Pase', 'Bélgica', 'United'] },
  { a: 'Van Dijk', b: 'Rúben Dias', pistas: ['Central', 'Liverpool', 'City'] },
  { a: 'Alisson', b: 'Courtois', pistas: ['Portero', 'Brasil', 'Madrid'] },
  { a: 'Ter Stegen', b: 'Oblak', pistas: ['Portero', 'Barça', 'Atleti'] },
  { a: 'Donnarumma', b: 'Ederson', pistas: ['Portero', 'Italia', 'City'] },
  { a: 'Griezmann', b: 'Dembélé', pistas: ['Francia', 'Barça', 'Atleti'] },
  { a: 'Foden', b: 'Saka', pistas: ['Inglaterra', 'City', 'Arsenal'] },
  { a: 'Musiala', b: 'Wirtz', pistas: ['Alemania', 'Bayern', 'Leverkusen'] },
  { a: 'Osimhen', b: 'Lautaro', pistas: ['Nueve', 'Nápoles', 'Inter'] },
  { a: 'Isak', b: 'Gyökeres', pistas: ['Nueve', 'Suecia', 'Sporting'] },
  { a: 'Lamine Yamal', b: 'Gavi', pistas: ['Cantera', 'Barça', 'joven'] },
  { a: 'Valverde', b: 'Tchouaméni', pistas: ['Madrid', 'pivote', 'Uruguay'] },
  { a: 'Camavinga', b: 'Declan Rice', pistas: ['Pivote', 'Francia', 'Arsenal'] },
  { a: 'Rüdiger', b: 'Militão', pistas: ['Central', 'Madrid', 'Alemania'] },
  { a: 'Araujo', b: 'Cubarsí', pistas: ['Central', 'Barça', 'Uruguay'] },
  { a: 'Kubo', b: 'Nico Williams', pistas: ['España', 'Sociedad', 'Athletic'] },
  { a: 'Oyarzabal', b: 'Morata', pistas: ['España', 'Sociedad', 'nueve'] },
  { a: 'João Félix', b: 'Darwin Núñez', pistas: ['Portugal', 'Atlético', 'Liverpool'] },
  { a: 'Julián Álvarez', b: 'Openda', pistas: ['Argentina', 'City', 'nueve'] },
  { a: 'Havertz', b: 'Gündogan', pistas: ['Alemania', 'Arsenal', 'City'] },
  { a: 'Kimmich', b: 'Goretzka', pistas: ['Bayern', 'Alemania', 'pivote'] },
  { a: 'Sané', b: 'Gnabry', pistas: ['Bayern', 'Alemania', 'banda'] },
  { a: 'Thomas Müller', b: 'Werner', pistas: ['Bayern', 'Alemania', 'espacio'] },
  { a: 'Reus', b: 'Götze', pistas: ['Dortmund', 'Alemania', 'diez'] },
  { a: 'Robben', b: 'Ribéry', pistas: ['Bayern', 'banda', 'holandés'] },
  { a: 'Lahm', b: 'Alaba', pistas: ['Bayern', 'lateral', 'Alemania'] },
  { a: 'Neuer', b: 'Sommer', pistas: ['Portero', 'Alemania', 'Bayern'] },
  { a: 'Chiellini', b: 'Bonucci', pistas: ['Juventus', 'Italia', 'central'] },
  { a: 'Dybala', b: 'Chiesa', pistas: ['Juventus', 'Argentina', 'diez'] },
  { a: 'Immobile', b: 'Vlahovic', pistas: ['Nueve', 'Lazio', 'Juventus'] },
  { a: 'Lukaku', b: 'Giroud', pistas: ['Nueve', 'Bélgica', 'Francia'] },
  { a: 'Pogba', b: 'Kanté', pistas: ['Francia', 'United', 'Chelsea'] },
  { a: 'Sterling', b: 'Mahrez', pistas: ['City', 'Inglaterra', 'Argelia'] },
  { a: 'David Silva', b: 'Bernardo Silva', pistas: ['City', 'España', 'Portugal'] },
  { a: 'Cancelo', b: 'Walker', pistas: ['Lateral', 'City', 'Portugal'] },
  { a: 'Alexander-Arnold', b: 'Carvajal', pistas: ['Lateral', 'Liverpool', 'Madrid'] },
  { a: 'Hakimi', b: 'Dumfries', pistas: ['Lateral', 'PSG', 'Inter'] },
  { a: 'Theo Hernández', b: 'Alphonso Davies', pistas: ['Lateral', 'Milan', 'Bayern'] },
  { a: 'Marcelo', b: 'Jordi Alba', pistas: ['Lateral', 'Madrid', 'Barça'] },
  { a: 'Dani Alves', b: 'Maicon', pistas: ['Lateral', 'Brasil', 'Barça'] },
  { a: 'Puyol', b: 'Koeman', pistas: ['Central', 'Barça', 'Holanda'] },
  { a: 'Rijkaard', b: 'Kluivert', pistas: ['Holanda', 'Ajax', 'Milan'] },
  { a: 'Lineker', b: 'Shearer', pistas: ['Inglaterra', 'nueve', 'noventa'] },
  { a: 'Cantona', b: 'Beckham', pistas: ['United', 'Francia', 'siete'] },
  { a: 'Owen', b: 'Fowler', pistas: ['Liverpool', 'Inglaterra', 'nueve'] },
  { a: 'Rivaldo', b: 'Bebeto', pistas: ['Brasil', 'noventa', 'Barça'] },
  { a: 'Cesc Fàbregas', b: 'Xabi Alonso', pistas: ['España', 'pivote', 'Arsenal'] },
  { a: 'Llorente', b: 'Aduriz', pistas: ['Athletic', 'nueve', 'cabeza'] },
  { a: 'Unai Simón', b: 'De Gea', pistas: ['Portero', 'España', 'Athletic'] },
  { a: 'Koke', b: 'Saúl', pistas: ['Atleti', 'España', 'mediocampo'] },
  { a: 'Correa', b: 'Carrasco', pistas: ['Atleti', 'banda', 'Argentina'] },
  { a: 'Rúben Neves', b: 'Palhinha', pistas: ['Portugal', 'pivote', 'Wolves'] },
  { a: 'Ferran Torres', b: 'Ansu Fati', pistas: ['Barça', 'España', 'cantera'] },
  { a: 'Frenkie de Jong', b: 'Busquets', pistas: ['Pivote', 'Barça', 'Holanda'] },
  { a: 'Casemiro', b: 'Fabinho', pistas: ['Pivote', 'Madrid', 'Brasil'] },
  { a: 'Joselu', b: 'Asensio', pistas: ['Madrid', 'España', 'nueve'] },
  { a: 'Brahim', b: 'Gareth Bale', pistas: ['Madrid', 'banda', 'Málaga'] },
  { a: 'Eriksen', b: 'Ødegaard', pistas: ['Diez', 'Dinamarca', 'Arsenal'] },
  { a: 'Martinelli', b: 'Gabriel Jesus', pistas: ['Arsenal', 'Brasil', 'banda'] },
  { a: 'Rashford', b: 'Sancho', pistas: ['United', 'Inglaterra', 'banda'] },
  { a: 'Antony', b: 'Raphinha', pistas: ['Brasil', 'banda', 'Barça'] },
  { a: 'Weah', b: 'Roger Milla', pistas: ['África', 'Liberia', 'Milan'] },
  { a: 'Matthäus', b: 'Klinsmann', pistas: ['Alemania', 'noventa', 'pivote'] },
];

export const FUTBOL: Tema = {
  id: 'futbol',
  nombre: 'Futbolistas',
  pinta: 'De Di Stéfano a Yamal, todo el patio',
  terminos,
};
