import type { Tema, Termino } from './tipos';

const terminos: readonly Termino[] = [
  { a: 'Bug', b: 'Funcionalidad', pistas: ['depende', 'ticket', 'viernes'] },
  { a: 'Despliegue', b: 'Marcha atrás', pistas: ['viernes', 'botón', 'rezar'] },
  { a: 'Git', b: 'Subversion', pistas: ['rama', 'conflicto', 'historia'] },
  { a: 'Contraseña', b: 'Huella', pistas: ['olvidada', 'post-it', 'asteriscos'] },
  { a: 'Copia de seguridad', b: 'Foto del disco', pistas: ['nunca', 'ayer', 'llorar'] },
  { a: 'Servidor', b: 'Nube', pistas: ['caído', 'ruido', 'factura'] },
  { a: 'Wifi', b: 'Cable', pistas: ['barras', 'router', 'vecino'] },
  { a: 'Actualización', b: 'Parche', pistas: ['reinicia', 'ahora no', 'porcentaje'] },
  { a: 'Teclado', b: 'Ratón', pistas: ['migas', 'clic', 'mecánico'] },
  { a: 'Correo', b: 'Mensaje', pistas: ['bandeja', 'copia', 'adjunto'] },
  { a: 'Antivirus', b: 'Cortafuegos', pistas: ['aviso', 'lento', 'caducado'] },
  { a: 'Pantalla azul', b: 'Cuelgue', pistas: ['reinicio', 'cara', 'perdido'] },
  { a: 'Java', b: 'C#', pistas: ['clase', 'punto y coma', 'empresa'] },
  { a: 'JavaScript', b: 'TypeScript', pistas: ['cualquiera', 'undefined', 'tipos'] },
  { a: 'Python', b: 'Ruby', pistas: ['indentar', 'serpiente', 'rápido'] },
  { a: 'PHP', b: 'Perl', pistas: ['web', 'viejo', 'dólar'] },
  { a: 'Rust', b: 'Go', pistas: ['prestamo', 'rápido', 'nuevo'] },
  { a: 'C++', b: 'C', pistas: ['puntero', 'duele', 'rápido'] },
  { a: 'Kotlin', b: 'Swift', pistas: ['móvil', 'null', 'moderno'] },
  { a: 'SQL', b: 'NoSQL', pistas: ['join', 'tabla', 'lento'] },
  { a: 'Postgres', b: 'MySQL', pistas: ['gratis', 'tabla', 'admin'] },
  { a: 'Mongo', b: 'Redis', pistas: ['documento', 'rápido', 'memoria'] },
  { a: 'Oracle', b: 'SQL Server', pistas: ['caro', 'licencia', 'DBA'] },
  { a: 'React', b: 'Vue', pistas: ['hook', 'componente', 'estado'] },
  { a: 'Angular', b: 'Svelte', pistas: ['inyección', 'módulo', 'pesado'] },
  { a: 'Next', b: 'Nuxt', pistas: ['ruta', 'SSR', 'framework'] },
  { a: 'Node', b: 'Deno', pistas: ['callback', 'paquetes', 'asíncrono'] },
  { a: 'npm', b: 'yarn', pistas: ['lock', 'node_modules', 'instala'] },
  { a: 'pnpm', b: 'Bun', pistas: ['rápido', 'espacio', 'nuevo'] },
  { a: 'Docker', b: 'Podman', pistas: ['contenedor', 'imagen', 'compose'] },
  { a: 'Kubernetes', b: 'Nomad', pistas: ['pods', 'yaml', 'caos'] },
  { a: 'Terraform', b: 'Pulumi', pistas: ['infra', 'plan', 'apply'] },
  { a: 'Ansible', b: 'Chef', pistas: ['yaml', 'playbook', 'ssh'] },
  { a: 'Jenkins', b: 'GitHub Actions', pistas: ['pipeline', 'verde', 'plugin'] },
  { a: 'GitLab CI', b: 'CircleCI', pistas: ['yaml', 'minuto', 'cola'] },
  { a: 'AWS', b: 'Azure', pistas: ['factura', 'región', 'IAM'] },
  { a: 'GCP', b: 'Cloudflare', pistas: ['edge', 'gratis', 'región'] },
  { a: 'S3', b: 'Blob storage', pistas: ['cubo', 'público', 'foto'] },
  { a: 'Lambda', b: 'Cloud Functions', pistas: ['frío', 'evento', 'barato'] },
  { a: 'Linux', b: 'Windows', pistas: ['terminal', 'sudo', 'driver'] },
  { a: 'macOS', b: 'Ubuntu', pistas: ['notch', 'brew', 'bonito'] },
  { a: 'Vim', b: 'Emacs', pistas: ['salir', 'guerra', 'teclas'] },
  { a: 'VS Code', b: 'IntelliJ', pistas: ['extensión', 'gratis', 'ligero'] },
  { a: 'Cursor', b: 'Copilot', pistas: ['ia', 'tab', 'alucina'] },
  { a: 'ChatGPT', b: 'Claude', pistas: ['prompt', 'alucina', 'pega'] },
  { a: 'Stack Overflow', b: 'Reddit', pistas: ['copiar', 'cerrado', '2009'] },
  { a: 'Jira', b: 'Linear', pistas: ['ticket', 'tablero', 'lento'] },
  { a: 'Confluence', b: 'Notion', pistas: ['wiki', 'nadie', 'busca'] },
  { a: 'Figma', b: 'Sketch', pistas: ['diseño', 'componente', 'dev'] },
  { a: 'Postman', b: 'Insomnia', pistas: ['coleccion', 'token', '200'] },
  { a: 'REST', b: 'GraphQL', pistas: ['json', 'recurso', 'overfetch'] },
  { a: 'gRPC', b: 'WebSocket', pistas: ['binario', 'stream', 'protobuf'] },
  { a: 'JSON', b: 'XML', pistas: ['llaves', 'parse', 'feo'] },
  { a: 'YAML', b: 'TOML', pistas: ['indentar', 'rompe', 'config'] },
  { a: 'Markdown', b: 'AsciiDoc', pistas: ['readme', 'almohadilla', 'preview'] },
  { a: 'Regex', b: 'Parser', pistas: ['dos problemas', 'asterisco', 'stack'] },
  { a: 'Cache', b: 'CDN', pistas: ['viejo', 'invalida', 'borde'] },
  { a: 'Cookie', b: 'LocalStorage', pistas: ['aviso', 'sesión', 'borrar'] },
  { a: 'JWT', b: 'Sesión', pistas: ['token', 'expira', 'secreto'] },
  { a: 'OAuth', b: 'SAML', pistas: ['google', 'consentir', 'redirect'] },
  { a: 'HTTPS', b: 'TLS', pistas: ['candado', 'certificado', 'caduca'] },
  { a: 'DNS', b: 'DHCP', pistas: ['propaga', 'nombre', 'horas'] },
  { a: 'IP', b: 'MAC', pistas: ['dirección', 'ping', 'local'] },
  { a: 'VPN', b: 'SSH', pistas: ['túnel', 'casa', 'llave'] },
  { a: 'Firewall', b: 'WAF', pistas: ['puerto', 'bloquea', 'regla'] },
  { a: 'Load balancer', b: 'Reverse proxy', pistas: ['reparte', 'entrada', 'equilibrio'] },
  { a: 'Nginx', b: 'Apache', pistas: ['config', '443', 'viejo'] },
  { a: 'Kafka', b: 'RabbitMQ', pistas: ['cola', 'evento', 'lag'] },
  { a: 'Elasticsearch', b: 'Solr', pistas: ['busca', 'índice', 'lento'] },
  { a: 'Prometheus', b: 'Grafana', pistas: ['alerta', 'gráfico', 'scrape'] },
  { a: 'Sentry', b: 'Datadog', pistas: ['error', 'stack', 'caro'] },
  { a: 'Log', b: 'Métrica', pistas: ['grep', 'disco', 'ruido'] },
  { a: 'Trace', b: 'Span', pistas: ['lento', 'id', 'opentelemetry'] },
  { a: 'Unit test', b: 'E2E', pistas: ['rápido', 'mock', 'rojo'] },
  { a: 'Mock', b: 'Stub', pistas: ['falso', 'test', 'discutir'] },
  { a: 'TDD', b: 'BDD', pistas: ['primero', 'rojo', 'verde'] },
  { a: 'CI', b: 'CD', pistas: ['verde', 'merge', 'automático'] },
  { a: 'Feature flag', b: 'Dark launch', pistas: ['apaga', 'porcentaje', 'miedo'] },
  { a: 'Canary', b: 'Blue-green', pistas: ['pocos', 'probar', 'cambio'] },
  { a: 'Rollback', b: 'Hotfix', pistas: ['atrás', 'producción', 'noche'] },
  { a: 'Patch', b: 'Workaround', pistas: ['urgente', 'main', 'cherry'] },
  { a: 'Merge', b: 'Rebase', pistas: ['conflicto', 'historia', 'guerra'] },
  { a: 'Cherry-pick', b: 'Squash', pistas: ['commit', 'uno', 'limpia'] },
  { a: 'Pull request', b: 'Code review', pistas: ['comentarios', 'nit', 'lgtm'] },
  { a: 'Linter', b: 'Formatter', pistas: ['espacio', 'pelea', 'amarillo'] },
  { a: 'ESLint', b: 'Prettier', pistas: ['punto y coma', 'auto', 'config'] },
  { a: 'Webpack', b: 'Vite', pistas: ['bundle', 'lento', 'config'] },
  { a: 'Babel', b: 'SWC', pistas: ['transpile', 'viejo', 'rápido'] },
  { a: 'SSR', b: 'SSG', pistas: ['html', 'seo', 'render'] },
  { a: 'CSR', b: 'Hydration', pistas: ['cliente', 'parpadea', 'js'] },
  { a: 'SPA', b: 'MPA', pistas: ['ruta', 'una', 'history'] },
  { a: 'PWA', b: 'Nativa', pistas: ['instala', 'offline', 'tienda'] },
  { a: 'iOS', b: 'Android', pistas: ['tienda', 'review', 'permiso'] },
  { a: 'Flutter', b: 'React Native', pistas: ['cruzado', 'widget', 'casi'] },
  { a: 'Electron', b: 'Tauri', pistas: ['pesado', 'escritorio', 'chrome'] },
  { a: 'WebAssembly', b: 'ASM.js', pistas: ['rápido', 'binario', 'juego'] },
  { a: 'WebGL', b: 'WebGPU', pistas: ['gráfico', 'canvas', 'juego'] },
  { a: 'Canvas', b: 'SVG', pistas: ['píxel', 'dibuja', 'escala'] },
  { a: 'Cookie banner', b: 'Paywall', pistas: ['aceptar', 'todo', 'molesta'] },
  { a: 'Captcha', b: 'Turnstile', pistas: ['semáforos', 'robot', 'clicks'] },
  { a: '404', b: '500', pistas: ['no está', 'roto', 'página'] },
  { a: 'CORS', b: 'CSP', pistas: ['bloquea', 'cabecera', 'odio'] },
  { a: 'Null', b: 'Undefined', pistas: ['error', 'typeof', 'discutir'] },
  { a: 'NaN', b: 'Infinity', pistas: ['número', 'igual', 'trampa'] },
  { a: 'Off-by-one', b: 'Race condition', pistas: ['bucle', 'casi', 'hilo'] },
  { a: 'Memory leak', b: 'Deadlock', pistas: ['crece', 'nunca', 'hilos'] },
  { a: 'Segfault', b: 'Panic', pistas: ['peta', 'core', 'nativo'] },
];

export const INFORMATICA: Tema = {
  id: 'informatica',
  nombre: 'Informática',
  pinta: 'Para la mesa que se sabe la broma',
  terminos,
};
