import type { Tema, Termino } from './tipos';

const terminos: readonly Termino[] = [
  { a: 'Playa', b: 'Piscina', pistas: ['toalla', 'arena', 'agosto'] },
  { a: 'Aeropuerto', b: 'Estación', pistas: ['maleta', 'esperar', 'pantalla'] },
  { a: 'Hospital', b: 'Ambulatorio', pistas: ['cola', 'bata', 'olor'] },
  { a: 'Biblioteca', b: 'Librería', pistas: ['silencio', 'carné', 'estanterías'] },
  { a: 'Supermercado', b: 'Mercado', pistas: ['carro', 'lista', 'cola'] },
  { a: 'Montaña', b: 'Sierra', pistas: ['bota', 'niebla', 'cuesta'] },
  { a: 'Museo', b: 'Galería', pistas: ['no tocar', 'audioguía', 'entrada'] },
  { a: 'Camping', b: 'Hostal', pistas: ['tienda', 'barato', 'mosquitos'] },
  { a: 'Peluquería', b: 'Barbería', pistas: ['espejo', 'charla', 'poco'] },
  { a: 'Gasolinera', b: 'Área de servicio', pistas: ['noche', 'café', 'carretera'] },
  { a: 'Ascensor', b: 'Escalera', pistas: ['vecino', 'silencio', 'espejo'] },
  { a: 'Ferretería', b: 'Bazar', pistas: ['tornillo', 'de todo', 'señor'] },
  { a: 'Madrid', b: 'Barcelona', pistas: ['atasco', 'metro', 'turismo'] },
  { a: 'Valencia', b: 'Sevilla', pistas: ['luz', 'calor', 'naranja'] },
  { a: 'Bilbao', b: 'San Sebastián', pistas: ['lluvia', 'norte', 'pintxo'] },
  { a: 'Málaga', b: 'Alicante', pistas: ['palmera', 'paseo', 'suave'] },
  { a: 'Granada', b: 'Córdoba', pistas: ['patio', 'calor', 'cuesta'] },
  { a: 'Zaragoza', b: 'Valladolid', pistas: ['río', 'meseta', 'viento'] },
  { a: 'Toledo', b: 'Segovia', pistas: ['muralla', 'turista', 'cuesta'] },
  { a: 'Salamanca', b: 'Santiago', pistas: ['piedra', 'mochila', 'universidad'] },
  { a: 'Palma', b: 'Ibiza', pistas: ['isla', 'avión', 'verano'] },
  { a: 'Tenerife', b: 'Gran Canaria', pistas: ['volcán', 'eterno', 'viento'] },
  { a: 'Oviedo', b: 'León', pistas: ['frío', 'piedra', 'norte'] },
  { a: 'Santander', b: 'Gijón', pistas: ['bahía', 'humedad', 'norte'] },
  { a: 'A Coruña', b: 'Vigo', pistas: ['viento', 'mar', 'gallego'] },
  { a: 'Pamplona', b: 'Logroño', pistas: ['norte', 'vino', 'julio'] },
  { a: 'Murcia', b: 'Cartagena', pistas: ['calor', 'huerta', 'romana'] },
  { a: 'Badajoz', b: 'Cáceres', pistas: ['calor', 'llano', 'frontera'] },
  { a: 'Girona', b: 'Tarragona', pistas: ['piedra', 'costa', 'catalán'] },
  { a: 'Roma', b: 'París', pistas: ['turismo', 'fuente', 'cola'] },
  { a: 'Londres', b: 'Berlín', pistas: ['lluvia', 'autobús', 'frío'] },
  { a: 'Lisboa', b: 'Oporto', pistas: ['colina', 'tranvía', 'azulejo'] },
  { a: 'Venecia', b: 'Ámsterdam', pistas: ['canal', 'puente', 'foto'] },
  { a: 'Florencia', b: 'Praga', pistas: ['puente', 'turista', 'casco'] },
  { a: 'Atenas', b: 'Estambul', pistas: ['ruina', 'gato', 'caos'] },
  { a: 'Viena', b: 'Budapest', pistas: ['danubio', 'palacio', 'café'] },
  { a: 'Dublín', b: 'Edimburgo', pistas: ['lluvia', 'pub', 'verde'] },
  { a: 'Nueva York', b: 'Chicago', pistas: ['rascacielos', 'frío', 'taxi'] },
  { a: 'Tokio', b: 'Seúl', pistas: ['neón', 'metro', 'orden'] },
  { a: 'Buenos Aires', b: 'Ciudad de México', pistas: ['ruido', 'tarde', 'gente'] },
  { a: 'El Cairo', b: 'Marrakech', pistas: ['zoco', 'calor', 'polvo'] },
  { a: 'Dubái', b: 'Las Vegas', pistas: ['lujo', 'luz', 'falso'] },
  { a: 'Panadería', b: 'Pastelería', pistas: ['olor', 'cola', 'madrugón'] },
  { a: 'Carnicería', b: 'Charcutería', pistas: ['número', 'frío', 'señor'] },
  { a: 'Pescadería', b: 'Frutería', pistas: ['hielo', 'olor', 'mañana'] },
  { a: 'Farmacia', b: 'Parafarmacia', pistas: ['cruz', 'turno', 'cola'] },
  { a: 'Banco', b: 'Correos', pistas: ['número', 'espera', 'formulario'] },
  { a: 'Estanco', b: 'Loterías', pistas: ['cola', 'tabaco', 'esquina'] },
  { a: 'Kiosco', b: 'Tienda 24h', pistas: ['revista', 'chicle', 'esquina'] },
  { a: 'Centro comercial', b: 'Outlet', pistas: ['parking', 'sábado', 'frío'] },
  { a: 'Tienda de ropa', b: 'Zapatería', pistas: ['probador', 'talla', 'espejo'] },
  { a: 'Óptica', b: 'Joyería', pistas: ['cristal', 'caro', 'espera'] },
  { a: 'Floristería', b: 'Vivero', pistas: ['olor', 'agua', 'cumpleaños'] },
  { a: 'Taller', b: 'Concesionario', pistas: ['espera', 'café', 'factura'] },
  { a: 'Tintorería', b: 'Lavandería', pistas: ['olor', 'ticket', 'esperar'] },
  { a: 'Veterinaria', b: 'Protectora', pistas: ['olor', 'ladrido', 'cola'] },
  { a: 'Mercadona', b: 'Carrefour', pistas: ['carro', 'oferta', 'domingo'] },
  { a: 'Ikea', b: 'Leroy Merlin', pistas: ['perdido', 'domingo', 'pasillo'] },
  { a: 'El Corte Inglés', b: 'Primark', pistas: ['escaleras', 'sábado', 'bolsa'] },
  { a: 'Zara', b: 'H&M', pistas: ['talla', 'cola', 'básico'] },
  { a: 'McDonald\'s', b: 'Burger King', pistas: ['bandeja', 'niños', 'salsa'] },
  { a: 'Telepizza', b: 'Domino\'s', pistas: ['reparto', 'caja', 'noche'] },
  { a: '100 Montaditos', b: 'La Sureña', pistas: ['caña', 'barra', 'centro'] },
  { a: 'Cine', b: 'Teatro', pistas: ['entrada', 'butaca', 'palomitas'] },
  { a: 'Discoteca', b: 'Pub', pistas: ['cola', 'sello', 'noche'] },
  { a: 'Bar', b: 'Cafetería', pistas: ['barra', 'periódico', 'mañana'] },
  { a: 'Restaurante', b: 'Taberna', pistas: ['reserva', 'carta', 'cubierto'] },
  { a: 'Marisquería', b: 'Asador', pistas: ['mantel', 'domingo', 'caro'] },
  { a: 'Heladería', b: 'Churrería', pistas: ['cola', 'verano', 'servilleta'] },
  { a: 'Estadio', b: 'Pabellón', pistas: ['hinchada', 'acceso', 'ruido'] },
  { a: 'Plaza de toros', b: 'Hipódromo', pistas: ['grada', 'domingo', 'arena'] },
  { a: 'Zoo', b: 'Acuario', pistas: ['niños', 'olor', 'entrada'] },
  { a: 'Parque de atracciones', b: 'Parque temático', pistas: ['cola', 'foto', 'vértigo'] },
  { a: 'Casino', b: 'Bingo', pistas: ['humo', 'suerte', 'alfombra'] },
  { a: 'Polideportivo', b: 'Rocódromo', pistas: ['vestuario', 'sudor', 'taquilla'] },
  { a: 'Campo de golf', b: 'Club náutico', pistas: ['césped', 'caro', 'socio'] },
  { a: 'Bolera', b: 'Salón recreativo', pistas: ['ruido', 'fichas', 'adolescentes'] },
  { a: 'Escape room', b: 'Casa del terror', pistas: ['oscuro', 'grupo', 'grito'] },
  { a: 'Parque', b: 'Jardín', pistas: ['banco', 'sombra', 'paseo'] },
  { a: 'Plaza', b: 'Calle', pistas: ['palomas', 'paso', 'terraza'] },
  { a: 'Puerto', b: 'Muelle', pistas: ['grúa', 'sal', 'gaviota'] },
  { a: 'Faro', b: 'Acantilado', pistas: ['viento', 'foto', 'abajo'] },
  { a: 'Desierto', b: 'Duna', pistas: ['calor', 'arena', 'silencio'] },
  { a: 'Bosque', b: 'Selva', pistas: ['sombra', 'mosquito', 'camino'] },
  { a: 'Lago', b: 'Embalse', pistas: ['orilla', 'picnic', 'remo'] },
  { a: 'Río', b: 'Ría', pistas: ['orilla', 'puente', 'humedad'] },
  { a: 'Cascada', b: 'Garganta', pistas: ['humedad', 'foto', 'eco'] },
  { a: 'Volcán', b: 'Cráter', pistas: ['humo', 'cuesta', 'foto'] },
  { a: 'Cueva', b: 'Gruta', pistas: ['frío', 'casco', 'eco'] },
  { a: 'Isla', b: 'Península', pistas: ['ferry', 'viento', 'lejos'] },
  { a: 'Cabo', b: 'Golfo', pistas: ['viento', 'mapa', 'foto'] },
  { a: 'Valle', b: 'Cañón', pistas: ['carretera', 'eco', 'fondo'] },
  { a: 'Viñedo', b: 'Olivar', pistas: ['agosto', 'tierra', 'hilera'] },
  { a: 'Dehesa', b: 'Pradera', pistas: ['encina', 'sombra', 'ganado'] },
  { a: 'Cala', b: 'Caleta', pistas: ['agua', 'piedra', 'escondida'] },
  { a: 'Cocina', b: 'Comedor', pistas: ['olor', 'mesa', 'casa'] },
  { a: 'Dormitorio', b: 'Salón', pistas: ['cama', 'mando', 'siesta'] },
  { a: 'Baño', b: 'Aseo', pistas: ['cola', 'espejo', 'jabón'] },
  { a: 'Garaje', b: 'Trastero', pistas: ['cajas', 'polvo', 'abajo'] },
  { a: 'Ático', b: 'Sótano', pistas: ['escaleras', 'caro', 'luz'] },
  { a: 'Despacho', b: 'Oficina', pistas: ['silla', 'pantalla', 'silencio'] },
  { a: 'Aula', b: 'Laboratorio', pistas: ['pizarra', 'examen', 'pupitre'] },
  { a: 'Patio', b: 'Terraza', pistas: ['tendedero', 'vecino', 'verano'] },
  { a: 'Balcón', b: 'Mirador', pistas: ['foto', 'barandilla', 'viento'] },
  { a: 'Azotea', b: 'Tendedero', pistas: ['ropa', 'verano', 'vecina'] },
  { a: 'Pasillo', b: 'Recibidor', pistas: ['estrecho', 'perchero', 'luz'] },
  { a: 'Ayuntamiento', b: 'Diputación', pistas: ['sello', 'cola', 'mostrador'] },
  { a: 'Comisaría', b: 'Cuartel', pistas: ['uniforme', 'espera', 'parte'] },
  { a: 'Juzgado', b: 'Notaría', pistas: ['cola', 'papel', 'silencio'] },
  { a: 'Iglesia', b: 'Catedral', pistas: ['banco', 'silencio', 'vela'] },
  { a: 'Mezquita', b: 'Sinagoga', pistas: ['zapatos', 'silencio', 'rezo'] },
  { a: 'Cementerio', b: 'Tanatorio', pistas: ['flores', 'silencio', 'coche'] },
  { a: 'Universidad', b: 'Instituto', pistas: ['mochila', 'examen', 'pasillo'] },
  { a: 'Colegio', b: 'Guardería', pistas: ['patio', 'mochila', 'padres'] },
  { a: 'Hotel', b: 'Resort', pistas: ['llave', 'toalla', 'desayuno'] },
  { a: 'Parador', b: 'Casa rural', pistas: ['piedra', 'desayuno', 'silencio'] },
  { a: 'Albergue', b: 'Refugio', pistas: ['litera', 'mochila', 'madrugón'] },
  { a: 'Spa', b: 'Balneario', pistas: ['albornoz', 'susurro', 'agua'] },
  { a: 'Pueblo', b: 'Aldea', pistas: ['iglesia', 'silencio', 'bar'] },
  { a: 'Urbanización', b: 'Polígono', pistas: ['coche', 'vacío', 'naves'] },
  { a: 'Castillo', b: 'Fortaleza', pistas: ['cuesta', 'piedra', 'foto'] },
  { a: 'Palacio', b: 'Alcázar', pistas: ['cola', 'techo', 'foto'] },
  { a: 'Parking', b: 'Zona azul', pistas: ['tique', 'vueltas', 'multa'] },
  { a: 'Autopista', b: 'Carretera', pistas: ['peaje', 'aburrido', 'radio'] },
  { a: 'Metro', b: 'Tranvía', pistas: ['andén', 'agarrao', 'retraso'] },
  { a: 'Autobús', b: 'Taxi', pistas: ['espera', 'tarifa', 'asiento'] },
  { a: 'Prado', b: 'Reina Sofía', pistas: ['cola', 'audioguía', 'foto'] },
  { a: 'Retiro', b: 'Casa de Campo', pistas: ['barco', 'sombra', 'domingo'] },
  { a: 'Sagrada Familia', b: 'Alhambra', pistas: ['cola', 'foto', 'turista'] },
  { a: 'Gran Vía', b: 'Las Ramblas', pistas: ['gente', 'tiendas', 'foto'] },
  { a: 'Costa del Sol', b: 'Costa Brava', pistas: ['verano', 'carretera', 'turismo'] },
  { a: 'Pirineos', b: 'Picos de Europa', pistas: ['nieve', 'curva', 'vaca'] },
  { a: 'Teide', b: 'Mulhacén', pistas: ['altura', 'frío', 'coche'] },
  { a: 'Benidorm', b: 'Magaluf', pistas: ['inglés', 'verano', 'rascacielos'] },
  { a: 'Mercadillo', b: 'Rastro', pistas: ['domingo', 'ganga', 'calle'] },
  { a: 'Doñana', b: 'Ordesa', pistas: ['bota', 'aves', 'prohibido'] },
];

export const LUGARES: Tema = {
  id: 'lugares',
  nombre: 'Lugares',
  pinta: 'Sitios a los que se va y de los que se vuelve',
  terminos,
};
