import type { Tema, Termino } from './tipos';

const terminos: readonly Termino[] = [
  { a: 'Guitarra', b: 'Bajo', pistas: ['cuerdas', 'hoguera', 'seis'] },
  { a: 'Batería', b: 'Percusión', pistas: ['vecinos', 'baquetas', 'ruido'] },
  { a: 'Piano', b: 'Órgano', pistas: ['teclas', 'clases', 'blanco'] },
  { a: 'Concierto', b: 'Festival', pistas: ['entradas', 'pie', 'barra'] },
  { a: 'Karaoke', b: 'Coro', pistas: ['valor', 'micro', 'letra'] },
  { a: 'Auriculares', b: 'Altavoz', pistas: ['metro', 'cable', 'volumen'] },
  { a: 'Vinilo', b: 'Casete', pistas: ['nostalgia', 'girar', 'caro'] },
  { a: 'Villancico', b: 'Himno', pistas: ['diciembre', 'todos', 'pesado'] },
  { a: 'Flamenco', b: 'Copla', pistas: ['palmas', 'quejío', 'sur'] },
  { a: 'Reguetón', b: 'Trap', pistas: ['verano', 'discusión', 'repetido'] },
  { a: 'Ópera', b: 'Zarzuela', pistas: ['larga', 'palco', 'idioma'] },
  { a: 'Ensayo', b: 'Prueba de sonido', pistas: ['local', 'nadie', 'otra vez'] },
  { a: 'Violín', b: 'Viola', pistas: ['barbilla', 'arco', 'llora'] },
  { a: 'Chelo', b: 'Contrabajo', pistas: ['entre', 'grave', 'silla'] },
  { a: 'Saxofón', b: 'Clarinete', pistas: ['jazz', 'caña', 'curva'] },
  { a: 'Trompeta', b: 'Trombón', pistas: ['brillo', 'fanfarria', 'varas'] },
  { a: 'Flauta', b: 'Piccolo', pistas: ['agudo', 'colegio', 'agujeros'] },
  { a: 'Arpa', b: 'Lira', pistas: ['ángel', 'cuerdas', 'dedos'] },
  { a: 'Acordeón', b: 'Bandoneón', pistas: ['fuelle', 'tango', 'calle'] },
  { a: 'Ukelele', b: 'Mandolina', pistas: ['pequeña', 'verano', 'cuatro'] },
  { a: 'Banjo', b: 'Cítara', pistas: ['country', 'metal', 'rápido'] },
  { a: 'Armónica', b: 'Melódica', pistas: ['bolsillo', 'tren', 'blues'] },
  { a: 'Triángulo', b: 'Castañuelas', pistas: ['ding', 'colegio', 'mano'] },
  { a: 'Pandereta', b: 'Djembe', pistas: ['verano', 'círculo', 'sonajas'] },
  { a: 'Cajón flamenco', b: 'Bongos', pistas: ['sentado', 'palmas', 'caja'] },
  { a: 'Sintetizador', b: 'Sampler', pistas: ['perillas', 'ochenta', 'cable'] },
  { a: 'Mesa de mezclas', b: 'Controlador', pistas: ['palancas', 'DJ', 'luces'] },
  { a: 'Tocadiscos', b: 'Plato', pistas: ['DJ', 'scratch', 'agujas'] },
  { a: 'Amplificador', b: 'Pedal', pistas: ['botón', 'distorsión', 'suelo'] },
  { a: 'Púa', b: 'Ceja', pistas: ['bolsillo', 'plástico', 'rasgueo'] },
  { a: 'Atriles', b: 'Partitura', pistas: ['hojas', 'pasa', 'negro'] },
  { a: 'Metrónomo', b: 'Diapasón', pistas: ['tic', 'tempo', 'oreja'] },
  { a: 'Jazz', b: 'Blues', pistas: ['humo', 'improvisar', 'sótano'] },
  { a: 'Rock', b: 'Metal', pistas: ['pelo', 'ampli', 'grito'] },
  { a: 'Punk', b: 'Grunge', pistas: ['cresta', 'tres', 'rabia'] },
  { a: 'Pop', b: 'Disco', pistas: ['radio', 'pegadizo', 'verano'] },
  { a: 'Soul', b: 'Gospel', pistas: ['iglesia', 'voz', 'palmadas'] },
  { a: 'Salsa', b: 'Cumbia', pistas: ['pareja', 'cadera', 'latina'] },
  { a: 'Tango', b: 'Milonga', pistas: ['Buenos Aires', 'abrazo', 'rosa'] },
  { a: 'Samba', b: 'Bossa nova', pistas: ['Brasil', 'carnaval', 'suave'] },
  { a: 'Reggae', b: 'Ska', pistas: ['offbeat', 'Jamaica', 'verde'] },
  { a: 'Techno', b: 'House', pistas: ['cuatro', 'almacén', 'noche'] },
  { a: 'Trance', b: 'Drum and bass', pistas: ['manos', 'subida', 'noche'] },
  { a: 'Hip hop', b: 'Rap', pistas: ['rima', 'gorra', 'beat'] },
  { a: 'Fado', b: 'Rebetiko', pistas: ['Lisboa', 'saudade', 'toalla'] },
  { a: 'Sevillanas', b: 'Rumba', pistas: ['feria', 'cuatro', 'palmas'] },
  { a: 'Jota', b: 'Muñeira', pistas: ['Aragón', 'salto', 'regional'] },
  { a: 'Sardana', b: 'Trikitixa', pistas: ['círculo', 'Cataluña', 'manos'] },
  { a: 'Gaita', b: 'Txistu', pistas: ['Galicia', 'fuelle', 'fiesta'] },
  { a: 'Orquesta', b: 'Banda', pistas: ['frac', 'director', 'foso'] },
  { a: 'Big band', b: 'Combo', pistas: ['viento', 'swing', 'doce'] },
  { a: 'Cuarteto', b: 'Trío', pistas: ['cámara', 'sillas', 'íntimo'] },
  { a: 'Solista', b: 'Acompañante', pistas: ['delante', 'luz', 'cadencia'] },
  { a: 'Director', b: 'Concertino', pistas: ['batuta', 'espalda', 'frac'] },
  { a: 'Soprano', b: 'Mezzosoprano', pistas: ['aguda', 'aria', 'vestido'] },
  { a: 'Tenor', b: 'Barítono', pistas: ['pañuelo', 'agudo', 'héroe'] },
  { a: 'Bajo profundo', b: 'Contralto', pistas: ['grave', 'suelo', 'raro'] },
  { a: 'Aria', b: 'Recitativo', pistas: ['para', 'brillo', 'aplauso'] },
  { a: 'Obertura', b: 'Finale', pistas: ['antes', 'telón', 'todos'] },
  { a: 'Bis', b: 'Propina', pistas: ['otra', 'aplauso', 'luz'] },
  { a: 'Gira', b: 'Residencia', pistas: ['autocar', 'ciudades', 'camiseta'] },
  { a: 'Telonero', b: 'Headliner', pistas: ['antes', 'pocos', 'prueba'] },
  { a: 'Backstage', b: 'Foso', pistas: ['pase', 'nervios', 'agua'] },
  { a: 'Camerino', b: 'Rider', pistas: ['espejo', 'lista', 'gominolas'] },
  { a: 'Merchandising', b: 'Vinilo deluxe', pistas: ['camiseta', 'cola', 'caro'] },
  { a: 'Spotify', b: 'YouTube Music', pistas: ['lista', 'shuffle', 'anuncio'] },
  { a: 'Walkman', b: 'Discman', pistas: ['cinta', 'noventa', 'skip'] },
  { a: 'MP3', b: 'WAV', pistas: ['kilos', 'calidad', 'pendrive'] },
  { a: 'Compact disc', b: 'Minidisc', pistas: ['cara', 'laser', 'estuche'] },
  { a: 'Radio 3', b: 'Los 40', pistas: ['raro', 'noche', 'indie'] },
  { a: 'Eurovisión', b: 'Benidorm Fest', pistas: ['doce', 'televoto', 'lentejuelas'] },
  { a: 'OT', b: 'La Voz Kids', pistas: ['academia', 'directo', 'sillón'] },
  { a: 'Coachella', b: 'Glastonbury', pistas: ['barro', 'selfie', 'desierto'] },
  { a: 'Primavera Sound', b: 'Sónar', pistas: ['Barcelona', 'indie', 'calor'] },
  { a: 'Mad Cool', b: 'FIB', pistas: ['Madrid', 'polvo', 'Benicàssim'] },
  { a: 'Viña Rock', b: 'Resurrection', pistas: ['Villarrobledo', 'pelo', 'calor'] },
  { a: 'Rosalía', b: 'Bad Gyal', pistas: ['trenza', 'uñas', 'Barcelona'] },
  { a: 'Tablado', b: 'Peña', pistas: ['tablao', 'noche', 'jerez'] },
  { a: 'Camarón', b: 'Paco de Lucía', pistas: ['gitano', 'Jerez', 'duende'] },
  { a: 'Palos', b: 'Compás', pistas: ['soleá', 'contar', 'palmas'] },
  { a: 'Extremoduro', b: 'Platero y Tú', pistas: ['extremo', 'bar', 'rasposo'] },
  { a: 'Toque', b: 'Baile', pistas: ['uñas', 'duende', 'mano'] },
  { a: 'Letra', b: 'Estribillo', pistas: ['estrofa', 'todos', 'pega'] },
  { a: 'Puente', b: 'Intro', pistas: ['medio', 'cambia', 'antes del estribillo'] },
  { a: 'Solo', b: 'Riff', pistas: ['guitarra', 'cara', 'memorable'] },
  { a: 'Cover', b: 'Remix', pistas: ['otra', 'versión', 'boda'] },
  { a: 'Estopa', b: 'El Canto del Loco', pistas: ['barrio', 'dos', 'Cornellà'] },
  { a: 'Playback', b: 'Directo', pistas: ['labios', 'mentira', 'tele'] },
  { a: 'Afinar', b: 'Templar', pistas: ['antes', 'clavijas', 'oreja'] },
  { a: 'Desafinado', b: 'Fuera de ritmo', pistas: ['duele', 'karaoke', 'tío'] },
  { a: 'Mecano', b: 'La Oreja de Van Gogh', pistas: ['ochenta', 'synth', 'famoso'] },
  { a: 'Pentagrama', b: 'Tablatura', pistas: ['cinco', 'puntos', 'leer'] },
  { a: 'Clave de sol', b: 'Clave de fa', pistas: ['dibujo', 'agudo', 'principio'] },
  { a: 'Sostenido', b: 'Bemol', pistas: ['almohadilla', 'sube', 'negro'] },
  { a: 'Compás de 4/4', b: 'Compás de 3/4', pistas: ['vals', 'contar', 'pie'] },
  { a: 'Joaquín Sabina', b: 'Serrat', pistas: ['gafas', 'versos', 'viejo'] },
  { a: 'Crescendo', b: 'Diminuendo', pistas: ['sube', 'pelo', 'final'] },
  { a: 'Staccato', b: 'Legato', pistas: ['picado', 'corto', 'puntos'] },
  { a: 'Vibrato', b: 'Tremolo', pistas: ['dedo', 'tiembla', 'onda'] },
  { a: 'Distorsión', b: 'Reverb', pistas: ['sucio', 'iglesia', 'eco'] },
  { a: 'Fito', b: 'Marea', pistas: ['bar', 'norte', 'rasposo'] },
  { a: 'Ecualizador', b: 'Compresor', pistas: ['graves', 'perillas', 'estudio'] },
  { a: 'Autotune', b: 'Vocoder', pistas: ['robot', 'trampa', 'moderno'] },
  { a: 'Click', b: 'Loop', pistas: ['auricular', 'batería', 'repite'] },
];

export const MUSICA: Tema = {
  id: 'musica',
  nombre: 'Música',
  pinta: 'Sin tararear, que eso es hacer trampa',
  terminos,
};
