import type { Tema, Termino } from './tipos';

const terminos: readonly Termino[] = [
  { a: 'Reunión', b: 'Llamada', pistas: ['correo', 'calendario', 'larga'] },
  { a: 'Máquina de café', b: 'Fuente de agua', pistas: ['pasillo', 'excusa', 'monedas'] },
  { a: 'Jefe', b: 'Cliente', pistas: ['prisa', 'cambia', 'despacho'] },
  { a: 'Vacaciones', b: 'Puente', pistas: ['agosto', 'cola', 'planilla'] },
  { a: 'Impresora', b: 'Escáner', pistas: ['atasco', 'nunca', 'papel'] },
  { a: 'Nómina', b: 'Factura', pistas: ['fin de mes', 'menos', 'PDF'] },
  { a: 'Retrospectiva', b: 'Daily', pistas: ['pizarra', 'nadie', 'quince'] },
  { a: 'Teletrabajo', b: 'Presencial', pistas: ['pijama', 'cámara', 'discusión'] },
  { a: 'Ascenso', b: 'Aumento', pistas: ['año', 'promesa', 'firma'] },
  { a: 'Fichar', b: 'Turno', pistas: ['reloj', 'entrada', 'ley'] },
  { a: 'Becario', b: 'Junior', pistas: ['barato', 'preguntas', 'café'] },
  { a: 'Excel', b: 'Base de datos', pistas: ['celdas', 'macro', 'todo'] },
  { a: 'PowerPoint', b: 'Keynote', pistas: ['diapositiva', 'animación', 'aburrido'] },
  { a: 'Word', b: 'Google Docs', pistas: ['márgenes', 'control', 'cambios'] },
  { a: 'Outlook', b: 'Gmail', pistas: ['bandeja', 'urgente', 'copia'] },
  { a: 'Teams', b: 'Slack', pistas: ['canal', 'mute', 'hilo'] },
  { a: 'Zoom', b: 'Meet', pistas: ['enlace', 'fondo', 'estás mute'] },
  { a: 'Calendario', b: 'Agenda', pistas: ['invita', 'solapa', 'libre'] },
  { a: 'Sala de reuniones', b: 'Cabina', pistas: ['reserva', 'pantalla', 'fría'] },
  { a: 'Open space', b: 'Despacho', pistas: ['ruido', 'cascos', 'planta'] },
  { a: 'Hot desk', b: 'Sitio fijo', pistas: ['mochila', 'guerra', 'monitor'] },
  { a: 'Parking', b: 'Abono transporte', pistas: ['plaza', 'tarde', 'caro'] },
  { a: 'Cantina', b: 'Tupper', pistas: ['microondas', 'cola', 'menú'] },
  { a: 'Afterwork', b: 'Cena de empresa', pistas: ['viernes', 'una', 'el jefe'] },
  { a: 'Team building', b: 'Away day', pistas: ['kayak', 'confianza', 'foto'] },
  { a: 'Formación', b: 'Webinar', pistas: ['obligatoria', 'certificado', 'mute'] },
  { a: 'Evaluación', b: 'Feedback 360', pistas: ['año', 'casilla', 'mejora'] },
  { a: 'Objetivos', b: 'KPIs', pistas: ['número', 'tablero', 'verde'] },
  { a: 'OKR', b: 'Bonus', pistas: ['ambicioso', 'porcentaje', 'marzo'] },
  { a: 'Presupuesto', b: 'Forecast', pistas: ['excel', 'recorte', 'Q3'] },
  { a: 'Deadline', b: 'Hito', pistas: ['ayer', 'rojo', 'imposible'] },
  { a: 'Retraso', b: 'Bloqueante', pistas: ['depende', 'otro', 'espera'] },
  { a: 'Prioridad', b: 'Urgente', pistas: ['todo', 'rojo', 'ahora'] },
  { a: 'Backlog', b: 'Inbox', pistas: ['crece', 'nunca', 'orden'] },
  { a: 'Sprint', b: 'Kanban', pistas: ['dos semanas', 'tablero', 'velo'] },
  { a: 'Planning', b: 'Refinamiento', pistas: ['puntos', 'discusión', 'infinito'] },
  { a: 'Demo', b: 'Review', pistas: ['pantalla', 'funciona', 'preguntas'] },
  { a: 'Standup', b: 'Sync', pistas: ['quince', 'ayer', 'bloqueos'] },
  { a: 'Postmortem', b: 'Autopsia', pistas: ['caída', 'sin culpa', 'acción'] },
  { a: 'Incidencia', b: 'Ticket', pistas: ['rojo', 'número', 'abre'] },
  { a: 'SLA', b: 'OLA', pistas: ['horas', 'contrato', 'multa'] },
  { a: 'Guardia', b: 'On-call', pistas: ['móvil', 'finde', 'alerta'] },
  { a: 'Desconexión digital', b: 'Out of office', pistas: ['ley', 'verano', 'mentira'] },
  { a: 'Baja', b: 'Permiso', pistas: ['parte', 'médico', 'días'] },
  { a: 'ERTE', b: 'ERE', pistas: ['2020', 'carta', 'miedo'] },
  { a: 'Convenio', b: 'Contrato', pistas: ['sector', 'letra', 'firma'] },
  { a: 'Indefinido', b: 'Temporal', pistas: ['suerte', 'prueba', 'renueva'] },
  { a: 'Freelance', b: 'Autónomo', pistas: ['factura', 'cuota', 'libertad'] },
  { a: 'Consultora', b: 'In-house', pistas: ['tarifa', 'hotel', 'externo'] },
  { a: 'Outsourcing', b: 'Nearshore', pistas: ['barato', 'otro', 'zona'] },
  { a: 'Offboarding', b: 'Onboarding', pistas: ['portátil', 'alta', 'tour'] },
  { a: 'Buddy', b: 'Mentor', pistas: ['nuevos', 'preguntas', 'café'] },
  { a: 'RRHH', b: 'People', pistas: ['baja', 'encuesta', 'nombre nuevo'] },
  { a: 'Compliance', b: 'Legal', pistas: ['curso', 'acepto', 'aburrido'] },
  { a: 'GDPR', b: 'LOPD', pistas: ['cookies', 'casilla', 'multa'] },
  { a: 'Código ético', b: 'Conflicto de interés', pistas: ['regalo', 'curso', 'firma'] },
  { a: 'Dietas', b: 'Kilometraje', pistas: ['excel', 'viaje', 'tique'] },
  { a: 'Nota de gastos', b: 'Liquidación', pistas: ['tique', 'mes', 'retraso'] },
  { a: 'Tarjeta de empresa', b: 'Anticipo', pistas: ['límite', 'cena', 'pide'] },
  { a: 'Viaje de trabajo', b: 'Feria', pistas: ['maleta', 'stand', 'jet lag'] },
  { a: 'Hotel de empresa', b: 'Airbnb corporativo', pistas: ['barato', 'lejos', 'wifi'] },
  { a: 'Sala VIP', b: 'Priority pass', pistas: ['aeropuerto', 'zumos', 'enchufe'] },
  { a: 'Parking de visitas', b: 'Recepción', pistas: ['tarjeta', 'espera', 'sofá'] },
  { a: 'Tarjeta de acceso', b: 'Llavero', pistas: ['bip', 'olvidada', 'torniquete'] },
  { a: 'Lockers', b: 'Taquilla', pistas: ['candado', 'chaqueta', 'gimnasio'] },
  { a: 'Gimnasio de empresa', b: 'Fruta', pistas: ['beneficio', 'enero', 'nadie'] },
  { a: 'Seguro médico', b: 'Cheque restaurante', pistas: ['beneficio', 'app', 'límites'] },
  { a: 'Stock options', b: 'Phantom shares', pistas: ['quizá', 'salida', 'letra'] },
  { a: 'Clawback', b: 'Malus', pistas: ['bonus', 'devuelve', 'letra'] },
  { a: 'NDA', b: 'No compete', pistas: ['secreto', 'firma', 'abogado'] },
  { a: 'Pacto de socios', b: 'Cap table', pistas: ['porcentaje', 'ronda', 'excel'] },
  { a: 'Ronda de inversión', b: 'Due diligence', pistas: ['presentación', 'preguntas', 'nervios'] },
  { a: 'Pitch', b: 'Elevator pitch', pistas: ['minutos', 'problema', 'slide'] },
  { a: 'Stakeholder', b: 'Sponsor', pistas: ['influye', 'decide', 'arriba'] },
  { a: 'Steering', b: 'Comité', pistas: ['mensual', 'slides', 'sí'] },
  { a: 'Acta', b: 'Minuta', pistas: ['nadie', 'acciones', 'correo'] },
  { a: 'Acción', b: 'Owner', pistas: ['nombre', 'fecha', 'olvida'] },
  { a: 'Riesgo', b: 'Dependencia', pistas: ['ámbar', 'matriz', 'mitiga'] },
  { a: 'Alcance', b: 'Scope creep', pistas: ['crece', 'no', 'cambio'] },
  { a: 'Cambio', b: 'RFC', pistas: ['formulario', 'comité', 'espera'] },
  { a: 'Go live', b: 'Freeze', pistas: ['viernes', 'miedo', 'rollback'] },
  { a: 'UAT', b: 'QA', pistas: ['usuario', 'falla', 'entorno'] },
  { a: 'Staging', b: 'Producción', pistas: ['casi', 'datos', 'cuidado'] },
  { a: 'VPN', b: 'Proxy', pistas: ['casa', 'lento', 'conecta'] },
  { a: 'SSO', b: '2FA', pistas: ['una', 'móvil', 'código'] },
  { a: 'Password manager', b: 'Post-it', pistas: ['caja', 'olvidada', 'pantalla'] },
  { a: 'Portátil', b: 'Docking', pistas: ['mochila', 'cable', 'pesado'] },
  { a: 'Monitor extra', b: 'Portátil cerrado', pistas: ['cuello', 'lujo', 'dos'] },
  { a: 'Silla ergonómica', b: 'Pelota', pistas: ['espalda', 'cara', 'espera'] },
  { a: 'Soporte lumbar', b: 'Reposapiés', pistas: ['catalogo', 'pide', 'RRHH'] },
  { a: 'Cascos', b: 'Tapones', pistas: ['open', 'mundo', 'no'] },
  { a: 'Planta', b: 'Cubículo', pistas: ['ruido', 'separador', 'foto'] },
  { a: 'Pizarra', b: 'Post-its', pistas: ['rotulador', 'se seco', 'idea'] },
  { a: 'Rotulador que no pinta', b: 'Tinta', pistas: ['siempre', 'tapa', 'negro'] },
  { a: 'Grapadora', b: 'Taladradora', pistas: ['atasco', 'cajón', 'huecos'] },
  { a: 'Quitagrapas', b: 'Tipex', pistas: ['sangre', 'blanco', 'error'] },
  { a: 'Carpeta', b: 'Archivador', pistas: ['lomo', 'año', 'polvo'] },
  { a: 'Destructora', b: 'Confidencial', pistas: ['tira', 'ruido', 'RGPD'] },
  { a: 'Sello', b: 'Firma digital', pistas: ['tinta', 'fecha', 'certificado'] },
  { a: 'Mochila de portátil', b: 'Riñonera corporativa', pistas: ['logo', 'regalo', 'feria'] },
  { a: 'Bolígrafo de feria', b: 'USB de feria', pistas: ['logo', 'no escribe', 'cajón'] },
  { a: 'Mug de empresa', b: 'Botella de cristal', pistas: ['logo', 'lavavajillas', 'borde'] },
  { a: 'Lanyard', b: 'Tarjeta identificativa', pistas: ['cuello', 'foto', 'torno'] },
];

export const OFICINA: Tema = {
  id: 'oficina',
  nombre: 'Oficina',
  pinta: 'Lo que pasa entre las nueve y las seis',
  terminos,
};
