import type { Tema, Termino } from './tipos';

/** Títulos de artículo. Hay que explicarlos sin decirlos. */
const terminos: readonly Termino[] = [
  { a: 'Agujero negro', b: 'Estrella de neutrones', pistas: ['denso', 'espacio', 'colapso'] },
  { a: 'Fotosíntesis', b: 'Respiración celular', pistas: ['gases', 'célula', 'ciclo'] },
  { a: 'ADN', b: 'ARN', pistas: ['hélice', 'código', 'célula'] },
  { a: 'Relatividad', b: 'Mecánica cuántica', pistas: ['raro', 'físico', 'siglo XX'] },
  { a: 'Teorema de Pitágoras', b: 'Teorema de Tales', pistas: ['triángulo', 'escuela', 'griego'] },
  { a: 'Átomo', b: 'Molécula', pistas: ['pequeño', 'enlaces', 'químico'] },
  { a: 'Electrón', b: 'Protón', pistas: ['carga', 'núcleo', 'pequeño'] },
  { a: 'Big Bang', b: 'Inflación cósmica', pistas: ['origen', 'expansión', 'tiempo'] },
  { a: 'Evolución', b: 'Selección natural', pistas: ['especies', 'cambio', 'fósil'] },
  { a: 'Gravedad', b: 'Magnetismo', pistas: ['fuerza', 'campo', 'invisible'] },
  { a: 'Mitosis', b: 'Meiosis', pistas: ['división', 'célula', 'cromosoma'] },
  { a: 'Vacuna', b: 'Antibiótico', pistas: ['pinchazo', 'defensa', 'bata'] },
  { a: 'Virus', b: 'Bacteria', pistas: ['contagio', 'micro', 'enfermo'] },
  { a: 'Tabla periódica', b: 'Número atómico', pistas: ['elementos', 'casillas', 'químico'] },
  { a: 'Entropía', b: 'Energía libre', pistas: ['desorden', 'físico', 'calor'] },
  { a: 'Agujero de ozono', b: 'Efecto invernadero', pistas: ['atmósfera', 'polar', 'aviso'] },
  { a: 'Tectónica de placas', b: 'Deriva continental', pistas: ['terremoto', 'mapa', 'lento'] },
  { a: 'Superconductividad', b: 'Semiconductor', pistas: ['frío', 'corriente', 'chip'] },
  { a: 'Radiactividad', b: 'Fisión nuclear', pistas: ['peligro', 'verde', 'central'] },
  { a: 'Número pi', b: 'Número e', pistas: ['infinito', 'raro', 'clase'] },
  { a: 'Fractal', b: 'Teoría del caos', pistas: ['repetido', 'raro', 'dibujo'] },
  { a: 'Algoritmo', b: 'Programa informático', pistas: ['pasos', 'ordenador', 'receta'] },
  { a: 'Inteligencia artificial', b: 'Aprendizaje automático', pistas: ['robot', 'datos', 'moda'] },
  { a: 'Internet', b: 'World Wide Web', pistas: ['cable', 'página', 'mundial'] },
  { a: 'Bitcoin', b: 'Cadena de bloques', pistas: ['dinero', 'minar', 'clave'] },
  { a: 'Realidad virtual', b: 'Realidad aumentada', pistas: ['gafas', 'falso', 'juego'] },
  { a: 'Célula', b: 'Núcleo celular', pistas: ['micro', 'vivo', 'pared'] },
  { a: 'Sistema solar', b: 'Vía Láctea', pistas: ['giro', 'noche', 'enorme'] },
  { a: 'Revolución Francesa', b: 'Revolución Rusa', pistas: ['cabezas', 'invierno', 'pueblo'] },
  { a: 'Guerra Fría', b: 'Cortina de hierro', pistas: ['dos bandos', 'espías', 'muro'] },
  { a: 'Primera Guerra Mundial', b: 'Segunda Guerra Mundial', pistas: ['trincheras', 'mapa', 'siglo XX'] },
  { a: 'Reconquista', b: 'Cruzadas', pistas: ['castillo', 'fe', 'siglos'] },
  { a: 'Caída de Roma', b: 'Caída de Constantinopla', pistas: ['imperio', 'murallas', 'saqueo'] },
  { a: 'Revolución Industrial', b: 'Revolución Digital', pistas: ['fábrica', 'cambio', 'máquina'] },
  { a: 'Mayo del 68', b: 'Primavera de Praga', pistas: ['estudiantes', 'carteles', 'tanques'] },
  { a: 'Guerra Civil Española', b: 'Guerra de la Independencia Española', pistas: ['trincheras', 'pueblo', 'hambre'] },
  { a: 'Transición española', b: '15-M', pistas: ['plaza', 'cambio', 'pancarta'] },
  { a: 'Tratado de Versalles', b: 'Congreso de Viena', pistas: ['mapa', 'firmas', 'paz'] },
  { a: 'Imperio romano', b: 'Imperio otomano', pistas: ['conquistas', 'siglos', 'frontera'] },
  { a: 'Edad Media', b: 'Renacimiento', pistas: ['castillo', 'fe', 'siglos'] },
  { a: 'Ilustración', b: 'Romanticismo', pistas: ['salón', 'sentimiento', 'siglo'] },
  { a: 'Inquisición', b: 'Caza de brujas', pistas: ['fuego', 'miedo', 'acusado'] },
  { a: 'Peste negra', b: 'Gripe española', pistas: ['muertos', 'mascarilla', 'oleada'] },
  { a: 'Apolo 11', b: 'Sputnik', pistas: ['cohete', 'bandera', 'carrera'] },
  { a: 'Chernóbil', b: 'Fukushima', pistas: ['central', 'nube', 'abandono'] },
  { a: 'Pompeya', b: 'Herculano', pistas: ['ceniza', 'ruinas', 'sorpresa'] },
  { a: 'Waterloo', b: 'Trafalgar', pistas: ['general', 'mapa', 'derrota'] },
  { a: 'Muro de Berlín', b: 'Puerta de Brandeburgo', pistas: ['hormigón', 'adiós', 'alemanes'] },
  { a: 'Descubrimiento de América', b: 'Primera circunnavegación', pistas: ['barco', 'mapa', 'siglo XVI'] },
  { a: 'Independencia de Estados Unidos', b: 'Revolución haitiana', pistas: ['colonia', 'disparos', 'libertad'] },
  { a: '11-S', b: '11-M', pistas: ['noticias', 'miedo', 'aniversario'] },
  { a: 'Desembarco de Normandía', b: 'Ataque a Pearl Harbor', pistas: ['playa', 'sorpresa', 'aliados'] },
  { a: 'Partenón', b: 'Coliseo', pistas: ['ruinas', 'turismo', 'antiguo'] },
  { a: 'Machu Picchu', b: 'Chichén Itzá', pistas: ['piedra', 'selva', 'turistas'] },
  { a: 'Torre Eiffel', b: 'Estatua de la Libertad', pistas: ['foto', 'hierro', 'postal'] },
  { a: 'Pirámides de Giza', b: 'Gran Esfinge', pistas: ['arena', 'piedra', 'turistas'] },
  { a: 'Stonehenge', b: 'Moái', pistas: ['piedra', 'misterio', 'foto'] },
  { a: 'Alhambra', b: 'Mezquita de Córdoba', pistas: ['arco', 'azulejo', 'patio'] },
  { a: 'Sagrada Familia', b: 'Torre de Pisa', pistas: ['andamios', 'foto', 'obras'] },
  { a: 'Gran Muralla China', b: 'Muro de Adriano', pistas: ['piedra', 'frontera', 'andar'] },
  { a: 'Everest', b: 'K2', pistas: ['frío', 'cola', 'oxígeno'] },
  { a: 'Amazonas', b: 'Nilo', pistas: ['caudal', 'barco', 'largo'] },
  { a: 'Sáhara', b: 'Gobi', pistas: ['arena', 'camello', 'infinito'] },
  { a: 'Océano Pacífico', b: 'Océano Atlántico', pistas: ['sal', 'barco', 'enorme'] },
  { a: 'Mar Mediterráneo', b: 'Mar Caribe', pistas: ['playa', 'sal', 'vacaciones'] },
  { a: 'Islas Canarias', b: 'Islas Baleares', pistas: ['vuelo', 'playa', 'puente'] },
  { a: 'Camino de Santiago', b: 'Ruta de la Seda', pistas: ['mochila', 'etapas', 'leyenda'] },
  { a: 'Canal de Suez', b: 'Canal de Panamá', pistas: ['atajo', 'barco', 'peaje'] },
  { a: 'Cataratas del Niágara', b: 'Iguazú', pistas: ['ruido', 'chubasquero', 'foto'] },
  { a: 'Kilimanjaro', b: 'Monte Fuji', pistas: ['cima', 'foto', 'simétrico'] },
  { a: 'Antártida', b: 'Ártico', pistas: ['frío', 'blanco', 'hielo'] },
  { a: 'Venus (planeta)', b: 'Marte (planeta)', pistas: ['vecino', 'telescopio', 'nombre'] },
  { a: 'Luna', b: 'Titán (satélite)', pistas: ['satélite', 'frío', 'sonda'] },
  { a: 'Sol', b: 'Próxima Centauri', pistas: ['estrella', 'luz', 'cerca'] },
  { a: 'Guernica', b: 'Las Meninas', pistas: ['museo', 'gris', 'famoso'] },
  { a: 'Don Quijote', b: 'La Celestina', pistas: ['castellano', 'trágico', 'clásico'] },
  { a: 'La Gioconda', b: 'El Grito', pistas: ['museo', 'famoso', 'robado'] },
  { a: 'Hamlet', b: 'Macbeth', pistas: ['corona', 'duda', 'muerto'] },
  { a: 'La Odisea', b: 'La Ilíada', pistas: ['barco', 'dioses', 'verso'] },
  { a: 'Cien años de soledad', b: 'Rayuela', pistas: ['saga', 'pueblo', 'salto'] },
  { a: 'La Divina Comedia', b: 'El Paraíso perdido', pistas: ['infierno', 'verso', 'ángel'] },
  { a: '1984 (novela)', b: 'Un mundo feliz', pistas: ['vigilancia', 'futuro', 'prohibido'] },
  { a: 'El Señor de los Anillos', b: 'Las crónicas de Narnia', pistas: ['mapa', 'mago', 'niño'] },
  { a: 'Harry Potter', b: 'El hobbit', pistas: ['magia', 'gafas', 'mapa'] },
  { a: 'Carmen (ópera)', b: 'La traviata', pistas: ['soprano', 'drama', 'palco'] },
  { a: 'El lago de los cisnes', b: 'El cascanueces', pistas: ['tutú', 'navidad', 'ruso'] },
  { a: 'La persistencia de la memoria', b: 'El jardín de las delicias', pistas: ['raro', 'museo', 'sueño'] },
  { a: 'Capilla Sixtina', b: 'El Juicio Final', pistas: ['techo', 'cuello', 'Roma'] },
  { a: 'La noche estrellada', b: 'Los girasoles', pistas: ['brocha', 'loco', 'amarillo'] },
  { a: 'Las cuatro estaciones', b: 'Novena de Beethoven', pistas: ['palco', 'muy oído', 'clásico'] },
  { a: 'Star Wars', b: 'Star Trek', pistas: ['nave', 'galaxia', 'friki'] },
  { a: 'La Regenta', b: 'Fortunata y Jacinta', pistas: ['provincia', 'marido', 'folletín'] },
  { a: 'Luces de bohemia', b: 'Esperando a Godot', pistas: ['raro', 'escenario', 'absurdo'] },
  { a: 'La boda de Fígaro', b: 'Don Giovanni', pistas: ['palco', 'enredo', 'italiano'] },
  { a: 'Imprenta', b: 'Papel', pistas: ['libro', 'tinta', 'copia'] },
  { a: 'Teléfono', b: 'Telégrafo', pistas: ['cable', 'mensaje', 'timbre'] },
  { a: 'Radio', b: 'Televisión', pistas: ['antena', 'salón', 'anuncios'] },
  { a: 'Avión', b: 'Helicóptero', pistas: ['ruido', 'asiento', 'cielo'] },
  { a: 'Automóvil', b: 'Bicicleta', pistas: ['ruedas', 'atasco', 'casco'] },
  { a: 'Brújula', b: 'Astrolabio', pistas: ['norte', 'barco', 'aguja'] },
  { a: 'Pólvora', b: 'Dinamita', pistas: ['boom', 'chino', 'palo'] },
  { a: 'Penicilina', b: 'Aspirina', pistas: ['pastilla', 'milagro', 'bata'] },
  { a: 'Microscopio', b: 'Telescopio', pistas: ['lente', 'lejos', 'laboratorio'] },
  { a: 'Máquina de vapor', b: 'Motor de combustión', pistas: ['pistón', 'fábrica', 'humo'] },
  { a: 'Bombilla', b: 'Vela', pistas: ['luz', 'apagón', 'calor'] },
  { a: 'GPS', b: 'Radar', pistas: ['pantalla', 'pitido', 'perdido'] },
  { a: 'Fotografía', b: 'Cine', pistas: ['clic', 'revelar', 'pose'] },
  { a: 'Submarino', b: 'Portaaviones', pistas: ['acero', 'flota', 'profundo'] },
  { a: 'Democracia', b: 'República', pistas: ['voto', 'plaza', 'discurso'] },
  { a: 'Capitalismo', b: 'Comunismo', pistas: ['fábrica', 'debate', 'dinero'] },
  { a: 'Anarquismo', b: 'Liberalismo', pistas: ['estado', 'manifiesto', 'libertad'] },
  { a: 'Feminismo', b: 'Sufragismo', pistas: ['voto', 'pancarta', 'siglo'] },
  { a: 'Ateísmo', b: 'Agnosticismo', pistas: ['duda', 'iglesia', 'debate'] },
  { a: 'Budismo', b: 'Hinduismo', pistas: ['templo', 'reencarnación', 'Asia'] },
  { a: 'Islam', b: 'Cristianismo', pistas: ['templo', 'libro', 'fe'] },
  { a: 'Mitología griega', b: 'Mitología nórdica', pistas: ['dioses', 'rayo', 'epopeya'] },
  { a: 'Utopía', b: 'Distopía', pistas: ['futuro', 'sociedad', 'libro'] },
  { a: 'Psicoanálisis', b: 'Conductismo', pistas: ['diván', 'rata', 'complejo'] },
  { a: 'Inflación', b: 'Deflación', pistas: ['precios', 'noticia', 'compra'] },
  { a: 'Huelga', b: 'Manifestación', pistas: ['pancarta', 'parar', 'megáfono'] },
];

export const WIKIPEDIA: Tema = {
  id: 'wikipedia',
  nombre: 'Wikipedia',
  pinta: 'El título de la página. Explícalo sin decirlo.',
  terminos,
};
