import type { Pregunta } from '@devweb/shared/games/trivial/tipos';

/**
 * Preguntas rescatadas del banco que se escribió antes del monorepo.
 *
 * Vivían en `src/app/games/trivial/data` con otro formato y, sobre todo, en la
 * web: las respuestas viajaban en el bundle, que en un concurso es repartir la
 * chuleta con las preguntas. Nunca llegaron a main y se habrían perdido al
 * limpiar la rama vieja.
 *
 * De las 1432 escritas a mano se han traído 152: las que tenían explicación.
 * El presentador la lee en voz alta al cerrar la ronda, así que una pregunta
 * sin ella deja el programa mudo justo en el momento que engancha. Las otras
 * 1029 siguen en el commit 70b26c1 (etiquetado `banco-trivial-viejo`) por si
 * algún día se les escribe una.
 *
 * El reparto por pruebas es el criterio que ya usa `pruebas.ts`: la bomba se
 * contesta con la mecha corriendo, así que va cortísima; en «el primero que
 * pulse» se cobra por lanzarse, así que tiene que leerse de un vistazo.
 *
 * Como el resto del banco, **no se importa nunca desde `apps/web`**.
 */
export const BANCO_RESCATADO: readonly Pregunta[] = [
  // --- Test: cuatro opciones y todos contestan a la vez ---
  {
    id: 'viejo-dev-lenguajes-003',
    tipo: 'test',
    enunciado: 'JavaScript lo inventó Brendan Eich en Netscape. ¿En cuántos días, según la leyenda (y él mismo)?',
    opciones: ['7', '10', '30', '90'],
    correcta: 1,
    explicacion: 'Diez días en mayo de 1995. Se llamó Mocha, luego LiveScript, luego JavaScript.',
  },
  {
    id: 'viejo-dev-lenguajes-019',
    tipo: 'test',
    enunciado: 'Ruby on Rails lo creó David Heinemeier Hansson. ¿De qué framework extrae Rails su nombre de joya?',
    opciones: ['Del lenguaje Ruby', 'De Perl', 'De Smalltalk', 'De Lisp'],
    correcta: 0,
    explicacion: 'Ruby (Matsumoto) + Rails. DHH lo sacó de Basecamp en 2004.',
  },
  {
    id: 'viejo-dev-historia-001',
    tipo: 'test',
    enunciado: '¿Quién se considera el primer programador de la historia, por las notas sobre la máquina de Babbage?',
    opciones: ['Alan Turing', 'Ada Lovelace', 'Grace Hopper', 'Konrad Zuse'],
    correcta: 1,
    explicacion: 'Ada Lovelace, 1843. Escribió un algoritmo para la máquina analítica. No llegó a ejecutarse.',
  },
  {
    id: 'viejo-dev-historia-002',
    tipo: 'test',
    enunciado: '¿Qué máquina descifraba (entre otras cosas) Enigma en Bletchley Park, asociada a Turing?',
    opciones: ['Colossus', 'ENIAC', 'The Bombe', 'UNIVAC'],
    correcta: 2,
    explicacion: 'La Bombe (versión británica de la de Rejewski). Colossus iba a Lorenz, no a Enigma.',
  },
  {
    id: 'viejo-dev-historia-004',
    tipo: 'test',
    enunciado: 'El primer «bug» de ordenador, una polilla en un relé, se atribuye a un equipo con Hopper. ¿En qué máquina?',
    opciones: ['ENIAC', 'Harvard Mark II', 'Altair 8800', 'IBM PC'],
    correcta: 1,
    explicacion: '9 de septiembre de 1947. La polilla está pegada en el logbook. Hopper popularizó la anécdota.',
  },
  {
    id: 'viejo-dev-web-013',
    tipo: 'test',
    enunciado: '¿Qué framework de Google usa componentes y TypeScript por defecto en su versión actual?',
    opciones: ['React', 'Vue', 'Angular', 'Svelte'],
    correcta: 2,
    explicacion: 'Angular (2+) es de Google. React es de Meta; Vue, de Evan You.',
  },
  {
    id: 'viejo-dev-datos-002',
    tipo: 'test',
    enunciado: '¿Qué significa REST en APIs web?',
    opciones: ['Representational State Transfer', 'Remote Execution Standard Transfer', 'Reliable Endpoint Service Transport', 'Request Event Stream Type'],
    correcta: 0,
    explicacion: 'Roy Fielding, tesis doctoral de 2000.',
  },
  {
    id: 'viejo-dev-datos-007',
    tipo: 'test',
    enunciado: 'Redis se usa sobre todo como…',
    opciones: ['Almacén documental', 'Caché / estructura en memoria', 'Bus de correo', 'CDN'],
    correcta: 1,
    explicacion: 'Clave-valor en RAM. También colas, pub/sub y locks.',
  },
  {
    id: 'viejo-dev-git-006',
    tipo: 'test',
    enunciado: 'Un commit de Git se identifica sobre todo por un hash. ¿De qué algoritmo, clásicamente?',
    opciones: ['MD5', 'SHA-1', 'bcrypt', 'CRC32'],
    correcta: 1,
    explicacion: 'SHA-1 (hoy hay repos SHA-256). No uses SHA-1 para contraseñas.',
  },
  {
    id: 'viejo-dev-git-008',
    tipo: 'test',
    enunciado: '¿Qué comando reescribe el último commit (mensaje o contenido) si aún no lo has empujado?',
    opciones: ['git revert', 'git reset --hard', 'git commit --amend', 'git rebase -i origin'],
    correcta: 2,
    explicacion: 'amend pega el cambio al último commit. revert crea uno nuevo que deshace. No amends a lo ya público sin avisar.',
  },
  {
    id: 'viejo-dev-hardware-006',
    tipo: 'test',
    enunciado: '¿Cuál de estos NO es un fabricante de CPUs para PC/servidor?',
    opciones: ['Intel', 'AMD', 'ARM (diseño) / sus licenciatarios', 'Western Digital como CPU x86'],
    correcta: 3,
    explicacion: 'WD hace discos. ARM diseña ISA; Intel y AMD fabrican x86.',
  },
  {
    id: 'viejo-dev-hardware-008',
    tipo: 'test',
    enunciado: 'USB-C y Thunderbolt 3/4 comparten conector. ¿Quién desarrolló Thunderbolt originalmente con Intel?',
    opciones: ['Apple', 'Microsoft', 'Sony', 'Dell'],
    correcta: 0,
    explicacion: 'Light Peak de Intel, Apple lo metió en Macs. Luego se abrió.',
  },
  {
    id: 'viejo-dev-cultura-002',
    tipo: 'test',
    enunciado: '«Hello, World» es tradicionalmente…',
    opciones: ['El primer programa que se enseña', 'Un virus de los 90', 'El prompt de BIOS', 'Un paquete de npm'],
    correcta: 0,
    explicacion: 'Kernighan lo usó en un tutorial de B, 1972, y pegó en el K&R.',
  },
  {
    id: 'viejo-dev-x1-lenguajes-037',
    tipo: 'test',
    enunciado: '¿Cuál NO es un tipo primitivo habitual en Java?',
    opciones: ['int', 'boolean', 'string (con minúscula, clase)', 'double'],
    correcta: 2,
    explicacion: 'String es clase. int, boolean, double sí son primitivos.',
  },
  {
    id: 'viejo-dev-x2-seguridad-108',
    tipo: 'test',
    enunciado: '¿Cuál NO es un hash criptográfico clásico?',
    opciones: ['SHA-256', 'SHA-3', 'BLAKE2', 'CRC32 como firma de autenticidad'],
    correcta: 3,
    explicacion: 'CRC32 detecta basura accidental, no a un atacante.',
  },
  {
    id: 'viejo-gen-geografia-001',
    tipo: 'test',
    enunciado: '¿Cuál es el río más largo de la Tierra (disputa clásica: Nilo vs Amazonas)? El consenso habitual de «más largo» apunta al…',
    opciones: ['Nilo', 'Yangtsé', 'Misisipi', 'Danubio'],
    correcta: 0,
    explicacion: 'El Nilo suele llevarse «el más largo»; el Amazonas, «el de mayor caudal». Hay papers en los dos bandos.',
  },
  {
    id: 'viejo-gen-musica-012',
    tipo: 'test',
    enunciado: 'Nirvana lideraba Kurt Cobain. ¿Cómo se llamaba su batería más famoso de la etapa Nevermind?',
    opciones: ['Dave Grohl', 'Lars Ulrich', 'Chad Smith', 'Travis Barker'],
    correcta: 0,
    explicacion: 'Luego montó Foo Fighters. Ulrich es Metallica; Smith, Chili Peppers; Barker, Blink-182.',
  },
  {
    id: 'viejo-gen-television-005',
    tipo: 'test',
    enunciado: 'Walter White es el prota de…',
    opciones: ['The Wire', 'Breaking Bad', 'Better Call Saul (el primero)', 'Narcos'],
    correcta: 1,
    explicacion: 'Better Call Saul es el spin-off de Saul Goodman.',
  },
  {
    id: 'viejo-gen-naturaleza-010',
    tipo: 'test',
    enunciado: 'El «baobab» es un árbol típico de…',
    opciones: ['La tundra', 'Sabanas africanas (y algún otro sitio)', 'Los Alpes', 'La Amazonía exclusivamente'],
    correcta: 1,
    explicacion: 'También hay especies en Madagascar y Australia.',
  },
  {
    id: 'viejo-general-x2-cine-018',
    tipo: 'test',
    enunciado: 'El primer Óscar a mejor película extranjera de una película española (en democracia tardía famosa) «Belle Époque» es de…',
    opciones: ['Trueba', 'Almodóvar', 'Amenábar', 'Berlanga'],
    correcta: 0,
    explicacion: '1994. Almodóvar ganó después con Todo sobre mi madre, que es otro premio.',
  },
  {
    id: 'viejo-general-x3-geografia-002',
    tipo: 'test',
    enunciado: '¿Cuál es la capital de Países Bajos?',
    opciones: ['Róterdam', 'Ámsterdam', 'La Haya (gobierno) / Ámsterdam capital', 'Utrecht'],
    correcta: 1,
    explicacion: 'La Haya alberga el gobierno; la capital constitucional es Ámsterdam.',
  },
  {
    id: 'viejo-general-x3-ciencia-082',
    tipo: 'test',
    enunciado: '¿Cuál NO es un sentido clásico de los cinco?',
    opciones: ['Vista', 'Oído', 'Equilibrio (vestibular, extra)', 'Olfato'],
    correcta: 2,
    explicacion: 'El vestibular existe, pero no es de los cinco escolares.',
  },

  // --- El primero que pulse: se leen de un vistazo ---
  {
    id: 'viejo-dev-lenguajes-002',
    tipo: 'pulsa',
    enunciado: '¿En qué lenguaje está escrito originalmente el kernel de Linux?',
    opciones: ['C', 'C++', 'Assembly puro', 'Rust'],
    correcta: 0,
    explicacion: 'C con un poco de ensamblador. Rust está entrando ahora, a cuentagotas.',
  },
  {
    id: 'viejo-dev-lenguajes-009',
    tipo: 'pulsa',
    enunciado: '¿Qué lenguaje se diseñó en Apple y se llama como un pájaro veloz?',
    opciones: ['Kotlin', 'Swift', 'Dart', 'Go'],
    correcta: 1,
    explicacion: 'Swift, 2014. Sustituye a Objective-C en iOS y macOS.',
  },
  {
    id: 'viejo-dev-lenguajes-010',
    tipo: 'pulsa',
    enunciado: 'El primer compilador de COBOL lo lideró una almirante de la Navy. ¿Quién?',
    opciones: ['Ada Lovelace', 'Grace Hopper', 'Margaret Hamilton', 'Radia Perlman'],
    correcta: 1,
    explicacion: 'Hopper impulsó FLOW-MATIC y COBOL. Lovelace es el siglo XIX; Hamilton, el Apolo.',
  },
  {
    id: 'viejo-dev-lenguajes-013',
    tipo: 'pulsa',
    enunciado: 'PHP empezó como un conjunto de scripts. ¿Qué significaban las siglas al principio?',
    opciones: ['Personal Home Page', 'PHP: Hypertext Preprocessor', 'Public Hosting Pages', 'Pretty HTML Parser'],
    correcta: 0,
    explicacion: 'Rasmus Lerdorf, 1994: Personal Home Page Tools. Luego se reconvirtió en acrónimo recursivo.',
  },
  {
    id: 'viejo-dev-lenguajes-015',
    tipo: 'pulsa',
    enunciado: 'En Python, ¿qué se usa para delimitar bloques en vez de llaves?',
    opciones: ['Paréntesis', 'La indentación', 'Punto y coma', 'Palabras begin/end'],
    correcta: 1,
    explicacion: 'Los espacios (o tabuladores, pero no mezcles) son sintaxis. Por eso duele un mal copypaste.',
  },
  {
    id: 'viejo-dev-lenguajes-017',
    tipo: 'pulsa',
    enunciado: 'Rust nació en Mozilla. ¿Quién lo empezó como proyecto personal?',
    opciones: ['Graydon Hoare', 'Brendan Eich', 'Linus Torvalds', 'Ryan Dahl'],
    correcta: 0,
    explicacion: 'Graydon Hoare, ~2006. Mozilla lo adoptó; ahora lo gobierna la Rust Foundation.',
  },
  {
    id: 'viejo-dev-historia-008',
    tipo: 'pulsa',
    enunciado: '¿Cuál de estos NO fue un ordenador de los años 70/80 para el hogar?',
    opciones: ['Commodore 64', 'ZX Spectrum', 'ENIAC', 'Apple II'],
    correcta: 2,
    explicacion: 'ENIAC es de 1945 y ocupaba una sala. Los otros tres sí se vendían en casa.',
  },
  {
    id: 'viejo-dev-historia-009',
    tipo: 'pulsa',
    enunciado: 'Microsoft se fundó en 1975. ¿Cuál fue su primer producto famoso?',
    opciones: ['Windows', 'MS-DOS', 'Altair BASIC', 'Excel'],
    correcta: 2,
    explicacion: 'Un BASIC para el Altair 8800. Lo escribieron Gates y Allen. MS-DOS llega en 1981.',
  },
  {
    id: 'viejo-dev-historia-016',
    tipo: 'pulsa',
    enunciado: '¿Qué protocolo de correo electrónico se usa para ENVIAR (no para leer la bandeja)?',
    opciones: ['IMAP', 'POP3', 'SMTP', 'FTP'],
    correcta: 2,
    explicacion: 'SMTP envía. IMAP y POP3 recogen. FTP es para archivos.',
  },
  {
    id: 'viejo-dev-historia-017',
    tipo: 'pulsa',
    enunciado: 'El primer tuit de la historia lo escribió Jack Dorsey. ¿Qué decía, en esencia?',
    opciones: ['Hello world', 'just setting up my twttr', 'This is Twitter', 'Good morning'],
    correcta: 1,
    explicacion: '21 de marzo de 2006. Sigue ahí, fosilizado.',
  },
  {
    id: 'viejo-dev-web-003',
    tipo: 'pulsa',
    enunciado: '¿Qué código HTTP se usa para un recurso creado con éxito (p. ej. un POST)?',
    opciones: ['200', '201', '204', '202'],
    correcta: 1,
    explicacion: '201 Created. 204 es «sin contenido». 202 es «aceptado, ya lo haré».',
  },
  {
    id: 'viejo-dev-datos-008',
    tipo: 'pulsa',
    enunciado: '¿Qué patrón describe un backend que solo habla JSON/HTTP y no sirve HTML?',
    opciones: ['MVC', 'API REST o similar', 'SSR', 'SOAP únicamente'],
    correcta: 1,
    explicacion: 'El navegador o la app móvil pintan. El servidor da datos. También hay GraphQL, gRPC…',
  },
  {
    id: 'viejo-dev-sistemas-007',
    tipo: 'pulsa',
    enunciado: 'Docker empaqueta una app con sus dependencias. ¿Cómo se llama esa unidad?',
    opciones: ['Máquina virtual', 'Contenedor', 'Chroot', 'Pod únicamente'],
    correcta: 1,
    explicacion: 'El pod es de Kubernetes: uno o varios contenedores juntos.',
  },
  {
    id: 'viejo-dev-sistemas-008',
    tipo: 'pulsa',
    enunciado: 'Kubernetes nació en Google. ¿De qué sistema interno hereda ideas?',
    opciones: ['Borg', 'MapReduce', 'Bigtable', 'Spanner'],
    correcta: 0,
    explicacion: 'Borg (y Omega). Kubernetes se presentó en 2014.',
  },
  {
    id: 'viejo-dev-sistemas-010',
    tipo: 'pulsa',
    enunciado: 'systemd es el init de muchas distros. ¿Quién lo creó (Red Hat / Poettering)?',
    opciones: ['Lennart Poettering', 'Linus Torvalds', 'Richard Stallman', 'Ian Murdock'],
    correcta: 0,
    explicacion: '2010. Amado y odiado a partes iguales. Torvalds no lo escribió.',
  },
  {
    id: 'viejo-dev-sistemas-013',
    tipo: 'pulsa',
    enunciado: '¿Qué archivo de Linux suele guardar las cuentas de usuario (nombres, UID, shell)?',
    opciones: ['/etc/passwd', '/etc/shadow', '/etc/hosts', '/etc/group'],
    correcta: 0,
    explicacion: 'Las contraseñas hasheadas están en /etc/shadow, no en passwd.',
  },
  {
    id: 'viejo-dev-hardware-005',
    tipo: 'pulsa',
    enunciado: 'La ley de Moore observaba que el número de transistores se duplicaba cada…',
    opciones: ['6 meses', 'aprox. 2 años', '10 años', 'cada generación de Windows'],
    correcta: 1,
    explicacion: 'Gordon Moore, 1965/1975. Hoy está más que discutida.',
  },
  {
    id: 'viejo-dev-algoritmos-006',
    tipo: 'pulsa',
    enunciado: 'El problema de la parada (halting problem) lo demostró insoluble…',
    opciones: ['Church', 'Turing', 'Gödel solo', 'von Neumann'],
    correcta: 1,
    explicacion: '1936. No hay programa que decida si cualquier otro programa termina.',
  },
  {
    id: 'viejo-dev-seguridad-002',
    tipo: 'pulsa',
    enunciado: 'XSS significa…',
    opciones: ['Cross-Site Scripting', 'Extra Secure Socket', 'XML Style Sheet', 'X-Frame Strict Security'],
    correcta: 0,
    explicacion: 'Colar JS en la página de otro. Distinto de CSRF.',
  },
  {
    id: 'viejo-dev-cultura-008',
    tipo: 'pulsa',
    enunciado: 'La licencia GPL la escribió (el espíritu y el texto fundacional)…',
    opciones: ['Linus Torvalds', 'Richard Stallman / FSF', 'Eric Raymond', 'Bill Gates'],
    correcta: 1,
    explicacion: 'Copyleft: el derivado sigue libre. Linux se licencia en GPL, pero Linus no la inventó.',
  },
  {
    id: 'viejo-dev-ia-002',
    tipo: 'pulsa',
    enunciado: 'El paper «Attention Is All You Need» (2017) introduce…',
    opciones: ['Las redes convolucionales', 'El Transformer', 'El perceptrón', 'LSTM'],
    correcta: 1,
    explicacion: 'Vaswani et al., Google. Base de GPT, BERT, etc.',
  },
  {
    id: 'viejo-dev-ia-007',
    tipo: 'pulsa',
    enunciado: '¿Cuál de estos NO es un modelo o familia de modelo de lenguaje famosa?',
    opciones: ['GPT', 'BERT', 'LLaMA', 'JPEG XL'],
    correcta: 3,
    explicacion: 'JPEG XL es un formato de imagen.',
  },
  {
    id: 'viejo-dev-x2-sistemas-028',
    tipo: 'pulsa',
    enunciado: '¿Qué comando Linux muestra uso de disco por directorio (humano)?',
    opciones: ['df -h', 'du -h', 'free -h', 'ls -lh solo'],
    correcta: 1,
    explicacion: 'du es usage; df es espacio de sistemas de archivos.',
  },
  {
    id: 'viejo-gen-historia-011',
    tipo: 'pulsa',
    enunciado: '¿Quién escribió las 95 tesis que dispararon la Reforma protestante?',
    opciones: ['Calvino', 'Lutero', 'Erasmo', 'Enrique VIII'],
    correcta: 1,
    explicacion: 'Wittenberg, 1517.',
  },
  {
    id: 'viejo-gen-ciencia-006',
    tipo: 'pulsa',
    enunciado: 'El ADN está en el núcleo (en eucariotas) y su forma clásica es…',
    opciones: ['Triple hélice', 'Doble hélice', 'Anillo plano', 'Cubo'],
    correcta: 1,
    explicacion: 'Watson, Crick, Franklin y Wilkins, 1953.',
  },
  {
    id: 'viejo-gen-cine-002',
    tipo: 'pulsa',
    enunciado: 'En Star Wars, ¿cómo se llama el padre de Luke, de negro y respirador?',
    opciones: ['Yoda', 'Darth Vader', 'Obi-Wan', 'Palpatine'],
    correcta: 1,
    explicacion: 'Anakin Skywalker, detrás de la máscara.',
  },
  {
    id: 'viejo-gen-cine-004',
    tipo: 'pulsa',
    enunciado: 'El Óscar a mejor película de 2003 (ceremonia 2004) se lo llevó, de las de Tolkien…',
    opciones: ['La Comunidad del Anillo', 'Las dos torres', 'El retorno del rey', 'El hobbit'],
    correcta: 2,
    explicacion: 'Once estatuillas. Empató el récord de Ben-Hur y Titanic.',
  },
  {
    id: 'viejo-gen-cine-007',
    tipo: 'pulsa',
    enunciado: '¿Cuál de estas NO es una película de Studio Ghibli?',
    opciones: ['El viaje de Chihiro', 'Mi vecino Totoro', 'Akira', 'La princesa Mononoke'],
    correcta: 2,
    explicacion: 'Akira es de Ōtomo / Tokyo Movie Shinsha, no de Ghibli.',
  },
  {
    id: 'viejo-gen-television-009',
    tipo: 'pulsa',
    enunciado: 'El presentador original británico de «The Weakest Link» (el eslabón más débil) era…',
    opciones: ['Anne Robinson', 'Chris Tarrant', 'Alexander Armstrong', 'Richard Osman'],
    correcta: 0,
    explicacion: '«You are the weakest link. Goodbye.» Tarrant era el del Millonario.',
  },
  {
    id: 'viejo-gen-gastronomia-005',
    tipo: 'pulsa',
    enunciado: 'El «umami» es…',
    opciones: ['Un tipo de pasta', 'El quinto sabor básico', 'Un vino italiano', 'Un corte de carne'],
    correcta: 1,
    explicacion: 'Dulce, salado, ácido, amargo y umami. Ikeda, 1908.',
  },
  {
    id: 'viejo-gen-espana-005',
    tipo: 'pulsa',
    enunciado: 'El pico más alto del país (territorio español, incluyendo islas) es…',
    opciones: ['Mulhacén', 'Aneto', 'Teide', 'Veleta'],
    correcta: 2,
    explicacion: 'Tenerife, 3.715 m. En península, el Mulhacén.',
  },
  {
    id: 'viejo-general-x1-geografia-015',
    tipo: 'pulsa',
    enunciado: '¿Cuál es la capital de Sudáfrica legislativa (una de las tres)?',
    opciones: ['Johannesburgo', 'Ciudad del Cabo', 'Durban', 'Pretoria'],
    correcta: 1,
    explicacion: 'El Cabo es legislativa; Pretoria, administrativa; Bloemfontein, judicial.',
  },

  // --- Ráfaga: verdadero o falso, se contesta con el estómago ---
  {
    id: 'viejo-dev-lenguajes-004',
    tipo: 'rafaga',
    enunciado: 'Java y JavaScript los diseñó la misma persona.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'Java: James Gosling (Sun). JavaScript: Brendan Eich (Netscape). El nombre fue marketing.',
  },
  {
    id: 'viejo-dev-lenguajes-011',
    tipo: 'rafaga',
    enunciado: 'TypeScript lo desarrolla Microsoft y se compila a JavaScript.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Anders Hejlsberg (el de C# y Turbo Pascal) lo empezó en 2012.',
  },
  {
    id: 'viejo-dev-lenguajes-018',
    tipo: 'rafaga',
    enunciado: 'SQL es un lenguaje pensado sobre todo para consultar y manipular datos relacionales.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Structured Query Language. Lo inventó IBM (SEQUEL) en los 70.',
  },
  {
    id: 'viejo-dev-historia-005',
    tipo: 'rafaga',
    enunciado: 'El Macintosh original de Apple salió al mercado en 1984.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: '24 de enero de 1984. El anuncio de Ridley Scott se emitió en la Super Bowl.',
  },
  {
    id: 'viejo-dev-historia-013',
    tipo: 'rafaga',
    enunciado: 'Steve Wozniak fue el que diseñó el hardware del Apple I y del Apple II.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Woz el circuito; Jobs el empaque y la venta. Apple Computer, 1 de abril de 1976.',
  },
  {
    id: 'viejo-dev-historia-018',
    tipo: 'rafaga',
    enunciado: 'UNIX nació en Bell Labs, de la mano de Thompson y Ritchie.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: '1969-1971, AT&T Bell Labs. Luego vino C para reescribirlo.',
  },
  {
    id: 'viejo-dev-web-012',
    tipo: 'rafaga',
    enunciado: 'Una Single Page Application recarga el HTML completo en cada clic de menú.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'Justo al contrario: cambia la vista en el cliente sin recargar la página entera.',
  },
  {
    id: 'viejo-dev-datos-003',
    tipo: 'rafaga',
    enunciado: 'JSON nació como un subconjunto de la notación de objetos de JavaScript.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Douglas Crockford lo popularizó. Hoy es el esperanto de las APIs.',
  },
  {
    id: 'viejo-dev-datos-010',
    tipo: 'rafaga',
    enunciado: 'NULL en SQL significa «cero».',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'NULL es «no hay valor». No es 0 ni cadena vacía. Por eso `= NULL` no funciona: se usa `IS NULL`.',
  },
  {
    id: 'viejo-dev-sistemas-006',
    tipo: 'rafaga',
    enunciado: 'root en Unix es el usuario con todos los privilegios.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'UID 0. En Windows el análogo grosero es Administrador / SYSTEM.',
  },
  {
    id: 'viejo-dev-algoritmos-009',
    tipo: 'rafaga',
    enunciado: 'P vs NP es un problema abierto: no se ha demostrado que P = NP ni lo contrario.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Uno de los problemas del milenio. Hay un millón de dólares en juego.',
  },
  {
    id: 'viejo-dev-seguridad-003',
    tipo: 'rafaga',
    enunciado: 'Conviene guardar contraseñas en la base en texto claro para poder recordárselas al usuario.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'Hash + salt (bcrypt, argon2, scrypt). Si puedes leerlas, lo hace el ladrón también.',
  },
  {
    id: 'viejo-dev-seguridad-008',
    tipo: 'rafaga',
    enunciado: '2FA (doble factor) puede ser algo que sabes más algo que tienes.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Contraseña + móvil/llave. No es infalible (SIM swap, phishing), pero ayuda.',
  },
  {
    id: 'viejo-dev-cultura-003',
    tipo: 'rafaga',
    enunciado: 'Stack Overflow es un sitio de preguntas y respuestas para programadores.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Jeff Atwood y Joel Spolsky, 2008. Cuidado con copiar sin leer.',
  },
  {
    id: 'viejo-dev-ia-008',
    tipo: 'rafaga',
    enunciado: 'Entrenar un modelo grande y usarlo para completar texto (inferencia) consumen la misma cantidad de cómputo por token de usuario.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'El entrenamiento es un palizón único (o raro). La inferencia es lo que pagas en cada chat.',
  },
  {
    id: 'viejo-dev-x1-lenguajes-028',
    tipo: 'rafaga',
    enunciado: 'JavaScript y Java comparten el mismo recolector de basura y el mismo bytecode.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'Solo el nombre. Máquinas y semántica distintas.',
  },
  {
    id: 'viejo-dev-x1-lenguajes-030',
    tipo: 'rafaga',
    enunciado: 'Rust exige un recolector de basura en runtime como Java.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'El borrow checker vive en compilación.',
  },
  {
    id: 'viejo-dev-x1-web-075',
    tipo: 'rafaga',
    enunciado: 'HTTPS usa el puerto 80 por defecto.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: '443. El 80 es HTTP plano.',
  },
  {
    id: 'viejo-dev-x1-git-102',
    tipo: 'rafaga',
    enunciado: '`git revert` borra el commit de la historia como si no hubiera existido.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'Crea un commit nuevo que deshace los cambios. No reescribe historia.',
  },
  {
    id: 'viejo-dev-x1-cultura-124',
    tipo: 'rafaga',
    enunciado: '«Legacy code» es, en la broma de Feathers, código sin tests.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Working Effectively with Legacy Code, Michael Feathers.',
  },
  {
    id: 'viejo-dev-x2-datos-062',
    tipo: 'rafaga',
    enunciado: 'En SQL, `COUNT(*)` ignora las filas con NULL en cualquier columna.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'COUNT(*) cuenta filas. COUNT(col) ignora NULL de esa col.',
  },
  {
    id: 'viejo-dev-secmix-seguridad-050',
    tipo: 'rafaga',
    enunciado: 'TLS cifra el contenido de la petición HTTP, no solo el nombre de dominio en el SNI de siempre.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'El SNI va en claro en TLS clásico; el path y el body van cifrados tras el handshake.',
  },
  {
    id: 'viejo-gen-arte-005',
    tipo: 'rafaga',
    enunciado: 'Picasso nació en España.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Málaga, 1881. Murió en Francia.',
  },
  {
    id: 'viejo-gen-naturaleza-003',
    tipo: 'rafaga',
    enunciado: 'Los pingüinos viven, de forma natural, sobre todo en el hemisferio sur.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 0,
    explicacion: 'Galápagos rozan el ecuador. No hay colonias salvajes en el Ártico.',
  },
  {
    id: 'viejo-general-x1-ciencia-096',
    tipo: 'rafaga',
    enunciado: 'Un año luz es una unidad de tiempo.',
    opciones: ['Verdadero', 'Falso'],
    correcta: 1,
    explicacion: 'Es distancia: lo que recorre la luz en un año.',
  },

  // --- Estimación: un número, y se puntúa por lo cerca que caes ---
  {
    id: 'viejo-dev-lenguajes-005',
    tipo: 'estimacion',
    enunciado: '¿En qué año se publicó la primera edición del K&R, «The C Programming Language»?',
    opciones: [],
    correcta: 1978,
    margen: 12,
    explicacion: 'Kernighan y Ritchie, 1978. La segunda edición, ANSI C, es de 1988.',
  },
  {
    id: 'viejo-dev-lenguajes-020',
    tipo: 'estimacion',
    enunciado: '¿En qué año se presentó Java al público (Sun / «Write Once, Run Anywhere»)?',
    opciones: [],
    correcta: 1995,
    margen: 12,
    explicacion: 'Mayo de 1995, SunWorld. El JDK 1.0 es de enero de 1996.',
  },
  {
    id: 'viejo-dev-historia-003',
    tipo: 'estimacion',
    enunciado: '¿En qué año se envió el primer mensaje de ARPANET (aunque se cayó a la «LO» de LOGIN)?',
    opciones: [],
    correcta: 1969,
    margen: 12,
    explicacion: '29 de octubre de 1969, UCLA a Stanford. Kleinrock. Se colgó en la G de LOGIN.',
  },
  {
    id: 'viejo-dev-historia-007',
    tipo: 'estimacion',
    enunciado: '¿En qué año Linus Torvalds anunció Linux en el grupo comp.os.minix?',
    opciones: [],
    correcta: 1991,
    margen: 12,
    explicacion: 'Agosto de 1991. «I\'m doing a (free) operating system (just a hobby)…»',
  },
  {
    id: 'viejo-dev-historia-015',
    tipo: 'estimacion',
    enunciado: '¿En qué año Intel presentó el 4004, el primer microprocesador comercial?',
    opciones: [],
    correcta: 1971,
    margen: 12,
    explicacion: '15 de noviembre de 1971. 4 bits, para una calculadora Busicom.',
  },
  {
    id: 'viejo-dev-datos-009',
    tipo: 'estimacion',
    enunciado: '¿Cuántos bytes tiene un UUID típico de 128 bits?',
    opciones: [],
    correcta: 16,
    margen: 2,
    explicacion: '128 bits = 16 bytes. En texto, 36 caracteres con guiones.',
  },
  {
    id: 'viejo-dev-hardware-009',
    tipo: 'estimacion',
    enunciado: '¿Cuántos bytes son 1 KiB (kibibyte, 2^10)?',
    opciones: [],
    correcta: 1024,
    margen: 12,
    explicacion: '1024, no 1000. El kB de disco a veces es 1000: por eso «el disco miente».',
  },
  {
    id: 'viejo-dev-algoritmos-008',
    tipo: 'estimacion',
    enunciado: 'En un árbol binario lleno de altura h (raíz = 1), ¿cuántas hojas hay, en potencia de 2? Si h=3, ¿cuántas hojas?',
    opciones: [],
    correcta: 4,
    margen: 1,
    explicacion: 'Altura 3: raíz, dos hijos, cuatro nietos. 2^(h-1) = 4.',
  },
  {
    id: 'viejo-dev-seguridad-010',
    tipo: 'estimacion',
    enunciado: '¿En qué año se publicó el fallo Heartbleed de OpenSSL (CVE-2014-0160)?',
    opciones: [],
    correcta: 2014,
    margen: 12,
    explicacion: 'Abril de 2014. El 0160 es el id del CVE.',
  },
  {
    id: 'viejo-dev-cultura-011',
    tipo: 'estimacion',
    enunciado: 'En el chiste clásico: hay 10 tipos de personas, las que entienden binario y las que no. ¿Qué número decimal es el 10 binario?',
    opciones: [],
    correcta: 2,
    margen: 1,
    explicacion: '1×2 + 0×1 = 2. Por eso el chiste.',
  },
  {
    id: 'viejo-dev-x1-lenguajes-033',
    tipo: 'estimacion',
    enunciado: '¿En qué año se publicó Python 3.0?',
    opciones: [],
    correcta: 2008,
    margen: 12,
    explicacion: 'Diciembre de 2008. Rompió compatibilidad con Python 2.',
  },
  {
    id: 'viejo-dev-x1-lenguajes-035',
    tipo: 'estimacion',
    enunciado: '¿En qué año se estandarizó C89/C90 (ANSI/ISO)?',
    opciones: [],
    correcta: 1989,
    margen: 12,
    explicacion: 'ANSI 1989, ISO 1990. Se habla de C89 o C90.',
  },
  {
    id: 'viejo-dev-x3-sistemas-054',
    tipo: 'estimacion',
    enunciado: '¿Qué señal es SIGKILL (número)?',
    opciones: [],
    correcta: 9,
    margen: 1,
    explicacion: '9. No se puede capturar. SIGTERM es 15.',
  },
  {
    id: 'viejo-dev-extra-5-algoritmos-024',
    tipo: 'estimacion',
    enunciado: '¿Cuál es la complejidad temporal de acceder por índice a un array?',
    opciones: [],
    correcta: 1,
    margen: 1,
    explicacion: 'Es tiempo constante, O(1).',
  },
  {
    id: 'viejo-dev-extra-6-datos-072',
    tipo: 'estimacion',
    enunciado: '¿Cuál es la complejidad de buscar en una tabla hash ideal?',
    opciones: [],
    correcta: 1,
    margen: 1,
    explicacion: 'En promedio, O(1).',
  },
  {
    id: 'viejo-dev-secmix-ia-063',
    tipo: 'estimacion',
    enunciado: '¿Cuántos millones de parámetros anunció GPT-2 en su tamaño mayor público original (el de 1,5B se dice 1500 millones)?',
    opciones: [],
    correcta: 1500,
    margen: 12,
    explicacion: 'El paper habla de 1.5B; 1500 millones.',
  },
  {
    id: 'viejo-gen-geografia-006',
    tipo: 'estimacion',
    enunciado: '¿Cuántos continentes se suelen contar en el modelo escolar de siete (incluyendo la Antártida)?',
    opciones: [],
    correcta: 7,
    margen: 1,
    explicacion: 'África, América, Asia, Europa, Oceanía y la Antártida. A veces América se parte en dos y salen 7 igual; el de 5 junta América y junta Europa-Asia.',
  },
  {
    id: 'viejo-gen-ciencia-009',
    tipo: 'estimacion',
    enunciado: '¿Cuántos huesos tiene, aproximadamente, el esqueleto humano adulto?',
    opciones: [],
    correcta: 206,
    margen: 25,
    explicacion: '206 es la cifra de libro. Los bebés tienen más, luego se fusionan.',
  },
  {
    id: 'viejo-gen-arte-011',
    tipo: 'estimacion',
    enunciado: 'Rembrandt pintó sobre todo en el siglo XVII. ¿Qué número de siglo es ese (17, no romano)?',
    opciones: [],
    correcta: 17,
    margen: 2,
    explicacion: 'Nació en 1606, murió en 1669.',
  },
  {
    id: 'viejo-gen-gastronomia-008',
    tipo: 'estimacion',
    enunciado: '¿Cuál es el máximo de estrellas Michelin que puede tener un restaurante?',
    opciones: [],
    correcta: 3,
    margen: 1,
    explicacion: 'Tres estrellas: «una de las mejores mesas, vale el viaje».',
  },
  {
    id: 'viejo-gen-naturaleza-007',
    tipo: 'estimacion',
    enunciado: '¿Cuántos corazones tiene un pulpo (el común)?',
    opciones: [],
    correcta: 3,
    margen: 1,
    explicacion: 'Dos branquiales y uno sistémico.',
  },
  {
    id: 'viejo-gen-espana-008',
    tipo: 'estimacion',
    enunciado: '¿Cuántas comunidades autónomas tiene España?',
    opciones: [],
    correcta: 17,
    margen: 2,
    explicacion: '17 más 2 ciudades autónomas (Ceuta y Melilla).',
  },

  // --- La bomba: cortísimas, se contestan con la mecha corriendo ---
  {
    id: 'viejo-dev-lenguajes-001',
    tipo: 'bomba',
    enunciado: '¿Quién diseñó originalmente el lenguaje Python?',
    opciones: ['Bjarne Stroustrup', 'Guido van Rossum', 'James Gosling', 'Brendan Eich'],
    correcta: 1,
    explicacion: 'Lo empezó en Navidad de 1989. Se llama Python por Monty Python, no por la serpiente.',
  },
  {
    id: 'viejo-dev-lenguajes-006',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un lenguaje de programación?',
    opciones: ['Haskell', 'Erlang', 'Markdown', 'Prolog'],
    correcta: 2,
    explicacion: 'Markdown es un formato de texto. Los otros tres son lenguajes de verdad.',
  },
  {
    id: 'viejo-dev-lenguajes-007',
    tipo: 'bomba',
    enunciado: 'C++ lo creó Bjarne Stroustrup. ¿Cómo se llamaba al principio?',
    opciones: ['C with Classes', 'C++', 'Objective-C', 'D'],
    correcta: 0,
    explicacion: '«C with Classes» en 1979. El nombre C++ (operador de incremento) llega en 1983.',
  },
  {
    id: 'viejo-dev-lenguajes-012',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un lenguaje de Microsoft?',
    opciones: ['C#', 'F#', 'TypeScript', 'Kotlin'],
    correcta: 3,
    explicacion: 'Kotlin es de JetBrains. C#, F# y TypeScript salieron de Microsoft.',
  },
  {
    id: 'viejo-dev-historia-006',
    tipo: 'bomba',
    enunciado: '¿Quién creó el World Wide Web en el CERN?',
    opciones: ['Vint Cerf', 'Tim Berners-Lee', 'Bob Kahn', 'Marc Andreessen'],
    correcta: 1,
    explicacion: '1989 la propuesta, 1990 el primer servidor. HTML, URI y HTTP salen de ahí.',
  },
  {
    id: 'viejo-dev-historia-011',
    tipo: 'bomba',
    enunciado: '¿Qué empresa compró GitHub en 2018?',
    opciones: ['Google', 'Microsoft', 'Amazon', 'Meta'],
    correcta: 1,
    explicacion: '7.500 millones de dólares. Satya Nadella, junio de 2018.',
  },
  {
    id: 'viejo-dev-historia-014',
    tipo: 'bomba',
    enunciado: 'El ratón de ordenador lo inventó (el prototipo de madera)…',
    opciones: ['Douglas Engelbart', 'Xerox PARC', 'Steve Jobs', 'Bill Atkinson'],
    correcta: 0,
    explicacion: 'Engelbart, 1964, SRI. Xerox PARC lo refinó; Apple lo popularizó.',
  },
  {
    id: 'viejo-dev-web-002',
    tipo: 'bomba',
    enunciado: '¿Qué código HTTP significa «no encontrado»?',
    opciones: ['200', '301', '404', '500'],
    correcta: 2,
    explicacion: '200 OK, 301 redirect permanente, 404 not found, 500 error del servidor.',
  },
  {
    id: 'viejo-dev-web-004',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un método HTTP?',
    opciones: ['GET', 'PUT', 'FETCH', 'DELETE'],
    correcta: 2,
    explicacion: 'fetch() es la API de JavaScript. Los verbos son GET, POST, PUT, PATCH, DELETE…',
  },
  {
    id: 'viejo-dev-web-006',
    tipo: 'bomba',
    enunciado: '¿Quién creó jQuery?',
    opciones: ['John Resig', 'Ryan Dahl', 'Evan You', 'Jordan Walke'],
    correcta: 0,
    explicacion: '2006. «Write less, do more». Ryan Dahl es Node; Evan You, Vue; Walke, React.',
  },
  {
    id: 'viejo-dev-web-007',
    tipo: 'bomba',
    enunciado: 'React nació en…',
    opciones: ['Google', 'Facebook', 'Twitter', 'Microsoft'],
    correcta: 1,
    explicacion: 'Jordan Walke, 2013, de un prototipo interno de 2011 (FaxJS).',
  },
  {
    id: 'viejo-dev-web-014',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un empaquetador / bundler de frontend?',
    opciones: ['webpack', 'Vite', 'esbuild', 'nginx'],
    correcta: 3,
    explicacion: 'nginx es un servidor. Los otros tres empaquetan JS.',
  },
  {
    id: 'viejo-dev-datos-001',
    tipo: 'bomba',
    enunciado: 'En SQL, ¿qué cláusula filtra filas DESPUÉS de agrupar?',
    opciones: ['WHERE', 'HAVING', 'GROUP BY', 'ORDER BY'],
    correcta: 1,
    explicacion: 'WHERE filtra antes del GROUP BY. HAVING, después.',
  },
  {
    id: 'viejo-dev-datos-004',
    tipo: 'bomba',
    enunciado: '¿Cuál de estas bases NO es relacional?',
    opciones: ['PostgreSQL', 'MySQL', 'MongoDB', 'SQLite'],
    correcta: 2,
    explicacion: 'Mongo es documental (NoSQL). Las otras tres hablan SQL.',
  },
  {
    id: 'viejo-dev-datos-005',
    tipo: 'bomba',
    enunciado: 'ACID en bases de datos: Atomicity, Consistency, Isolation y…',
    opciones: ['Durability', 'Distribution', 'Density', 'Dependency'],
    correcta: 0,
    explicacion: 'Lo que se confirma, sobrevive a un corte de luz.',
  },
  {
    id: 'viejo-dev-datos-011',
    tipo: 'bomba',
    enunciado: 'GraphQL lo sacó…',
    opciones: ['Google', 'Facebook', 'Netflix', 'Amazon'],
    correcta: 1,
    explicacion: '2012 interno, 2015 público. Lee lo que pides, ni más ni menos.',
  },
  {
    id: 'viejo-dev-datos-012',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un tipo de JOIN de SQL?',
    opciones: ['INNER JOIN', 'LEFT JOIN', 'CROSS JOIN', 'SIDE JOIN'],
    correcta: 3,
    explicacion: 'INNER, LEFT/RIGHT/FULL OUTER, CROSS. Side no existe.',
  },
  {
    id: 'viejo-dev-sistemas-009',
    tipo: 'bomba',
    enunciado: '¿Cuál de estas NO es una distribución Linux?',
    opciones: ['Ubuntu', 'Fedora', 'FreeBSD', 'Debian'],
    correcta: 2,
    explicacion: 'FreeBSD es un Unix de la familia BSD, no Linux.',
  },
  {
    id: 'viejo-dev-git-001',
    tipo: 'bomba',
    enunciado: '¿Quién creó Git?',
    opciones: ['Linus Torvalds', 'Junio Hamano', 'GitHub', 'BitKeeper'],
    correcta: 0,
    explicacion: '2005, cabreado con BitKeeper. Junio Hamano lo mantiene desde entonces.',
  },
  {
    id: 'viejo-dev-git-005',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un estado típico de un archivo en Git?',
    opciones: ['staged', 'modified', 'committed', 'compiled'],
    correcta: 3,
    explicacion: 'Working tree, staged (index), committed. «Compiled» no es un estado de Git.',
  },
  {
    id: 'viejo-dev-algoritmos-004',
    tipo: 'bomba',
    enunciado: 'Una cola (queue) es…',
    opciones: ['LIFO', 'FIFO', 'Aleatoria', 'Árbol'],
    correcta: 1,
    explicacion: 'First in, first out. Como el súper, si nadie se cuela.',
  },
  {
    id: 'viejo-dev-algoritmos-005',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un algoritmo de ordenación clásico?',
    opciones: ['Quicksort', 'Mergesort', 'Heapsort', 'Dijkstrasort'],
    correcta: 3,
    explicacion: 'Dijkstra es caminos mínimos, no un sort.',
  },
  {
    id: 'viejo-dev-ia-006',
    tipo: 'bomba',
    enunciado: 'El perceptrón de Rosenblatt es de…',
    opciones: ['1958', '1986', '2012', '1997'],
    correcta: 0,
    explicacion: '1957-58. Minsky y Papert le dieron un palo en 1969; el invierno de la IA, en parte.',
  },
  {
    id: 'viejo-dev-x1-lenguajes-008',
    tipo: 'bomba',
    enunciado: '¿Qué valor devuelve `typeof null` en JavaScript?',
    opciones: ['null', 'object', 'undefined', 'nil'],
    correcta: 1,
    explicacion: 'Bug histórico. null no es un objeto, pero typeof dice que sí.',
  },
  {
    id: 'viejo-dev-x1-lenguajes-010',
    tipo: 'bomba',
    enunciado: '¿Qué hace `NaN === NaN` en JavaScript?',
    opciones: ['true', 'false', 'lanza error', 'undefined'],
    correcta: 1,
    explicacion: 'NaN no es igual a nada, ni a sí mismo. Se usa Number.isNaN.',
  },
  {
    id: 'viejo-dev-x1-web-050',
    tipo: 'bomba',
    enunciado: '¿Código HTTP de «no autorizado» (hace falta login)?',
    opciones: ['400', '401', '403', '404'],
    correcta: 1,
    explicacion: '401 Unauthorized (sin credenciales). 403 Forbidden (identificado, sin permiso).',
  },
  {
    id: 'viejo-dev-x1-web-081',
    tipo: 'bomba',
    enunciado: '¿Cuál NO es un framework CSS?',
    opciones: ['Bootstrap', 'Tailwind', 'Bulma', 'Express'],
    correcta: 3,
    explicacion: 'Express es backend Node.',
  },
  {
    id: 'viejo-gen-geografia-003',
    tipo: 'bomba',
    enunciado: '¿En qué continente está Egipto, mayoritariamente?',
    opciones: ['Asia', 'África', 'Europa', 'Oceanía'],
    correcta: 1,
    explicacion: 'El Sinaí es asiático, pero el país se cuenta como africano.',
  },
  {
    id: 'viejo-gen-geografia-007',
    tipo: 'bomba',
    enunciado: '¿Cuál de estas ciudades NO está en Italia?',
    opciones: ['Milán', 'Nápoles', 'Lyon', 'Turín'],
    correcta: 2,
    explicacion: 'Lyon es francesa.',
  },
  {
    id: 'viejo-gen-geografia-010',
    tipo: 'bomba',
    enunciado: '¿Cuál es el desierto más grande del mundo (contando el frío)?',
    opciones: ['Sáhara', 'Gobi', 'Antártida', 'Kalahari'],
    correcta: 2,
    explicacion: 'Desierto = muy poca precipitación. El Sáhara es el cálido más grande.',
  },
  {
    id: 'viejo-gen-geografia-012',
    tipo: 'bomba',
    enunciado: '¿Cuál es la capital de Kazajistán desde 2019 (nombre actual)?',
    opciones: ['Almatý', 'Astaná', 'Biskek', 'Taskent'],
    correcta: 1,
    explicacion: 'Fue Astaná, luego Nur-Sultán (2019-2022) y otra vez Astaná.',
  },
  {
    id: 'viejo-gen-historia-005',
    tipo: 'bomba',
    enunciado: '¿Quién fue el primer emperador de Roma?',
    opciones: ['Julio César', 'Augusto', 'Nerón', 'Trajano'],
    correcta: 1,
    explicacion: 'César fue dictador y lo mataron. Augusto (Octavio) es el primer princeps.',
  },
  {
    id: 'viejo-gen-historia-007',
    tipo: 'bomba',
    enunciado: 'La peste negra asoló Europa sobre todo en el siglo…',
    opciones: ['X', 'XIV', 'XVIII', 'XX'],
    correcta: 1,
    explicacion: 'Oleada de 1347-1351, más o menos. Mató a un tercio del continente, groso modo.',
  },
  {
    id: 'viejo-gen-historia-008',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO fue un faraón egipcio?',
    opciones: ['Tutankamón', 'Ramsés II', 'Julio César', 'Keops'],
    correcta: 2,
    explicacion: 'César anduvo por Egipto, pero el trono ptolemaico lo ocupaba Cleopatra. No fue faraón.',
  },
  {
    id: 'viejo-gen-ciencia-011',
    tipo: 'bomba',
    enunciado: 'El bosón de Higgs se observó en el CERN en…',
    opciones: ['1964', '1989', '2012', '2020'],
    correcta: 2,
    explicacion: 'El mecanismo es de 1964; la partícula, 2012 (ATLAS y CMS).',
  },
  {
    id: 'viejo-gen-cine-006',
    tipo: 'bomba',
    enunciado: '«El Padrino» la protagoniza, como Vito Corleone…',
    opciones: ['Al Pacino', 'Robert De Niro', 'Marlon Brando', 'Joe Pesci'],
    correcta: 2,
    explicacion: 'De Niro es el Vito joven en la II. Pacino es Michael.',
  },
  {
    id: 'viejo-gen-cine-010',
    tipo: 'bomba',
    enunciado: 'La primera película de Pixar (largometraje) fue…',
    opciones: ['Shrek', 'Toy Story', 'Buscando a Nemo', 'Monstruos, S.A.'],
    correcta: 1,
    explicacion: '1995. Shrek es de DreamWorks.',
  },
  {
    id: 'viejo-gen-musica-001',
    tipo: 'bomba',
    enunciado: '¿De qué ciudad eran los Beatles?',
    opciones: ['Londres', 'Liverpool', 'Manchester', 'Hamburgo'],
    correcta: 1,
    explicacion: 'Hamburgo los pulió; el origen es Liverpool.',
  },
  {
    id: 'viejo-gen-musica-006',
    tipo: 'bomba',
    enunciado: '«Bohemian Rhapsody» dura, groseramente, casi…',
    opciones: ['2 minutos', '6 minutos', '12 minutos', '20 minutos'],
    correcta: 1,
    explicacion: '5:55. La radio de 1975 la encontraba larga. Ganó igual.',
  },
  {
    id: 'viejo-gen-musica-007',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un instrumento de cuerda frotada?',
    opciones: ['Violín', 'Viola', 'Trombón', 'Violonchelo'],
    correcta: 2,
    explicacion: 'El trombón es de viento-metal.',
  },
  {
    id: 'viejo-gen-deporte-006',
    tipo: 'bomba',
    enunciado: '¿Cuántos anillos entrelazados tiene la bandera olímpica?',
    opciones: ['4', '5', '6', '7'],
    correcta: 1,
    explicacion: 'Cinco continentes, cinco colores.',
  },
  {
    id: 'viejo-gen-deporte-008',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un Grand Slam de tenis?',
    opciones: ['Wimbledon', 'Roland Garros', 'Open de Australia', 'Copa Davis'],
    correcta: 3,
    explicacion: 'La Davis es por equipos. El cuarto slam es el US Open.',
  },
  {
    id: 'viejo-gen-deporte-009',
    tipo: 'bomba',
    enunciado: 'España ganó su primer Mundial de fútbol en…',
    opciones: ['2008', '2010', '2012', '1982'],
    correcta: 1,
    explicacion: 'Sudáfrica. Iniesta en el 116. 2008 y 2012 son Eurocopas. 1982 se jugó aquí, no se ganó.',
  },
  {
    id: 'viejo-gen-television-007',
    tipo: 'bomba',
    enunciado: '¿Cuál de estas NO es una serie de HBO clásica?',
    opciones: ['The Sopranos', 'The Wire', 'Friends', 'True Detective'],
    correcta: 2,
    explicacion: 'Friends es de NBC.',
  },
  {
    id: 'viejo-gen-naturaleza-005',
    tipo: 'bomba',
    enunciado: 'El koala se alimenta sobre todo de hojas de…',
    opciones: ['Pino', 'Eucalipto', 'Roble', 'Bambú'],
    correcta: 1,
    explicacion: 'El bambú es el panda.',
  },
  {
    id: 'viejo-gen-naturaleza-006',
    tipo: 'bomba',
    enunciado: '¿Cuál de estos NO es un reptil?',
    opciones: ['Cocodrilo', 'Iguana', 'Salamandra', 'Tortuga'],
    correcta: 2,
    explicacion: 'La salamandra es un anfibio.',
  },
  {
    id: 'viejo-gen-espana-007',
    tipo: 'bomba',
    enunciado: '¿Cuál de estas NO es una comunidad autónoma?',
    opciones: ['Navarra', 'La Rioja', 'Andorra', 'Murcia'],
    correcta: 2,
    explicacion: 'Andorra es un Estado. Independiente, entre España y Francia.',
  },
  {
    id: 'viejo-general-x1-historia-040',
    tipo: 'bomba',
    enunciado: '¿En qué siglo se sitúa el descubrimiento de América por Colón?',
    opciones: ['XIV', 'XV', 'XVI', 'XVII'],
    correcta: 1,
    explicacion: '1492 es siglo XV.',
  },
  {
    id: 'viejo-general-x1-ciencia-075',
    tipo: 'bomba',
    enunciado: '¿Qué gas respiramos sobre todo (el que nos mantiene vivos)?',
    opciones: ['Nitrógeno', 'Oxígeno', 'CO2', 'Helio'],
    correcta: 1,
    explicacion: 'El aire es ~78% nitrógeno, pero el que usamos es O2.',
  },
  {
    id: 'viejo-general-x2-espana-093',
    tipo: 'bomba',
    enunciado: '¿Cuál es el río más largo de la península ibérica?',
    opciones: ['Ebro', 'Tajo', 'Duero', 'Guadalquivir'],
    correcta: 1,
    explicacion: 'Nace en España y muere en Portugal. El más largo solo español suele ser el Ebro.',
  },
  {
    id: 'viejo-general-x2-espana-101',
    tipo: 'bomba',
    enunciado: '¿Cuántas provincias tiene España?',
    opciones: ['17', '50', '52', '48'],
    correcta: 1,
    explicacion: '50 provincias; 52 si cuentas Ceuta y Melilla como «provincia-like» en INE a veces, pero el número oficial de provincias es 50.',
  },
];
